<?php
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter($driver);
    $mainFields = $formatter->getData($formatter->getDefaults('description'));
?>
<?php /** MSU: changed this block (no_description as a p, table attributes, th scope) */ ?>
<?php if (empty($mainFields)): ?>
  <p><?=$this->transEsc('no_description')?></p>
<?php else: ?>
  <table>
    <caption class="sr-only"><?=$this->transEsc('Description')?></caption>
    <?php foreach ($mainFields as $current): ?>
      <tr><th scope="row"><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
