<?php
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter($this->driver);
    $mainFields = $formatter->getData($formatter->getDefaults('description'));
?>
<table>
<?php /** MSU: changed this block (no_description as a p, table attributes, th scope) */ ?>
  <caption class="visually-hidden"><?=$this->transEsc('Description')?></caption>
  <?php if (!empty($mainFields)): ?>
    <?php foreach ($mainFields as $current): ?>
      <tr><th scope="row"><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
    <?php endforeach; ?>
  <?php else: ?>
    <p><?=$this->transEsc('no_description')?></p>
  <?php endif; ?>
</table>
