<?php
    // Set page title.
    $this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());
?>
<table class="citation table table-striped">
  <?php foreach ($this->driver->getRawData() as $field => $values): ?>
    <tr>
      <th><?=$this->escapeHtml($field)?></th>
      <td>
        <?php foreach ((array)$values as $value): ?>
          <?= $this->printArrayHtml($value); ?>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
