<?php
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    // MSUL Customizations to split TOC data by indicator PC-927

    $toc = $this->tab->getContent();
    $driverToc = $this->driver->getContentsNotes();
    if (!empty($driverToc)) {
        $toc['RecordDriver'] = $driverToc;
    }

    $incompleteToc = $this->tab->getContent();
    $driverToc = $this->driver->getIncompleteContentsNotes();
    if (!empty($driverToc)) {
        $incompleteToc['RecordDriver'] = $driverToc;
    }

    $partialToc = $this->tab->getContent();
    $driverToc = $this->driver->getPartialContentsNotes();
    if (!empty($driverToc)) {
        $partialToc['RecordDriver'] = $driverToc;
    }
?>
<?php if (!empty($toc)): ?>
  <strong><?=$this->transEsc('Contents')?>: </strong>
  <?php foreach ($toc as $provider => $content): ?>
    <?php if (!is_array($content)): // treat non-array content as raw HTML ?>
      <?=$content?>
    <?php else: ?>
      <ul class="toc">
      <?php foreach ($content as $line): ?>
        <li><?=$this->escapeHtml($line)?></li>
      <?php endforeach; ?>
      </ul>
    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>
<?php if (!empty($incompleteToc)): ?>
  <strong><?=$this->transEsc('Incomplete Contents')?>: </strong>
  <?php foreach ($incompleteToc as $provider => $content): ?>
    <?php if (!is_array($content)): // treat non-array content as raw HTML ?>
      <?=$content?>
    <?php else: ?>
      <ul class="toc">
      <?php foreach ($content as $line): ?>
        <li><?=$this->escapeHtml($line)?></li>
      <?php endforeach; ?>
      </ul>
    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>
<?php if (!empty($partialToc)): ?>
  <strong><?=$this->transEsc('Partial Contents')?>: </strong>
  <?php foreach ($partialToc as $provider => $content): ?>
    <?php if (!is_array($content)): // treat non-array content as raw HTML ?>
      <?=$content?>
    <?php else: ?>
      <ul class="toc">
      <?php foreach ($content as $line): ?>
        <li><?=$this->escapeHtml($line)?></li>
      <?php endforeach; ?>
      </ul>
    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>
<?php if (empty($toc) && empty($incompleteToc) && empty($partialToc)): ?>
  <?=$this->transEsc('Table of Contents unavailable')?>.
<?php endif; ?>
