---
version: "3.8"

services:
  catalog:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:latest 
    volumes:
      - logs:/var/log/apache2
    networks:
      - public
      - internal
    volumes:
      - /mnt/shared:/mnt/shared:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        order: start-first
      labels:
        - "traefik.enable=true"
        # HTTP Configuration
        - "traefik.http.routers.${STACK_NAME}-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-http-router.middlewares=http-redirect"
        - "traefik.http.routers.${STACK_NAME}-http-router.service=${STACK_NAME}-http-app"
        - "traefik.http.services.${STACK_NAME}-http-app.loadbalancer.server.port=80"
        # HTTPS Configuration
        - "traefik.http.routers.${STACK_NAME}-https-router.tls=true"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt"
        - "traefik.http.routers.${STACK_NAME}-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-router.middlewares=fix-prefix"
        - "traefik.http.routers.${STACK_NAME}-https-router.service=${STACK_NAME}-https-app"
        - "traefik.http.services.${STACK_NAME}-https-app.loadbalancer.server.port=80"

  harvest:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:latest
    command: /startup-cron.sh
    volumes:
      - /mnt/shared:/mnt/shared:rw
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
