---
version: "3.8"

services:
  # https://crazymax.dev/swarm-cronjob/
  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Detroit"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  prune-nodes:
    image: docker
    command: ["docker", "system", "prune", "-a", "-f"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 */30 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
      update_config:
        failure_action: rollback
