---
version: "3.8"

services:
  monitoring:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/monitoring:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    hostname: monitoring{{slice .Node.Hostname 8 9}}
    volumes:
      - logs:/mnt/logs
      - traefik_logs:/mnt/traefik_logs
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      NODE: "{{slice .Node.Hostname 8 9}}"
      STACK_NAME: "${STACK_NAME}"
      # secrets are prefixed with stack name in deploy-compose
      MARIADB_MONITORING_PASSWORD_FILE: /run/secrets/MARIADB_MONITORING_PASSWORD
      MARIADB_VUFIND_PASSWORD_FILE: /run/secrets/MARIADB_VUFIND_PASSWORD
    secrets: # secrets are prefixed with stack name in deploy-compose
      - MARIADB_MONITORING_PASSWORD
      - MARIADB_VUFIND_PASSWORD
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 10s

  proxymon-$STACK_NAME:
    image: bitnami/nginx
    networks:
      - public
      - internal
    volumes:
      - /mnt/shared/local/${STACK_NAME}/deploy/proxymonitoring/proxymonitoring.conf:/opt/bitnami/nginx/conf/server_blocks/proxymonitoring.conf:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.service=${STACK_NAME}-msul-proxymonitoring-app"
        - "traefik.http.services.${STACK_NAME}-msul-proxymonitoring-app.loadbalancer.server.port=8080"
        - "traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.middlewares=http-redirect"
        - "traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.service=${STACK_NAME}-https-msul-proxymonitoring-app"
        - "traefik.http.services.${STACK_NAME}-https-msul-proxymonitoring-app.loadbalancer.server.port=8080"
        - "traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.middlewares=restrict-auth"
        - "traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls=true"

networks:
  internal:
    name: ${STACK_NAME}-internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
    external: true
    name: "${STACK_NAME}_logs"
  traefik_logs:
    external: true
    name: "traefik_logs"

secrets: # secrets are prefixed with stack name in deploy-compose
  MARIADB_MONITORING_PASSWORD:
    external: true
  MARIADB_VUFIND_PASSWORD:
    external: true
