---
x-solr-envs: &solr_envs
  SOLR_ENABLE_CLOUD_MODE: "yes"
  SOLR_NUMBER_OF_NODES: 3
  SOLR_ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
  SOLR_JAVA_MEM: -Xms1g -Xmx4g
  SOLR_OPTS: "-Dsolr.allowPaths=/mnt/solr_backups"

x-zookeeper-envs: &zookeeper_envs
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ZOO_SERVERS: zk1:2888:3888::1 zk2:2888:3888::2 zk3:2888:3888::3
  ZOO_LISTEN_ALLIPS_ENABLED: "yes"
  ZOO_4LW_COMMANDS_WHITELIST: srvr,mntr,conf,ruok,stat

x-solr-deploy: &solr_deploy
  mode: replicated
  replicas: 3
  restart_policy:
    window: 15s
  update_config:
    parallelism: 1
    delay: 10s
    monitor: 10s
  placement:
    max_replicas_per_node: 1
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${STACK_NAME}-msul-solr-router.entrypoints=msul-http-ent"
    - "traefik.http.routers.${STACK_NAME}-msul-solr-router.service=${STACK_NAME}-msul-solr-app"
    - "traefik.http.services.${STACK_NAME}-msul-solr-app.loadbalancer.server.port=8983"
    - "traefik.http.routers.${STACK_NAME}-msul-solr-router.middlewares=http-redirect"
    - "traefik.http.routers.${STACK_NAME}-https-msul-solr-router.entrypoints=msul-https-ent"
    - "traefik.http.routers.${STACK_NAME}-https-msul-solr-router.service=${STACK_NAME}-https-msul-solr-app"
    - "traefik.http.services.${STACK_NAME}-https-msul-solr-app.loadbalancer.server.port=8983"
    - "traefik.http.routers.${STACK_NAME}-https-msul-solr-router.middlewares=restrict-auth"
    - "traefik.http.routers.${STACK_NAME}-https-msul-solr-router.tls=true"

version: "3.8"
services:
  solr:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/solr:${CI_COMMIT_SHORT_SHA}
    volumes:
      - bitnami:/bitnami
      - /mnt/shared/backups/solr_dropbox:/mnt/solr_backups
    hostname: solr{{slice .Node.Hostname 8 9}}
    networks:
      - public
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      SOLR_HOST: solr{{slice .Node.Hostname 8 9}}
      <<: *solr_envs
    deploy:
      <<: *solr_deploy

  zk:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/zk:${CI_COMMIT_SHORT_SHA}
    volumes:
      - zk-bitnami:/bitnami
    hostname: zk{{slice .Node.Hostname 8 9}}
    environment:
      ZOO_SERVER_ID: "{{slice .Node.Hostname 8 9}}"
      <<: *zookeeper_envs
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
      restart_policy:
        window: 15s

  cron:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/solr:${CI_COMMIT_SHORT_SHA}
    command: /startup-cron.sh
    user: "0"
    volumes:
      - bitnami:/bitnami
      - /mnt/shared:/mnt/shared:rw
      - logs:/mnt/logs
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    healthcheck:
      disable: true
    environment:
      NODE: "{{slice .Node.Hostname 8 9}}"
      STACK_NAME: "${STACK_NAME}"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        max_replicas_per_node: 1

networks:
  internal:
    name: ${STACK_NAME}-internal
    external: true
  public:
    name: public
    external: true

volumes:
  bitnami:
  zk-bitnami:
  logs:
    external: true
    name: "${STACK_NAME}_logs"
