---
version: "3.8"

services:
  catalog:
    image: catalog:latest
    volumes:
      - logs:/var/log/apache2
    networks:
      - public
      - internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        # HTTP Configuration
        - "traefik.http.routers.msul-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.msul-http-router.rule=\
            Host(`catalog-a.aws.lib.msu.edu`, `catalog-b.aws.lib.msu.edu`, `catalog-c.aws.lib.msu.edu`)"
        - "traefik.http.middlewares.msul-http-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.msul-http-redirect.redirectscheme.permanent=true"
        - "traefik.http.middlewares.msul-fix-prefix.replacepathregex.regex=^/(vufind/)?(.*)"
        - "traefik.http.middlewares.msul-fix-prefix.replacepathregex.replacement=/vufind/$$2"
        - "traefik.http.routers.msul-http-router.middlewares=msul-fix-prefix"
        #- "traefik.http.middlewares.msul-add-prefix.addprefix.prefix=/vufind"
        #- "traefik.http.routers.msul-http-router.middlewares=msul-add-prefix"
        - "traefik.http.routers.msul-http-router.service=msul-http-app"
        - "traefik.http.services.msul-http-app.loadbalancer.server.port=80"

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
