---
x-solr-envs: &solr_envs
  SOLR_ENABLE_CLOUD_MODE: "yes"
  SOLR_NUMBER_OF_NODES: 3
  SOLR_ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
  SOLR_JAVA_MEM: -Xms8192m -Xmx8192m -XX:MaxDirectMemorySize=2560m
  SOLR_OPTS: "-Dsolr.allowPaths=/mnt/solr_backups"
  STACK_NAME: "${STACK_NAME}"

version: "3.8"
services:
  solr:
    environment:
      SOLR_HOST: solr{{slice .Node.Hostname 8 9}}
      <<: *solr_envs
