---
version: "3.8"

services:
  catalog:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:latest 
    volumes:
      - logs:/var/log/apache2
    networks:
      - public
      - internal
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
      labels:
        - "traefik.enable=true"
        # Redirect Middleware
        - "traefik.http.middlewares.http-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.http-redirect.redirectscheme.permanent=true"
        # Middleware to add /vufind to path
        - "traefik.http.middlewares.fix-prefix.replacepathregex.regex=^/(vufind/)?(.*)"
        - "traefik.http.middlewares.fix-prefix.replacepathregex.replacement=/vufind/$$2"
        # HTTP Configuration
        - "traefik.http.routers.http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.http-router.rule=\
            Host(`catalog.aws.lib.msu.edu`, `catalog-beta.lib.msu.edu`)"
        - "traefik.http.routers.http-router.middlewares=http-redirect"
        - "traefik.http.routers.http-router.service=http-app"
        - "traefik.http.services.http-app.loadbalancer.server.port=80"
        # HTTPS Configuration
        - "traefik.http.routers.https-router.tls=true"
        - "traefik.http.routers.https-router.tls.certresolver=msul-letsencrypt"
        - "traefik.http.routers.https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.https-router.rule=\
            Host(`catalog.aws.lib.msu.edu`, `catalog-beta.lib.msu.edu`)"
        - "traefik.http.routers.https-router.middlewares=fix-prefix"
        - "traefik.http.routers.https-router.service=https-app"
        - "traefik.http.services.https-app.loadbalancer.server.port=80"

  harvest:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:latest
    command: cron -f -L 4
    volumes:
      - /mnt/shared:/mnt/shared
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
