---
#include vufind-envs

version: "3.8"

services:
  build:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    command: /startup-build.sh
    volumes:
      - logs:/mnt/logs
      - /mnt/shared:/mnt/shared:rw
      - /usr/local/bin/pc-locate-oai:/usr/local/bin/pc-locate-oai:ro
      - /etc/bash_completion.d/pc-locate-oai:/etc/bash_completion.d/pc-locate-oai:ro
      # Requires rw so it can restore from backups
      - /mnt/shared/alpha-browse/${STACK_NAME}:/mnt/alpha-browse:ro
      - /mnt/shared/local/devel-robby/core-repo/public/:/usr/local/vufind/public/:rw
      - /mnt/shared/local/devel-robby/core-repo/vendor/:/usr/local/vufind/vendor/:rw
      - /mnt/shared/local/devel-robby/core-repo/themes/bootprint3/:/usr/local/vufind/themes/bootprint3/:rw
      - /mnt/shared/local/devel-robby/core-repo/themes/bootstrap3/:/usr/local/vufind/themes/bootstrap3/:rw
      - /mnt/shared/local/devel-robby/repo/vufind/themes/msul/:/usr/local/vufind/themes/msul/:rw
      - /mnt/shared/local/devel-robby/core-repo/themes/root/:/usr/local/vufind/themes/root/:rw
      - /mnt/shared/local/devel-robby/core-repo/themes/sandal/:/usr/local/vufind/themes/sandal/:rw
      - /mnt/shared/local/devel-robby/repo/vufind/module/Catalog/:/usr/local/vufind/module/Catalog/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFind/:/usr/local/vufind/module/VuFind/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindAdmin/:/usr/local/vufind/module/VuFindAdmin/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindApi/:/usr/local/vufind/module/VuFindApi/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindConsole/:/usr/local/vufind/module/VuFindConsole/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindDevTools/:/usr/local/vufind/module/VuFindDevTools/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindLocalTemplate/:/usr/local/vufind/module/VuFindLocalTemplate/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindSearch/:/usr/local/vufind/module/VuFindSearch/:rw
      - /mnt/shared/local/devel-robby/core-repo/module/VuFindTheme/:/usr/local/vufind/module/VuFindTheme/:rw
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    healthcheck:
      disable: true
    environment:
      STACK_NAME: "${STACK_NAME}"
      NODE: "{{slice .Node.Hostname 8 9}}"
      <<: *vufind_envs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s

networks:
  internal:
    name: ${STACK_NAME}-internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
    external: true
    name: "${STACK_NAME}_logs"
