---
version: "3.8"
services:
  # Stack deploys require a network be used by at least 1 service
  # or Swarm will skip creating that network. Hence this service.
  health:
    image: alpine:latest
    command: sleep inf
    networks:
      - internal
    #healthcheck:
    #  test: >
    #    GATEWAY_IP=$$( ip addr show eth0 | grep "^\s\+inet" | awk '{ print $$2 }' | sed 's/\d\+\/24/2/' );
    #    ping -W1 -c1 "$${GATEWAY_IP}" 1>/dev/null 2>&1;
    #  interval: 30s
    #  timeout: 5s
    #  retries: 1
    #  start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s

# Internal network used by backend stacks (e.g. Solr, MariaDB)
networks:
  internal:
    name: internal
    driver: overlay
