---
version: "3.8"

services:
  monitoring:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/monitoring:latest
    volumes:
      - logs:/mnt/logs
    networks:
      - public
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      NODE: "{{slice .Node.Hostname 8 9}}"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-http-router.middlewares=http-redirect"
        - "traefik.http.routers.${STACK_NAME}-http-router.service=${STACK_NAME}-http-app"
        - "traefik.http.routers.${STACK_NAME}-http-router.rule=Host(`catalog.aws.lib.msu.edu`) && PathPrefix(`/monitoring`)"
        - "traefik.http.services.${STACK_NAME}-http-app.loadbalancer.server.port=80"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls=true"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt-dns"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].main=aws.lib.msu.edu"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].sans=*.aws.lib.msu.edu"
        - "traefik.http.routers.${STACK_NAME}-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-router.service=${STACK_NAME}-https-app"
        - "traefik.http.services.${STACK_NAME}-https-app.loadbalancer.server.port=80"

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
