---
x-solr-envs: &solr_envs
  SOLR_ENABLE_CLOUD_MODE: "yes"
  SOLR_NUMBER_OF_NODES: 3
  SOLR_ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
  SOLR_JAVA_MEM: -Xms1g -Xmx4g

x-zookeeper-envs: &zookeeper_envs
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ZOO_SERVERS: zk1:2888:3888::1 zk2:2888:3888::2 zk3:2888:3888::3
  ZOO_LISTEN_ALLIPS_ENABLED: "yes"
  ZOO_4LW_COMMANDS_WHITELIST: srvr,mntr,conf,ruok,stat

x-solr-deploy: &solr_deploy
  mode: replicated
  replicas: 3
  restart_policy:
    window: 15s
  update_config:
    parallelism: 1
    failure_action: rollback
    delay: 10s
  placement:
    max_replicas_per_node: 1
  labels:
    # These labels need to stay in this order for the CI to work
    - "traefik.enable=true"
    - "traefik.http.routers.msul-solr-router.entrypoints=msul-http-ent"
    - "traefik.http.routers.msul-solr-router.service=msul-solr-app"
    - "traefik.http.services.msul-solr-app.loadbalancer.server.port=8983"
    - "traefik.http.routers.msul-solr-router.rule=Host(`catalog.aws.lib.msu.edu`) && PathPrefix(`/solr`)"
    # NEW
    - "traefik.http.routers.devel-solr-msul-solr-router.middlewares=http-redirect"
    - "traefik.http.routers.devel-solr-https-msul-solr-router.entrypoints=msul-https-ent"
    - "traefik.http.routers.devel-solr-https-msul-solr-router.service=devel-solr-https-msul-solr-app"
    - "traefik.http.routers.devel-solr-https-msul-solr-router.middlewares=restrict-auth"
    - "traefik.http.routers.devel-solr-https-msul-solr-router.rule=Host(`devel-solr.aws.lib.msu.edu`) && PathPrefix(`/solr`)"
    - "traefik.http.routers.devel-solr-https-msul-solr-router.tls=true"
    - "traefik.http.routers.devel-solr-https-msul-solr-router.tls.certresolver=msul-letsencrypt"
    - "traefik.http.services.devel-solr-https-msul-solr-app.loadbalancer.server.port=8983"

version: "3.8"
services:
  solr:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/solr:latest
    volumes:
      - bitnami:/bitnami
    hostname: solr{{.Task.Slot}}
    networks:
      - public
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      SOLR_HOST: solr{{.Task.Slot}}
      <<: *solr_envs
    deploy:
      <<: *solr_deploy

  zk1:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/zk:latest
    volumes:
      - zk-bitnami:/bitnami
    #hostname: zk{{.Task.Slot}}
    environment:
      ZOO_SERVER_ID: 1
      <<: *zookeeper_envs
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        window: 15s
      placement:
        constraints:
          - "node.labels.nodeid==1"

  zk2:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/zk:latest
    volumes:
      - zk-bitnami:/bitnami
    environment:
      ZOO_SERVER_ID: 2
      <<: *zookeeper_envs
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        window: 15s
      placement:
        constraints:
          - "node.labels.nodeid==2"

  zk3:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/zk:latest
    volumes:
      - zk-bitnami:/bitnami
    environment:
      ZOO_SERVER_ID: 3
      <<: *zookeeper_envs
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        window: 15s
      placement:
        constraints:
          - "node.labels.nodeid==3"
  cron:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/solr:latest
    command: /startup-cron.sh
    user: "0"
    volumes:
      - bitnami:/bitnami
      - /mnt/shared:/mnt/shared:rw
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    healthcheck:
      disable: true
    environment:
      NODE: "{{.Task.Slot}}"
      STACK_NAME: "catalog-beta"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      placement:
        max_replicas_per_node: 1

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true

volumes:
  bitnami:
  zk-bitnami:
