---
version: "3.8"

services:
  # Load balancer for internal services. E.g. solr, mariadb
  lb:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/traefik-internal:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
      - target: 8983
        published: 8983
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp
    networks:
      - internal
    command:
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=internal
      # TODO -- add restriction to solr entrypoint in solr.yml
      - --providers.file.directory=/etc/traefik_providers
      - --providers.file.watch=true
      - --entrypoints.msul-db-ent.address=:3306
      #- --entrypoints.msul-solr-ent.address=:8983
      # - --entrypoints.msul-dashboard-ent.address=:8080
      - --log
      - --log.level=WARN
      - --accesslog
      - --entrypoints.health-ent.address=127.0.0.1:8081
      - --ping
      - --ping.entrypoint=health-ent
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --api.dashboard=true
    healthcheck:
      test: >
        traefik healthcheck \
          --entrypoints.health-ent.address=127.0.0.1:8081 \
          --ping \
          --ping.entrypoint=health-ent
      interval: 15s
      timeout: 5s
      retries: 1
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        order: start-first
#      labels:
#        - "traefik.enable=true"
#        - "traefik.http.routers.msul-dashboard-router.entrypoints=msul-dashboard-ent"
#        - "traefik.http.routers.msul-dashboard-router.rule=\
#            PathPrefix(`/dashboard`) && PathPrefix(`/api`)"
#        - "traefik.http.routers.msul-dashboard-router.service=api@internal"
#        - "traefik.http.services.msul-dashboard-app.loadbalancer.server.port=9999"

networks:
  internal:
    name: internal
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.1.0/24
