---
x-mariadb-envs: &mariadb_envs
  TZ: America/Detroit
  MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
  MARIADB_ROOT_PASSWORD: 12345
  MARIADB_GALERA_MARIABACKUP_PASSWORD: 123456
  MARIADB_DATABASE: vufind
  MARIADB_USER: vufind
  MARIADB_PASSWORD: vufind
  MARIADB_SKIP_TEST_DB: "yes"
  MARIADB_CHARACTER_SET: utf8mb4
  MARIADB_COLLATE: utf8mb4_unicode_ci
  MARIADB_EXTRA_FLAGS: --old_passwords=OFF --default-authentication-plugin=mysql_native_password --secure_auth=ON

version: "3.8"

######### WARNING ########
# Before force bootstrapping a node, ensure it was the last node to be stopped.
# This will require you to manually inspect SQL files to find the node which
# has file with the most recent "last modified" date on them.
#
# Once identified, manually set the deploy constraints "node.labels.nodeid==N"
# where N is the host node containing the most recent files.
# Only then should increment max_replicas_per_node to 1 and attempt
# to force bootstrap the cluster.
#
# As an additional precaution, you may want to make backups of all the
# MariaDB volumes data prior to proceeding.
######### WARNING ########

services:
  galera:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/db:latest
    hostname: galera{{slice .Node.Hostname 8 9}}
    networks:
      - internal
    environment:
      GALERA_HOST: galera{{slice .Node.Hostname 8 9}}
      # This flag is required when cold-starting the cluster
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "yes"
      # This flag is only needed when starting cluster from node where grastate.dat has "safe_to_bootstrap: 0"
      MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP: "yes"
      <<: *mariadb_envs
    volumes:
      - db-bitnami:/bitnami
    stop_signal: SIGWINCH
    stop_grace_period: 80s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 70s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 90s
      placement:
        constraints:
          # Update N to be the Docker Swarm node number with most recent SQL file changes
          - "node.labels.nodeid==N"
        # Increment to 1 when you are ready to deploy (make backups of volumes beforehand!)
        max_replicas_per_node: 0

networks:
  internal:
    name: internal
    external: true

volumes:
  db-bitnami:
