---
x-mariadb-envs: &mariadb_envs
  TZ: America/Detroit
  MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
  MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}" # TESTING
  MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
#  MARIADB_GALERA_MARIABACKUP_PASSWORD: "${MARIADB_GALERA_MARIABACKUP_PASSWORD}" # SEEMS OK
  MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/MARIADB_GALERA_MARIABACKUP_PASSWORD
  MARIADB_DATABASE: vufind
  MARIADB_USER: vufind
#  MARIADB_PASSWORD: "${MARIADB_VUFIND_PASSWORD}" # SEEMS OK
  MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
#  MARIADB_MONITORING_PASSWORD: "${MARIADB_MONITORING_PASSWORD}" # SEEMS OK
  MARIADB_MONITORING_PASSWORD_FILE: /run/secrets/MARIADB_MONITORING_PASSWORD
  MARIADB_SKIP_TEST_DB: "yes"
  MARIADB_CHARACTER_SET: utf8mb4
  MARIADB_COLLATE: utf8mb4_unicode_ci
  MARIADB_EXTRA_FLAGS: --old_passwords=OFF --default-authentication-plugin=mysql_native_password --secure_auth=ON

version: "3.8"
services:
  galera:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/db:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    hostname: galera{{slice .Node.Hostname 8 9}}
    networks:
      - internal
    environment:
      GALERA_HOST: galera{{slice .Node.Hostname 8 9}}
      <<: *mariadb_envs
    volumes:
      - db-bitnami:/bitnami
      - logs:/mnt/logs
    stop_signal: SIGWINCH
    stop_grace_period: 80s
    ulimits:
      nproc: 32768
      nofile: 32768
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        window: 160s
      update_config:
        parallelism: 1
        failure_action: pause
        delay: 30s
        monitor: 20s
        order: stop-first
      placement:
        max_replicas_per_node: 1
    secrets:
      - MARIADB_MONITORING_PASSWORD
      - MARIADB_ROOT_PASSWORD
      - MARIADB_GALERA_MARIABACKUP_PASSWORD
      - MARIADB_PASSWORD

networks:
  internal:
    name: ${STACK_NAME}-internal
    external: true

volumes:
  db-bitnami:
  logs:
    external: true
    name: "${STACK_NAME}_logs"

secrets:
  MARIADB_MONITORING_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_GALERA_MARIABACKUP_PASSWORD:
    external: true
  MARIADB_PASSWORD:
    external: true
