---
version: "3.8"

services:
  prune-nodes:
    image: docker
    command: ["docker", "system", "prune", "-a", "-f"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      restart_policy:
        delay: 30m
      update_config:
        failure_action: rollback
