---
version: "3.8"

services:
  # Load balancer for internal services. E.g. mariadb
  lb:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/traefik-internal:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    command:
      # This flag must be first for the CI/CD to replace the network name correctly
      - --providers.docker.network=internal
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefik_providers
      - --providers.file.watch=true
      - --entrypoints.msul-db-ent.address=:3306
      - --log
      - --log.level=WARN
      - --accesslog
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --api.dashboard=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
      restart_policy:
        window: 15s
#      labels:
#        - "traefik.enable=true"
#        - "traefik.http.routers.msul-dashboard-router.entrypoints=msul-dashboard-ent"
#        - "traefik.http.routers.msul-dashboard-router.rule=\
#            PathPrefix(`/dashboard`) && PathPrefix(`/api`)"
#        - "traefik.http.routers.msul-dashboard-router.service=api@internal"
#        - "traefik.http.services.msul-dashboard-app.loadbalancer.server.port=9999"

networks:
  internal:
    name: internal
    driver: overlay
