---
version: "3.8"

services:
  catalog:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:latest 
    volumes:
      - logs:/var/log/apache2
    networks:
      - public
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /mnt/shared:/mnt/shared:rw
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      SAML_IDP_ENTITY_ID: "https://fujifish.github.io/samling/samling.html"
      STACK_NAME: "${STACK_NAME}"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        # HTTP Configuration
        - "traefik.http.routers.${STACK_NAME}-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-http-router.middlewares=http-redirect"
        - "traefik.http.routers.${STACK_NAME}-http-router.service=${STACK_NAME}-http-app"
        - "traefik.http.services.${STACK_NAME}-http-app.loadbalancer.server.port=80"
        # HTTPS Configuration
        - "traefik.http.routers.${STACK_NAME}-https-router.tls=true"
        # XXX The following two lines must be indexes 6, 7, 8 of 'labels' for CI to update correctly
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt-dns"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].main=aws.lib.msu.edu"
        - "traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].sans=*.aws.lib.msu.edu"
        - "traefik.http.routers.${STACK_NAME}-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-router.middlewares=fix-prefix,saml-prefix"
        - "traefik.http.routers.${STACK_NAME}-https-router.service=${STACK_NAME}-https-app"
        - "traefik.http.services.${STACK_NAME}-https-app.loadbalancer.server.port=80"

  cron:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:latest
    command: /startup-cron.sh
    volumes:
      - /mnt/shared:/mnt/shared:rw
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    healthcheck:
      disable: true
    environment:
      NODE: "{{slice .Node.Hostname 8 9}}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s
      update_config:
        failure_action: rollback

networks:
  internal:
    name: internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
