---
version: "3.8"

services:
  traefik:
    image: traefik:v2.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/etc/traefik
      - logs:/mnt/logs
      - ${PWD}/provider.yml:/etc/traefik_providers/provider.yml
    networks:
      - public
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    environment:
      # XXX: The environment will be replaced by traefik-env.yml during deploy
    # XXX: Error when it tries to parse the defaultRules:
    # executing \"\" at <.Labels>: can't evaluate field Labels in type bool
    command: "sh -c '
      touch /mnt/logs/traefik.log; touch /etc/traefik_providers; tail -f /mnt/logs/traefik.log &
      exec traefik --providers.file.directory=/etc/traefik_providers
      '"
    healthcheck:
      test: >
        traefik healthcheck \
          --entrypoints.health-ent.address=127.0.0.1:8081 \
          --ping \
          --ping.entrypoint=health-ent
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        window: 15s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik-public-traefik.loadbalancer.server.port=9999"
        # BasicAuth Middleware for restricted resources
        - "traefik.http.middlewares.restrict-auth.basicauth.users=${BASICAUTH_FOR_RESOURCES}"
        # Redirect Middleware
        - "traefik.http.middlewares.http-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.http-redirect.redirectscheme.permanent=true"
        # Middleware to add /vufind to path
        - "traefik.http.middlewares.fix-prefix.replacepathregex.regex=^/(vufind/)?(.*)"
        - "traefik.http.middlewares.fix-prefix.replacepathregex.replacement=/vufind/$$2"
        - "traefik.http.middlewares.saml-prefix.replacepathregex.regex=^/vufind/simplesamlphp/(.*)"
        - "traefik.http.middlewares.saml-prefix.replacepathregex.replacement=/simplesamlphp/$$1"
        # Redirect to remove /vufind prefix
        - "traefik.http.middlewares.remove-prefix.redirectregex.regex=^(https://[^/]+)/vufind(/.*)"
        - "traefik.http.middlewares.remove-prefix.redirectregex.replacement=$${1}$${2}"
        - "traefik.http.middlewares.remove-prefix.redirectregex.permanent=true"
        # Traefik Dashboard HTTP
        - "traefik.http.routers.dashboard-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.dashboard-http-router.middlewares=http-redirect"
        - "traefik.http.routers.dashboard-http-router.rule=Host(`catalog-proxy.aws.lib.msu.edu`)"
        - "traefik.http.routers.dashboard-http-router.service=api@internal"
        # Traefik Dashboard HTTPS
        - "traefik.http.routers.dashboard-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.dashboard-https-router.middlewares=restrict-auth"
        - "traefik.http.routers.dashboard-https-router.tls=true"
        - "traefik.http.routers.dashboard-https-router.tls.certresolver=msul-letsencrypt"
        - "traefik.http.routers.dashboard-https-router.rule=\
            Host(`catalog-proxy.aws.lib.msu.edu`) && \
            (PathPrefix(`/dashboard`) || PathPrefix(`/api`) || PathPrefix(`/debug`))"
        - "traefik.http.routers.dashboard-https-router.service=api@internal"

networks:
  public:
    name: public
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  traefik:
    driver: local
  logs:
    external: true
    name: "traefik_logs"
