---
version: "3.8"

services:
  catalog:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    hostname: vufind{{slice .Node.Hostname 8 9}}
    volumes:
      - logs:/mnt/logs
      - /mnt/shared:/mnt/shared:rw
      - vufind_cache:/mnt/vufind_cache
    networks:
      - public
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      STACK_NAME: "${STACK_NAME}"
      SITE_HOSTNAME: "${SITE_HOSTNAME}"
      NODE: "{{slice .Node.Hostname 8 9}}"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
        monitor: 10s
      labels:
        - "traefik.enable=true"
        # HTTP Configuration
        - "traefik.http.routers.${STACK_NAME}-http-router.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-http-router.middlewares=http-redirect"
        - "traefik.http.routers.${STACK_NAME}-http-router.service=${STACK_NAME}-http-app"
        - "traefik.http.services.${STACK_NAME}-http-app.loadbalancer.server.port=80"
        # HTTPS Configuration
        - "traefik.http.routers.${STACK_NAME}-https-router.tls=true"
        - "traefik.http.routers.${STACK_NAME}-https-router.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-router.service=${STACK_NAME}-https-app"
        - "traefik.http.services.${STACK_NAME}-https-app.loadbalancer.server.port=80"

  legacylinks:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/legacylinks:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    networks:
      - public
    environment:
      # SITE_HOSTNAME could be used to help handle redirects going to VuFind instead of EDS
      SITE_HOSTNAME: "${SITE_HOSTNAME}"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
        monitor: 10s
      labels:
        - "traefik.enable=true"
        # HTTP Configuration
        - "traefik.http.routers.${STACK_NAME}-http-links.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-http-links.middlewares=http-redirect"
        - "traefik.http.routers.${STACK_NAME}-http-links.service=${STACK_NAME}-http-links-app"
        - "traefik.http.services.${STACK_NAME}-http-links-app.loadbalancer.server.port=80"
        # HTTPS Configuration
        - "traefik.http.routers.${STACK_NAME}-https-links.tls=true"
        - "traefik.http.routers.${STACK_NAME}-https-links.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-links.service=${STACK_NAME}-https-links-app"
        - "traefik.http.services.${STACK_NAME}-https-links-app.loadbalancer.server.port=80"

  croncache:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    command: /startup-cachecron.sh
    volumes:
      - vufind_cache:/mnt/vufind_cache
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - internal
    healthcheck:
      disable: true
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s

  cron:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/vufind:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    command: /startup-cron.sh
    volumes:
      - logs:/mnt/logs
      - /mnt/shared:/mnt/shared:rw
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    healthcheck:
      disable: true
    environment:
      STACK_NAME: "${STACK_NAME}"
      SITE_HOSTNAME: "${SITE_HOSTNAME}"
      NODE: "{{slice .Node.Hostname 8 9}}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s

  mail-$STACK_NAME:
    image: sj26/mailcatcher
    command: [
        "--no-quit",
        "--ip", "0.0.0.0",
        "--smtp-port", "25",
        "--http-port", "80",
        "--http-path", "mail",
        "--messages-limit", "100"
    ]
    networks:
      - public
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 15s
      labels:
        - "traefik.enable=true"
        # HTTP Configuration
        - "traefik.http.routers.${STACK_NAME}-http-mail.entrypoints=msul-http-ent"
        - "traefik.http.routers.${STACK_NAME}-http-mail.service=${STACK_NAME}-http-mail-app"
        - "traefik.http.services.${STACK_NAME}-http-mail-app.loadbalancer.server.port=80"
        - "traefik.http.routers.${STACK_NAME}-http-mail.middlewares=http-redirect"
        # HTTPS Configuration
        - "traefik.http.routers.${STACK_NAME}-https-mail.entrypoints=msul-https-ent"
        - "traefik.http.routers.${STACK_NAME}-https-mail.service=${STACK_NAME}-https-mail-app"
        - "traefik.http.services.${STACK_NAME}-https-mail-app.loadbalancer.server.port=80"
        - "traefik.http.routers.${STACK_NAME}-https-mail.middlewares=restrict-auth"
        - "traefik.http.routers.${STACK_NAME}-https-mail.tls=true"

networks:
  internal:
    name: ${STACK_NAME}-internal
    external: true
  public:
    name: public
    external: true

volumes:
  logs:
    external: true
    name: "${STACK_NAME}_logs"
  vufind_cache:
