---
x-mariadb-envs: &mariadb_envs
  TZ: America/Detroit
  MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1,galera2,galera3
  MARIADB_ROOT_PASSWORD_FILE: /run/secrets/${STACK_NAME}-MARIADB_ROOT_PASSWORD
  MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE: /run/secrets/${STACK_NAME}-MARIADB_GALERA_MARIABACKUP_PASSWORD
  MARIADB_DATABASE: vufind
  MARIADB_USER: vufind
  MARIADB_PASSWORD_FILE: /run/secrets/${STACK_NAME}-MARIADB_PASSWORD
  MARIADB_MONITORING_PASSWORD_FILE: /run/secrets/${STACK_NAME}-MARIADB_MONITORING_PASSWORD
  MARIADB_SKIP_TEST_DB: "yes"
  MARIADB_CHARACTER_SET: utf8mb4
  MARIADB_COLLATE: utf8mb4_unicode_ci
  MARIADB_EXTRA_FLAGS: --old_passwords=OFF --default-authentication-plugin=mysql_native_password --secure_auth=ON

version: "3.8"

######### WARNING ########
# Before force bootstrapping a node, ensure it was the last node to be stopped.
# This will require you to manually inspect SQL files to find the node which
# has file with the most recent "last modified" date on them.
#
# Once identified, manually set the deploy constraints "node.labels.nodeid==N"
# where N is the host node containing the most recent files.
# Only then should increment max_replicas_per_node to 1 and attempt
# to force bootstrap the cluster.
#
# As an additional precaution, you may want to make backups of all the
# MariaDB volumes data prior to proceeding.
#
# Once the cluster has recovered, remove the stack again and re-deploy
# with the docker-compose.mariadb-cloud.yml to remove the bootstrap
# setting from the stack.
######### WARNING ########

services:
  galera:
    image: registry.gitlab.msu.edu/msu-libraries/devops/catalog/db:${CI_COMMIT_SHORT_SHA}${EXTRA_TAG_SUFFIX}
    hostname: galera{{slice .Node.Hostname 8 9}}
    networks:
      - internal
    environment:
      GALERA_HOST: galera{{slice .Node.Hostname 8 9}}
      # This flag is required when cold-starting the cluster
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "yes"
      # This flag is only needed when starting cluster from node where grastate.dat has "safe_to_bootstrap: 0"
      MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP: "yes"
      <<: *mariadb_envs
    secrets:
      - ${STACK_NAME}-MARIADB_MONITORING_PASSWORD
      - ${STACK_NAME}-MARIADB_ROOT_PASSWORD
      - ${STACK_NAME}-MARIADB_GALERA_MARIABACKUP_PASSWORD
      - ${STACK_NAME}-MARIADB_PASSWORD
    volumes:
      - db-bitnami:/bitnami
      - logs:/mnt/logs
    stop_signal: SIGWINCH
    stop_grace_period: 80s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        window: 160s
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 140s
        monitor: 20s
      placement:
        ### YOU MUST BRING THE STACK DOWN BEFORE AND AFTER USING THIS FILE AND RE-DEPLOY WITH
        ### THE NORMAL COMPOSE FILE ONCE GALERA HAS RECOVERED SO THAT BOOTSTRAPING CAN BE DISABLED
        constraints:
          # Update N to be the Docker Swarm node number with most recent SQL file changes
          - "node.labels.nodeid==N"
        # Increment to 1 when you are ready to deploy (make backups of volumes beforehand!)
        max_replicas_per_node: 0

networks:
  internal:
    name: ${STACK_NAME}-internal
    external: true

volumes:
  db-bitnami:
  logs:
    external: true
    name: "${STACK_NAME}_logs"

secrets:
  ${STACK_NAME}-MARIADB_MONITORING_PASSWORD:
    external: true
  ${STACK_NAME}-MARIADB_ROOT_PASSWORD:
    external: true
  ${STACK_NAME}-MARIADB_GALERA_MARIABACKUP_PASSWORD:
    external: true
  ${STACK_NAME}-MARIADB_PASSWORD:
    external: true
