site_name: MSU Libraries Public Catalog Technical Documentation
repo_url: https://github.com/MSU-Libraries/catalog
repo_name: MSU-Libraries/catalog

theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.instant

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

plugins:
- search:

nav:
- Welcome: index.md
- Getting Started:
    - Technical Overview: tech-overview.md
    - First Time Setup: first-time-setup.md
    - Harvesting: harvesting.md
    - CI/CD: CICD.md
    - Troubleshooting: troubleshooting.md
