site_name: MSU Libraries Public Catalog Technical Documentation
repo_url: https://github.com/MSU-Libraries/catalog
repo_name: MSU-Libraries/catalog

theme:
  name: "material"
  features:
    - navigation.expand
    - navigation.instant

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
- tables
- footnotes
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- search:

nav:
- Welcome: index.md
- Getting Started:
    - Technical Overview: tech-overview.md
    - First Time Setup: first-time-setup.md
    - Harvesting &amp; Importing: harvesting-and-importing.md
    - CI/CD: CICD.md
- Administration:
    - Backup &amp; Restore: backup-and-restore.md
    - Upgrading: upgrading.md
    - VuFind: vufind.md
    - Solr: solr.md
    - MariaDB: mariadb.md
    - Traefik: traefik.md
    - Monitoring App: monitoring.md
    - Load Testing: load-testing.md
    - Helper Scripts: helper-scripts.md
    - Bots: bots.md
    - Job Schedules: job-schedules.md
- Developing:
    - Writing &amp; Running Tests: testing.md
    - Using Core VuFind Only: core-vufind.md
    - Alphabrowse Internals: alphabrowse.md
    - Documentation: documentation.md
