<?php
use Catalog\GetThis\GetThisLoader; /** MSU */

?>
<?php if ($this->holdings()->holdingIsVisible($holding)): ?>
  <?php
    $check = $holding['check'] ?? false;
    $checkStorageRetrievalRequest = $holding['checkStorageRetrievalRequest'] ?? false;
    $checkILLRequest = $holding['checkILLRequest'] ?? false;
    $availabilityStatus = $holding['availability'];
    /** MSU START */
    # TODO is $holding actually an item record? possibly!
    $id = $holding['id'];
    $item_id = $holding['item_id'];
    $getthis = new GetThisLoader($record, [$holding]);
    $callnum = $getthis->getCallNumber($item_id);
    /** MSU END */
  ?>
  <tr class="holding-row"<?=$this->schemaOrg()->getAttributes(['vocab' => 'http://schema.org/', 'typeof' => 'Offer'])?>>
    <th class="copy-number"><?php /** MSU */ ?>
      <?php if ($callnum ?? false): /** MSU */ ?>
        <span><?=$this->escapeHtml($callnum) ?></span><?php /** MSU */ ?>
      <?php endif; ?>
    </th>
    <td>
      <?php if ($holding['reserve'] == 'Y'): ?>
        <?=$this->schemaOrg()->getLink('http://schema.org/InStoreOnly', 'availability')?>
        <?=$this->transEsc('On Reserve - Ask at Circulation Desk')?><br>
      <?php endif; ?>
      <?php
        $statusClass = $this->availabilityStatus()->getClass($availabilityStatus);
        $statusDescription = $getthis->getStatus($item_id); /** MSU */
        $statusDescriptionTokens = $availabilityStatus->getStatusDescriptionTokens();
        $schemaAvailabilityUri = $availabilityStatus->getSchemaAvailabilityUri();
      ?>
      <span class="<?=$this->escapeHtmlAttr($statusClass)?>">
        <?=$this->transEsc($statusDescription, $statusDescriptionTokens)?>
        <?php if ($schemaAvailabilityUri): ?>
          <?=$this->schemaOrg()->getLink($schemaAvailabilityUri, 'availability')?>
        <?php endif; ?>
      </span>
      <?php if ($availabilityStatus->isAvailable()): ?>
        <?php /* Begin Available Items (Holds) */ ?>
        <?php /** MSU START */ ?>
        <?php if (! $this->driver instanceof VuFind\RecordDriver\EDS && ! $getthis->isOnlineResource($item_id)): ?>
          <a class="<?=$check ? 'checkRequest request-check ' : ''?>placehold" data-lightbox href="<?= $this->escapeHtmlAttr("/Record/$id/GetThis?item_id=$item_id") ?>" rel="nofollow">
            <?=$this->transEsc('Get this')?>
          </a>
        <?php endif; /** MSU END */ ?>
        <?php if ($holding['storageRetrievalRequestLink'] ?? false): ?>
          <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest request-check ' : ''?> placeStorageRetrievalRequest icon-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holding['storageRetrievalRequestLink']))?>">
            <?=$this->icon('place-storage-retrieval', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc($checkStorageRetrievalRequest ? 'storage_retrieval_request_check_text' : 'storage_retrieval_request_place_text')?></span>
          </a>
        <?php endif; ?>
        <?php if ($holding['ILLRequestLink'] ?? false): ?>
          <a class="<?=$checkILLRequest ? 'checkILLRequest request-check ' : ''?>placeILLRequest icon-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holding['ILLRequestLink']))?>">
            <?=$this->icon('place-ill-request', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc($checkILLRequest ? 'ill_request_check_text' : 'ill_request_place_text')?></span>
          </a>
        <?php endif; ?>
      <?php else: ?>
        <?php /* Begin Unavailable Items (Recalls) */ /** MSU */ ?>
          <?php /** MSU Code removed */ ?>
          <?php if (($holding['requests_placed'] ?? 0) > 0): ?>
            <span><?=$this->transEsc('Requests')?>: <?=$this->escapeHtml($holding['requests_placed'])?></span>
          <?php endif; ?>
          <?php /** MSU START */ ?>
          <?php if (! $this->driver instanceof VuFind\RecordDriver\EDS && ! $getthis->isOnlineResource($item_id)): ?>
            <a class="<?=$check ? 'checkRequest request-check ' : ''?>placehold" data-lightbox href="<?= $this->escapeHtmlAttr("/Record/$id/GetThis?item_id=$item_id") ?>" rel="nofollow">
              <?=$this->transEsc('Get this') ?>
            </a>
          <?php endif; /** MSU END */ ?>
          <?=$this->relais()->renderButtonIfActive($this->driver ?? null)?>
        <?php endif; ?>
        <?php if (isset($holding['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc('Item Notes')?>:</b>
            <ul>
              <?php foreach ($holding['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
        <?php if (!empty($holding['bound_with_records'])): ?>
          <?=
            $this->render(
                'RecordTab/holdingsils/boundwith.phtml',
                [
                  'boundWithRecords' => $holding['bound_with_records'],
                  'callNumber' => $holding['callnumber'],
                  'callNumberCount' => count($callNos),
                  'driver' => $driver,
                ]
            );
          ?>
        <?php endif; ?>
      <?php /* Embed item structured data: library, barcode, call number */ ?>
      <?php if ($holding['location'] ?? false): ?>
        <?=$this->schemaOrg()->getMeta('seller', $holding['location'])?>
      <?php endif; ?>
      <?php if ($holding['barcode'] ?? false): ?>
        <?=$this->schemaOrg()->getMeta('serialNumber', $holding['barcode'])?>
      <?php endif; ?>
      <?php if ($holding['callnumber'] ?? false): ?>
        <?=$this->schemaOrg()->getMeta('sku', $holding['callnumber'])?>
      <?php endif; ?>
      <?php /* Declare that the item is to be borrowed, not for sale */ ?>
      <?=$this->schemaOrg()->getLink('http://purl.org/goodrelations/v1#LeaseOut', 'businessFunction')?>
      <?=$this->schemaOrg()->getLink('#record', 'itemOffered')?>
    </td>
  </tr>
<?php endif; ?>
