<?php
$item_id = $this->getthis->item_id;
$id = $this->getthis->record->getUniqueId();
$callnum = $this->getthis->getCallNumber();
?>
<div>
    <p>
        <b>Request this Item:</b>
        You may check out the material from the
        <a data-lightbox-ignore href="<?= $this->escapeHtmlAttr("/Record/$id/MapThis?item_id=$item_id") ?>" rel="nofollow" target="_blank">
            appropriate Service Desk</a>
        using call number <?= $this->escapeHtml($callnum) ?>,
        during the Desk&#39;s open hours.
        <?php if ($this->getthis->isLibUseOnly()) {
            ?>However, this material cannot leave the building.<?php
        } ?>
    </p>
</div>
