<?php
$location = $this->getthis->getLocation();
$isCirc = stripos($location, 'circulation') !== false;
$url = $isCirc ? 'circ' : 'dmc';
$desk = $isCirc ? 'Circulation Desk' : 'Digital & Multimedia Center';
?>
<div>
    <p>
        <b>Self Service:</b>
        You may pick up the equipment from the <?= $desk ?>
        during the Desk's <a href='https://lib.msu.edu/hours/calendar/<?= $url ?>' target='_blank'>open hours</a>.
        Material is subject to availability.
    </p>
</div>
