<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Request this Item</legend>
        <label for="Da" width="100%">
            This item is only available for access and use in the Digital &amp; Multimedia
            Center on 4 West of the Main Library. If you have a particular use case or special
            need, contact the <a href='https://lib.msu.edu/collections/rovi/feedback/'>gaming coordinator</a>.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
