<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Request this Item</legend>
        <label for="Da" width="100%">
            Library Use Only materials are available for use during regular library
            <a href='http://www.law.msu.edu/library/hours.html'>hours</a>.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
