<?php
$item = $this->getthis->getItem();
?>
<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Self Service</legend>
        <label for="Da" width="100%">
            Please contact the Law Library Reference Desk at reference@law.msu.edu or
            (517) 432-6870 for information on how to access Rare and Archival materials.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
