<?php
$item = $this->getthis->getItem();
?>
<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Self Service</legend>
        <label for="Da" width="100%">
            You may check out the material from the
            <a href='https://www.law.msu.edu/library/hours.html'>Law Library Service Desk</a>
            using call number <?= $this->escapeHtml($item['callnumber']) ?> during the Desk open hours.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
