<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Self Service</legend>
        <label for="Da" width="100%">
            You may pick up the equipment from the <a href='https://www.lib.msu.edu/makerspace/'>MakeCentral's Service Desk</a>
            during the Desk's <a href='https://lib.msu.edu/general/library-hours-cal/hollander-makecentral-service-desk/'>open hours</a>.
            Material is subject to availability.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
