<?php
$item = $this->getthis->getItem();
$loc = $this->getthis->getLocation();
$title = $this->driver->getTitle();
$author = $this->driver->getPrimaryAuthor();
$bibnum = $this->driver->getSierraBN();
?>
<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Request Digital Lending</legend>
        <label for="Da" width="100%">
            Materials must be paged for in-building use. Please fill out
            <a href='https://codeprod.lib.msu.edu/forms/reqform.php?TITLE=<?= $this->escapeUrl($title) ?>&CALL=<?= $this->escapeUrl($item['callnumber']) ?>&AUTHOR=<?= $this->escapeUrl($author) ?>&LOC=<?= $this->escapeUrl($loc) ?>&BIBNUM=<?= $this->escapeUrl($bibnum) ?>'>this form</a>
            and we will contact you about your viewing options.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
