<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Request this Item</legend>
        <label for="Da" width="100%">
            This item is located in an off campus location and may be requested by emailing:
            <a href='mailto:remote@lib.msu.edu?subject=Requesting Microfilm from Remote Storage'>remote@lib.msu.edu</a>.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
