<?php
$item = $this->getthis->getItem();
?>
<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Self Service</legend>
        <label for="Da" width="100%">
            You may check out the material from the
            <a href='http://www.lib.msu.edu/contact/servicedesks/'>appropriate Reserve Service Desk</a>
            using call number <?= $this->escapeHtml($item['callnumber']) ?>
            during the Desk open hours.
            <?php if ($this->getthis->isLibUseOnly()) {
                ?>However, this material cannot leave the building.<?php
            } ?>
        </label>
    </fieldset>
</td></tr>
</table>
</div>
