<?php
$item = $this->getthis->getItem();
$callnum = $this->getthis->getCallNumber();
?>
<div>
    <p>
        <b>Self Service:</b>
        You may check out the material from the
        <a href='https://lib.msu.edu/reserves/service-desks' target='_blank'>appropriate Reserve Service Desk</a>
        using call number <?= $this->escapeHtml($callnum) ?>
        during the Desk open hours.
        <?php if ($this->getthis->isLibUseOnly()) {
            ?>However, this material cannot leave the building.<?php
        } ?>
    </p>
</div>
