<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Self Service</legend>
        <label for="Da" width="100%">
            This item has been placed on Reserves. You may check the item out at the Circulation
            desk. This is a first come, first served service. Late fees are $1.00/hour. Before
            coming to the library, please <a href='https://lib.msu.edu/hours/'>check our open hours</a>.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
