<?php
$item = $this->getthis->getItem();
$loc = $this->getthis->getLocation();
$title = $this->driver->getTitle();
$author = $this->driver->getPrimaryAuthor();
$bibnum = $this->driver->getSierraBN();
?>
<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Turfgrass Information Center</legend>
        <label for="Da" width="100%">
            The Turfgrass Information Center is temporarily closed. All material must be
            requested for viewing in the Special Collections Reading Room, by appointment
            only.<br /><br />
            Please note: You must make an appointment to view this item. Item requests without
            corresponding Reading Room appointments will be cancelled.<br />
            <ul>
                <li><a href='https://codeprod.lib.msu.edu/forms/reqform.php?TITLE=<?= $this->escapeUrl($title) ?>&CALL=<?= $this->escapeUrl($item['callnumber']) ?>&AUTHOR=<?= $this->escapeUrl($author) ?>&LOC=<?= $this->escapeUrl($loc) ?>&BIBNUM=<?= $this->escapeUrl($bibnum) ?>'>Request the item</a></li>
                <li><a href='https://bookings.lib.msu.edu/reserve/spc'>Make an appointment</a></li>
            </ul>
        </label>
    </fieldset>
</td></tr>
</table>
</div>
