<?php
$item = $this->getthis->getItem();
?>
<div class='advSearchLimits'>
<table id="fmBox" border="0">
<tr><td>
    <fieldset id="fbox">
        <legend id="fheader">Collections Access</legend>
        <label for="Da" width="100%">
            You may review the material at the University Archives &amp; Historical Collections in
            <a href='https://goo.gl/maps/cJzgFWghhRRAcFU5A'>Conrad Hall</a> using call number
            <?= $this->escapeHtml($item['callnumber']) ?> during the
            <a href='https://lib.msu.edu/branches/ua/Research/ReadingRoom/'>Reading Room</a>&#39;s open hours.
            <br /><br />
            Please contact the University Archives &amp; Historical Collections at
            <a href='mailto:archives@msu.edu'>archives@msu.edu</a> or visit
            <a href='https://lib.msu.edu/branches/ua/'>University Archives</a> for information on how
            to access these materials.
        </label>
    </fieldset>
</td></tr>
</table>
</div>
