<?php
use Catalog\GetThis\GetThisLoader;

$selected = '';
$record = $this->record($this->driver);
foreach ($this->statusItems as $item) {
  if ($selected == '') {
    $selected = $item;
  } elseif ($selected['status'] != 'Available') {
    if ($item['status'] == 'Available' || ($selected['status'] != 'Restricted' && $item['status'] == 'Restricted')) {
      $selected = $item;
    }
  }
}
if ($selected != '') {
  $status = $record->getStatus($selected);
  $location = $selected['location'];
  $callnumber = $selected['callnumber'];
  $callNumPrefix = !empty($selected['callnumber_prefix']) ? $selected['callnumber_prefix'] . ' ' : '';
}
?>
<?php if ($selected != ''): ?>
  <div>
    <strong>Holdings:</strong>
    <span class="fullAvailability">
      <?php if ($selected['use_unknown_message'] ?? false): ?>
        <strong class="text-muted"><?=$this->transEsc('status_unknown_message')?></strong>
      <?php elseif ($status == 'Library Use Only'): ?>
        <strong class="text-warning"><?=$this->transEsc($status)?></strong>
      <?php elseif ((int)$selected['availability'] === \VuFind\ILS\Logic\ItemStatus::STATUS_UNAVAILABLE): ?>
        <strong class="text-danger"><?=$this->transEsc($status)?></strong>
      <?php elseif ((int)$selected['availability'] === \VuFind\ILS\Logic\ItemStatus::STATUS_UNCERTAIN): ?>
        <strong class="text-warning"><?=$this->transEsc($status)?></strong>
      <?php else: ?>
        <strong class="text-success"><?=$this->transEsc($status)?></strong>
      <?php endif; ?>
    </span>
    <?php if ($location != ''): ?>
      at
      <span class="fullLocation">
        <?php $locationText = $this->transEsc($location); ?>
        <?php if (count($this->statusItems) > 1): ?>
          <?=$locationText?>&nbsp;&nbsp;<a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($selected['id']))?>/Holdings#tabnav" target="_blank">see more</a>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
      </span>
    <?php endif; ?>
    <?php $id = $selected['id']; ?>
    <?php $item_id = $selected['item_id']; ?>
    <?php $getthis = new GetThisLoader($record, $this->statusItems, $item_id); ?>
    <?php if ($getthis && ! str_starts_with($id, 'hlm.') && ! $getthis->isOnlineResource()): ?>
      <a class="pl-1 placehold" data-lightbox href="<?= $this->escapeHtmlAttr("/Record/$id/GetThis?item_id=$item_id") ?>" rel="nofollow">
        <?=$this->transEsc('Get this')?>
      </a>
    <?php endif; ?>
  </div>
  <?php if ($callnumber != ''): ?>
    <div>
      <strong>Call Number:</strong>
      <span class="fullCallnumber">
          <?=$this->escapeHtml($callNumPrefix)?><?=$this->escapeHtml($callnumber)?>
      </span>
    </div>
  <?php endif; ?>
  <?php if (!empty($selected)): ?>
    <?= $this->locationNotices($selected) ?>
  <?php endif; ?>
<?php else: ?>
  <span class="fullAvailability"><strong class="text-danger">Unavailable</strong></span>
<?php endif; ?>
