<?php
$selected = '';
foreach ($this->statusItems as $item) {
  if ($selected == '') {
    $selected = $item;
  } else if ($selected['status'] != 'Available') {
    if ($item['status'] == 'Available' || ($selected['status'] != 'Restricted' && $item['status'] == 'Restricted'))
      $selected = $item;
  }
}
if ($selected != '') {
  $status = $selected['status'];
  $location = $selected['location'];
  $callnumber = $selected['callnumber'];
  $callNumPrefix = !empty($selected['callnumber_prefix']) ? $selected['callnumber_prefix'] . ' ' : '';
  if (in_array($status, array('Aged to lost', 'Claimed returned', 'Declared lost', 'In process (non-requestable)',
      'Long missing', 'Lost and paid', 'Missing', 'On order', 'Order closed', 'Unknown', 'Withdrawn')))
    $status = 'Unavailable';
  else if (in_array($status, array('Awaiting pickup', 'Awaiting delivery', 'In transit', 'Paged', 'Checked out')))
    $status = 'Checked Out';
  else if ($status == 'Restricted')
    $status = 'Library Use Only';
  else if (!in_array($status, array('Available', 'Unavailable')))
    $status = 'Unknown status';
}
?>
<?php if ($selected != ''): ?>
  <div>
    <strong>Holdings:</strong>
    <span class="fullAvailability">
      <?php if ($selected['availability']): ?>
        <strong class="text-success"><?=($selected['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc("Available")?></strong>
      <?php elseif ($status == 'Library Use Only'): ?>
        <strong class="text-warning"><?=$this->transEsc($status)?></strong>
      <?php else: ?>
        <strong class="text-danger"><?=$this->transEsc($status)?></strong>
      <?php endif; ?>
    </span>
    <?php if ($location != ''): ?>
      at
      <span class="fullLocation">
        <?php $locationText = $this->transEsc($location); ?>
        <?php if (count($this->statusItems) > 1): ?>
          <?=$locationText?>&nbsp;&nbsp;<a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($selected['id']))?>/Holdings#tabnav" target="_blank">see more</a>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
      </span>
    <?php endif; ?>
  </div>
  <?php if ($callnumber != ''): ?>
    <div>
      <strong>Call Number:</strong>
      <span class="fullCallnumber">
          <?=$this->escapeHtml($callNumPrefix)?><?=$this->escapeHtml($callnumber)?>
      </span>
    </div>
  <?php endif; ?>
<?php else: ?>
  <span class="fullAvailability"><strong class="text-danger">Unavailable</strong></span>
<?php endif; ?>
