---
# Access link labels. Label is appended to link if provided regexes match.
#   label: The string to add to the link desc
#   desc : Regex must match against the 'desc' field for label to match; or null to ignore
#   url  : Regex must match against the 'url' field for label to match; or null to ignore
labels:
  # Example
  # - label: "EBSCO"
  #   desc: null
  #   url: "#https://search\\.ebscohost\\.com/#"
  - label: "EBSCO"
    url: "#https?://search\\.ebscohost\\.com/#"
  - label: "EBSCO"
    url: "#https?://www\\.net[Ll]ibrary\\.com/#"
  - label: "Alexander Street"
    url: "#https?://www\\.aspresolver\\.com/#"
  - label: "Ebook Central @ Proquest"
    url: "#https://ebookcentral\\.proquest\\.com/#"
  - label: "Hein Online"
    url: "#https://(www\\.)?heinonline\\.org/#"
  - label: "Springer Link"
    url: "#https://link\\.springer\\.com/#"
  - label: "University of North Texas Ditigal Library"
    url: "#https://digital\\.library\\.unt\\.edu/#"
  - label: "National Center for Biotechnology Information @ National Library of Medicine"
    url: "#https://www\\.ncbi\\.nlm\\.nih\\.gov/#"
  - label: "Digital Object Identifier Permalink"
    url: "#https?://((www|dx)\\.)?doi\\.org/#"
  - label: "FRASER @ Federal Reserve Bank of St. Louis"
    url: "#https://fraser\\.stlouisfed\\.org/#"
  - label: "ScienceDirect"
    url: "#https://www\\.sciencedirect\\.com/#"
  - label: "Brill"
    url: "#https://brill\\.com/#"
  - label: "Brill"
    url: "#https://([a-z0-9.-]*\\.)?brillonline\\.com/#"
  - label: "Firenze University Press"
    url: "#https://www\\.fupress\\.com/#"
  - label: "Handle.Net Permalink"
    url: "#https://hdl\\.handle\\.net/#"
  - label: "Wiley Online Library"
    url: "#https://([a-z0-9.-]*\\.)?onlinelibrary\\.wiley\\.com/#"
  - label: "University of California Press E-Books Collection"
    url: "#https://publishing\\.cdlib\\.org/ucpressebooks/#"
  - label: "Open Access Publishing in European Networks"
    url: "#https://library\\.oapen\\.org/#"
  - label: "Society for Industrial and Applied Mathematics"
    url: "#https://epubs\\.siam\\.org/#"
  - label: "Taylor & Francis eBooks"
    url: "#https://www\\.taylorfrancis\\.com/#"
  - label: "IEEE Xplore"
    url: "#https://ieeexplore\\.ieee\\.org/#"
  - label: "JSTOR"
    url: "#https://www\\.jstor\\.org/#"
  - label: "Frontiers"
    url: "#https://journal\\.frontiersin\\.org/#"
  - label: "International Monetary Fund eLibrary"
    url: "#https://www\\.elibrary\\.imf\\.org/#"
  - label: "Adam Matthew Digital"
    url: "#https?://([a-z0-9.-]*\\.)?amdigital\\.co\\.uk/#"
  - label: "World Bank eLibrary"
    url: "#https://elibrary\\.worldbank\\.org/#"
  - label: "ClinicalKey"
    url: "#https://www\\.clinicalkey\\.com/#"
  - label: "American Chemical Society Publications"
    url: "#https://pubs\\.acs\\.org/#"
  - label: "R2 Digital Library"
    url: "#https://www\\.r2library\\.com/#"
  - label: "Open Book Publishers"
    url: "#https://www\\.openbookpublishers\\.com/#"
  - label: "Open Textbook Library @ University of Minnesota"
    url: "#https://open.umn.edu/opentextbooks/#"
  - label: "Directory of Open Access Books"
    url: "#https://directory\\.doabooks\\.org/#"
  - label: "Emerald Insight"
    url: "#https://www\\.emerald\\.com/insight/#"
  - label: "Gale"
    url: "#https://([a-z0-9.-]*\\.)?gale(group)?\\.com/#"
  - label: "De Gruyter"
    url: "#https://www\\.degruyter\\.com/#"
  - label: "Project MUSE @ John Hopkins University"
    url: "#https://muse\\.jhu\\.edu/#"
  - label: "Digital Commons @ Utah State University"
    url: "#https://digitalcommons\\.usu\\.edu/#"
  - label: "ProQuest"
    url: "#https://((www|gateway|search)\\.)?proquest\\.com/#"
  - label: "ProQuest"
    url: "#https?://proquest\\.umi\\.com/#"
  - label: "ProQuest Congressional"
    url: "#https?://congressional\\.proquest\\.com/#"
  - label: "Knovel"
    url: "#https://app\\.knovel\\.com/#"
  - label: "Oxford Academic"
    url: "#https://academic\\.oup\\.com/#"
  - label: "Oxford Academic"
    url: "#https://oxford\\.universitypressscholarship\\.com/#"
  - label: "Oxford Academic"
    url: "#https://www\\.oxfordclinicalpsych\\.com/#"
  - label: "Astrophysics Data System"
    url: "#https?://ads\\.harvard\\.edu/books/#"
  - label: "Cataloging @ Library of Congress"
    url: "#https?://catdir\\.loc\\.gov/catdir/#"
  - label: "RERO doc Ditial Library"
    url: "#https?://doc\\.rero\\.ch/record/#"
  - label: "Center for Research Libraries Digital Delivery System"
    url: "#https?://dds(next)?\\.crl\\.edu/#"
  - label: "NewsBank"
    url: "#https?://([a-z0-9.-]*\\.)?newsbank\\.com/#"
  - label: "Law Library Microform Consortium"
    url: "#https?://llmc\\.com/#"
  - label: "Law Library Microform Consortium"
    url: "#https?://www\\.llmcdigital\\.org/#"
  - label: "Naxos Music Library"
    url: "#https?://michiganstate\\.naxosmusiclibrary\\.com/#"
  - label: "The HistoryMakers"
    url: "#https://da\\.thehistorymakers\\.org/#"
  - label: "Cambridge Core"
    url: "#https?://www\\.cambridge\\.org/#"
  - label: "medici.tv EDU"
    url: "#https://edu\\.medici\\.tv/#"
  - label: "Encyclopedia of Social Work"
    url: "#https?://socialwork\\.oxfordre\\.com/#"
  - label: "West Academic"
    url: "#https://subscription\\.westacademic\\.com/#"
  - label: "Gallica @ Bibliothèque nationale de France"
    url: "#https?://gallica\\.bnf\\.fr/#"
  - label: "University of Michigan Permalink"
    url: "#https?://name\\.umdl\\.umich\\.edu/#"
  - label: "The Online Books Page @ University of Pennsylvania"
    url: "#https?://onlinebooks\\.library\\.upenn\\.edu/#"
  - label: "U.S. Government Publishing Office Permalink"
    url: "#https?://permanent\\.access\\.gpo\\.gov/#"
  - label: "Federal Depository Library Program Persistant URL"
    url: "#https?://purl\\.access\\.gpo\\.gov/#"
  - label: "Federal Depository Library Program Persistant URL"
    url: "#https?://purl\\.fdlp\\.gov/#"
  - label: "Indiana University Libraries Persistant URL"
    url: "#https?://purl\\.dlib\\.indiana\\.edu/#"
  - label: "University of Minnesota Persistant URL"
    url: "#https?://purl\\.umn\\.edu/#"
  - label: "Idaho Office of the Administrative Rules Coordinator"
    url: "#https://adminrules\\.idaho\\.gov/#"
  - label: "Internet Archive"
    url: "#https://(www\\.)?archive\\.org/#"
  - label: "Biblioteca Digital @ Real Jardín Botánico de Madrid"
    url: "#https://bibdigital\\.rjb\\.csic\\.es/#"
  - label: "OpenEdition"
    url: "#https://(books\\.)?openedition.org/#"
  - label: "TU Delft OPEN Books"
    url: "#https://books\\.open\\.tudelft\\.nl/#"
  - label: "Scientific Electronic Library Online"
    url: "#https://books\\.scielo\\.org/#"
  - label: "Bologna University Press"
    url: "#https://buponline\\.com/#"
  - label: "Centre for Agriculture and Bioscience International Digital Library"
    url: "#https://(www\\.)?cabi(digitallibrary)?\\.org/#"
  - label: "Centro de Estudios Montañeses"
    url: "#https://centrodeestudiosmontaneses\\.com/#"
  - label: "Digital Collections @ Cornell University Library"
    url: "#https://digital\\.library\\.cornell\\.edu/#"
  - label: "Massachusetts Institute of Technology Press"
    url: "#https://(direct|mitpress)\\.mit\\.edu/#"
  - label: "Digital Repository @ Michigan State University"
    url: "#https://d\\.lib\\.msu\\.edu/#"
  - label: "ePublishing @ EKT National Documentation Centre, Greece"
    url: "#https://(ebooks\\.)?epublishing\\.ekt\\.gr/#"
  - label: "European Commission"
    url: "#https://ec\\.europa\\.eu/#"
  - label: "Universitaria Agustiniana"
    url: "#https://editorial\\.uniagustiniana\\.edu\\.co/#"
  - label: "Geological Survey of Denmark and Greenland"
    url: "#https://eng\\.geus\\.dk/#"
  - label: "European Network for Rural Development"
    url: "#https://enrd\\.ec\\.europa\\.eu/#"
  - label: "UNESCO"
    url: "#https://en\\.unesco\\.org/#"
  - label: "EUR-Lex"
    url: "#https://eur-lex\\.europa\\.eu/#"
  - label: "Academic Reference @ China National Knowledge Infrastructure"
    url: "#https?://ar\\.cnki\\.net/#"
  - label: "China Data Insights @ China National Knowledge Infrastructure"
    url: "#https?://cdi\\.cnki\\.net/#"
  - label: "Reference Works @ China National Knowledge Infrastructure"
    url: "#https?://gongjushu\\.oversea\\.cnki\\.net/#"
  - label: "Yearbooks Database @ China National Knowledge Infrastructure"
    url: "#https?://tongji\\.oversea\\.cnki\\.net//#"
  - label: "China National Knowledge Infrastructure"
    url: "#https?://oversea\\.cnki\\.net/#"
  - label: "China National Knowledge Infrastructure"
    url: "##https?://gb\\.global\\.cnki\\.net/#"
  - label: "Bibliothèque et Archives nationales du Québec"
    url: "#https?://collections\\.banq\\.qc\\.ca/#"
  - label: "Hindawi"
    url: "#https?://downloads\\.hindawi\\.com/#"
  - label: "SAGE Knowledge"
    url: "#https?://(knowledge|sk)\\.sagepub\\.com/#"
  - label: "SAGE Research Methods"
    url: "#https?://methods\\.sagepub\\.com/#"
  - label: "Nationallizenzen @ Deutsche Forschungsgemeinschaft"
    url: "#https?://nl\\.sub\\.uni-goettingen\\.de/#"
  - label: "Salem Press"
    url: "#https?://online\\.salempress\\.com/#"
  - label: "Georg-August-Universität Göttingen Permanent URL"
    url: "#https?://resolver\\.sub\\.uni-goettingen\\.de/#"
  - label: "McGraw Hill Medical"
    url: "#https://([a-z0-9.-]*\\.)?mhmedical\\.com/#"
  - label: "Nexis Uni @ LexisNexis"
    url: "#https://advance\\.lexis\\.com/#"
  - label: "American Institute of Physics Publishing"
    url: "#https://aip\\.scitation\\.org/#"
  - label: "Wiley Digital Archives"
    url: "#https://app\\.wileydigitalarchives\\.com/#"
  - label: "American Phytopathological Society Publications"
    url: "#https://apsjournals\\.apsnet\\.org/#"
  - label: "Datapages, Inc Archives @ American Association of Petroleum Geologists"
    url: "#https://archives\\.datapages\\.com/#"
  - label: "American Society of Mechanical Engineers Digital Collection"
    url: "#https://asmedigitalcollection.asme.org/#"
  - label: "BioOne Complete"
    url: "#https://bioone\\.org/#"
  - label: "Canada Commons"
    url: "#https://canadacommons\\.ca/#"
  - label: "O’Reilly"
    url: "#https://cdn\\.oreillystatic\\.com/#"
  - label: "O’Reilly"
    url: "#https://(www\\.)?oreilly\\.com/#"
  - label: "Library of Congress"
    url: "#https://([a-z0-9.-]*\\.)?loc\\.gov/#"
  - label: "LWW Health Library"
    url: "#https://([a-z0-9.-]*\\.)?lwwhealthlibrary\\.com/#"
  - label: "Digital Repository @ American Museum of Natural History Research Library"
    url: "#https://digitallibrary\\.amnh\\.org/#"
  - label: "Digital Collections @ University of Pittsburgh Library System"
    url: "#https://digital\\.library\\.pitt\\.edu/#"
  - label: "Institution of Engineering and Technology Digital Library"
    url: "#https://digital-library\\.theiet\\.org/#"
  - label: "Association for Computing Machinery Digital Library"
    url: "#https://dl\\.acm\\.org/#"
  - label: "Czech Digital Mathematics Library"
    url: "#https://dml\\.cz/#"
  - label: "Docuseek"
    url: "#https://docuseek2\\.com/#"
  - label: "DSM Library @ Psychiatry Online"
    url: "#https://dsm\\.psychiatryonline\\.org/#"
  - label: "Psychiatry Online"
    url: "#https://psychiatryonline\\.org/#"
  - label: "IOS Press Ebooks"
    url: "#https://ebooks\\.iospress\\.nl/#"
  - label: "Ditigal Theatre+"
    url: "#https://edu\\.digitaltheatreplus\\.com/#"
  - label: "American Society of Agricultural and Biological Engineers"
    url: "#https://elibrary\\.asabe\\.org/#"
  - label: "European Mathematical Press"
    url: "#https://ems\\.press/#"
  - label: "Films On Demand @ Infobase"
    url: "#https://fod\\.infobase\\.com/#"
  - label: "Feature Films for Education @ Infobase"
    url: "#https://ffusa\\.infobase\\.com/#"
  - label: "GeoScienceWorld"
    url: "#https://(pubs\\.)?geoscienceworld\\.org/#"
  - label: "Dow Jones Factivia"
    url: "#https://global\\.factiva\\.com/#"
  - label: "East View Global Press Archive"
    url: "#https://gpa\\.eastview\\.com/#"
  - label: "IOPscience @ Institute of Physics"
    url: "#https://iopscience\\.iop\\.org/#"
  - label: "Welsh Journals @ The National Library of Wales"
    url: "#https://journals\\.library\\.wales/#"
  - label: "jove"
    url: "#https://www\\.jove\\.com/#"
  - label: "MedOne ComSci @ Thieme"
    url: "#https://medone-comsci\\.thieme\\.com/#"
  - label: "MedOne Education @ Thieme"
    url: "#https://medone-education\\.thieme\\.com/#"
  - label: "MedOne Radiology @ Thieme"
    url: "#https://medone-radiology\\.thieme\\.com/#"
  - label: "McGraw-Hill eBookLibrary"
    url: "#https://mhebooklibrary\\.com/#"
  - label: "kanopy"
    url: "#https://msu\\.kanopy\\.com/#"
  - label: "TDS Health"
    url: "#https://online\\.statref\\.com/#"
  - label: "Open Research Library"
    url: "#https://openresearchlibrary\\.org/#"
  - label: "OpenStax"
    url: "#https://openstax\\.org/#"
  - label: "Publications Office of the European Union"
    url: "#https://op\\.europa\\.eu/#"
  - label: "Ovid"
    url: "#https://ovidsp\\.ovid\\.com/#"
  - label: "Swank Motion Pictures"
    url: "#https://permalinks\\.swankmp\\.net/#"
  - label: "perspectivia.net"
    url: "#https://perspectivia\\.net/#"
  - label: "Wolters Kluwer Resource Link"
    url: "#https://prod\\.resource\\.cch\\.com/#"
  - label: "Project Euclid"
    url: "#https://projecteuclid\\.org/#"
  - label: "American Psychological Association PsycNet"
    url: "#https://psycnet\\.apa\\.org/#"
  - label: "American Academy of Pediatrics Books"
    url: "#https://publications\\.aap\\.org/aapbooks/#"
  - label: "eBooks @ ABC-CLIO"
    url: "#https://publisher\\.abc-clio\\.com/#"
  - label: "Royal Society of Chemistry"
    url: "#https://pubs\\.rsc\\.org/#"
  - label: "uO Research @ University of Ottawa"
    url: "#https://ruor\\.uottawa\\.ca/#"
  - label: "Universitätsbibliothek Frankfurt am Main"
    url: "#https://sammlungen\\.ub\\.uni-frankfurt\\.de/#"
  - label: "Sciendo"
    url: "#https://sciendo\\.com/#"
  - label: "IGI Global"
    url: "#https://services\\.igi-global\\.com/#"
  - label: "Multidisciplinary Digital Publishing Institute"
    url: "#https://(www\\.)?mdpi\\.com/#"
  - label: "National Academies Press"
    url: "#https://www\\.nap\\.edu/#"
  - label: "National Film Board of Canada"
    url: "#https://www\\.(nfb|onf)\\.ca/#"
  - label: "Oxford Bibliographies"
    url: "#https://www\\.oxfordbibliographies\\.com/#"
  - label: "Oxford Reference"
    url: "#https://www\\.oxfordreference\\.com/#"
  - label: "Peter Lang"
    url: "#https://www\\.peterlang\\.com/#"
  - label: "Society of Photographic Instrumentation Engineers Digital Library"
    url: "#https://www\\.spiedigitallibrary\\.org/#"
  - label: "Society of Photographic Instrumentation Engineers"
    url: "#https://spie\\.org/#"
  - label: "Wageningen Academic Publishers"
    url: "#https://www\\.wageningenacademic\\.com/#"
  - label: "Ambrose Video Publishing"
    url: "#https?://videos\\.ambrosevideo\\.com/#"
  - label: "American Mathematical Society"
    url: "#https?://www\\.ams\\.org/#"
  - label: "British History Online"
    url: "#https://www\\.british-history\\.ac\\.uk/#"
  - label: "Botanicus"
    url: "#https?://www\\.botanicus\\.org/#"
  - label: "University of Michigan"
    url: "#https?://www\\.hti\\.umich\\.edu/#"
  - label: "Michigan State University Libraries"
    url: "#https?://(www\\.)?lib\\.msu\\.edu/#"
  - label: "U.S. Department of Energy Office of Scientific and Technical Information"
    url: "#https?://www\\.osti\\.gov/#"
  - label: "A&AePortal"
    url: "#https://www\\.aaeportal\\.com/#"
  - label: "McGraw-Hill AccessEngineering"
    url: "#https://www\\.accessengineeringlibrary\\.com/#"
  - label: "Columbia International Affairs Online"
    url: "#https://www\\.ciaonet\\.org/#"
  - label: "Elgar Online"
    url: "#https://www\\.elgaronline\\.com/#"
  - label: "University of Hawaii Open Access"
    url: "#https://www\\.hawaiiopen\\.org/#"
  - label: "International Atomic Energy Agency"
    url: "#https://www\\.iaea\\.org/#"
  - label: "Loeb Classical Library"
    url: "#https://www\\.loebclassics\\.com/#"
  - label: "Lyell Collection"
    url: "#https://(www|sp)\\.lyellcollection\\.org/#"
  - label: "Richard K. Miller & Associates"
    url: "#https://www\\.rkma\\.com/#"
  - label: "Routledge Handbooks Online"
    url: "#https://www\\.routledgehandbooks\\.com/#"
  - label: "Southern Poverty Law Center"
    url: "#https://www\\.splcenter\\.org/#"
  - label: "Accessible Archives"
    url: "#https?://www\\.accessible\\.com/#"
  - label: "LearnTechLib"
    url: "#https?://www\\.learntechlib\\.org/#"
  - label: "Morgan & Claypool"
    url: "#https?://www\\.morganclaypool\\.com/#"
  - label: "Begell House"
    url: "#https://www\\.begellhouse\\.com/#"
  - label: "British Small Animal Vetrinary Association Library"
    url: "#https://www\\.bsavalibrary\\.com/#"
  - label: "Human Kinetics Library"
    url: "#https://www\\.humankineticslibrary\\.com/#"
  - label: "astrophysics data system @ Harvard"
    url: "#https://ui\\.adsabs\\.harvard\\.edu/#"
  - label: "ASTM International"
    url: "#https://www\\.astm\\.org/#"
  - label: "Chronicle of Higher Education"
    url: "#https://www\\.chronicle\\.com/#"
  - label: "GovInfo @ U.S. Government Publishing Office"
    url: "#https://www\\.govinfo\\.gov/#"
  - label: "PressReader"
    url: "#https://www\\.pressreader\\.com/#"
  - label: "European Central Bank"
    url: "#https://www\\.ecb\\.europa\\.eu/#"
  - label: "Economic Commission for Latin America and the Caribbean"
    url: "#https://repositorio\\.cepal\\.org/#"
  - label: "Asian Development Bank"
    url: "#https://www\\.adb\\.org/#"
  - label: "Numdam"
    url: "#https?://www\\.numdam\\.org/#"
  - label: "John Benjamins e-Platform"
    url: "#https://www\\.jbe-platform\\.com/#"
