<?php
$loc = $this->getthis->getLocation();
$title_full = $this->driver->getRawData()['title_full'];
$callnum = $this->driver->getCallNumber();
?>
<html>
<body>
<p>
    This is your confirmation for requesting retrieval of the following material.
    Once the material is ready, you will be contacted with futher instructions.
</p>
<p>
    <i>Your Identity</i><br/>
    -----<br/>
    Name: <?= $this->userrow->firstname ?> <?= $this->userrow->lastname ?><br />
    Account: <?= $this->userrow->username ?><br />
</p>
<p>
    <i>Material to be Retrieved</i><br />
    -----<br />
    Title: <?= $title_full ?><br />
    Call Number: <?= $callnum ?><br />
    Retrieval From: <?= $loc ?><br />
</p>
</body>
</html>
