#!/bin/bash

rm -r "${VUFIND_CACHE_DIR:?}"/*

# Re-initialize dirs
install -d -o 33 -g 33 \
         "${VUFIND_CACHE_DIR}/covers" \
         "${VUFIND_CACHE_DIR}/objects" \
         "${VUFIND_CACHE_DIR}/yamls" \
         "${VUFIND_CACHE_DIR}/searchspecs"
install -d -o 1000 -g 1000 \
        "${VUFIND_CACHE_DIR}/cli"
chmod g+sw "${VUFIND_CACHE_DIR}/cli" "${VUFIND_CACHE_DIR}/covers"
chmod g+s "${VUFIND_CACHE_DIR}/objects" "${VUFIND_CACHE_DIR}/yamls"
