#!/bin/bash

rm -r "${VUFIND_CACHE_DIR}"/*

# Re-initialize cli and covers cache dir
mkdir -p ${VUFIND_CACHE_DIR}/cli ${VUFIND_CACHE_DIR}/covers
chown 33:33 ${VUFIND_CACHE_DIR}/cli ${VUFIND_CACHE_DIR}/covers
chmod g+sw ${VUFIND_CACHE_DIR}/cli ${VUFIND_CACHE_DIR}/covers
