#!/bin/bash

# Fail if any of these steps fail
set -e

cd /usr/local/vufind
cp module/Catalog/tests/vufind_phpunit.xml module/VuFind/tests/phpunit.xml || true
XDEBUG_MODE=coverage vendor/bin/phing phpunitfaster -D "phpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/ --coverage-text --colors=never"
