#!/bin/bash

# Fail if any of these steps fail
set -e

cd /usr/local/vufind
XDEBUG_MODE=coverage vendor/bin/phpunit -c module/Catalog/tests/phpunit.xml /usr/local/vufind/module/Catalog/tests/unit-tests/ --coverage-cobertura reports/coverage.xml > /dev/null 2>&1
cat reports/coverage.xml
