#!/bin/bash

# Fail if any of these steps fail
set -e

cd /usr/local/vufind
vendor/bin/phpunit -c module/Catalog/tests/phpunit.xml /usr/local/vufind/module/Catalog/tests/unit-tests/ --log-junit reports/report.xml > /dev/null 2>&1
cat reports/report.xml
