<div class="search-home-facets">

    <div class="home-facet">
      <h2>Browse Alphabetically</h2>
      <div class="home-facet-container">

          <?php $alphaBrowseTypes = $this->config()->get('config')->AlphaBrowse_Types; ?>
          <?=$this->context($this)->renderInContext('alphabrowse/home.phtml', ['alphaBrowseTypes' => $alphaBrowseTypes])?>

      </div>
    </div>
    <div class="home-facet home-reserves">
      <h2>Course Reserves</h2>
      <div class="home-facet-container">
  <!--    <p><?=$this->transEsc('Search for items on reserve:')?></p> -->
          <form class="form-inline" method="get" name="reservesSearchForm" action="Search/Reserves">
            <label for="reservesSearchForm_lookfor"><?=$this->transEsc("Your search terms")?></label>
            <input id="reservesSearchForm_lookfor" placeholder="Search terms" type="text" name="lookfor" size="40" value="" <?=$this->searchOptions('SolrReserves')->autocompleteEnabled() ? ' class="form-control autocomplete searcher:SolrReserves type:Reserves"' : ''?> />
            <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr("Find")?>"/>
          </form>
      </div>
    </div>
        <div class="home-facet home-askalib">
      <div class="home-facet-container text-center">
<a href="https://lib.msu.edu/contact/askalib">
            <p class="need-help">Need help getting started?</p>
            
            <img class="ask-icon d-none d-lg-block" alt="" role="presentation" aria-hidden="true" src="/themes/msul/images/Icons_AskALib_Default.svg">
            <br>
            <p class="askalibrarian">Ask a Librarian</p>
      </a>
      </div>
    </div>
</div>
