<div class="search-home-facets">

    <div class="home-facet">
      <h2>Browse Alphabetically</h2>
      <div class="home-facet-container">
        <?php $alphaBrowseTypes = $this->config()->get('config')->AlphaBrowse_Types; ?>
        <form class="form-inline" method="get" action="<?=$this->url('alphabrowse-home')?>" name="alphaBrowseForm" id="alphaBrowseForm">
          <label for="alphaBrowseForm_source"><?=$this->transEsc('Browse Alphabetically') ?></label>
          <select id="alphaBrowseForm_source" name="source" class="form-control">
            <?php foreach ($alphaBrowseTypes as $key => $item): ?>
              <option value="<?=$this->escapeHtmlAttr($key) ?>"<?php if ($this->source == $key): ?> selected="selected"<?php endif; ?>><?=$this->transEsc($item) ?></option>
            <?php endforeach; ?>
          </select>
          <label for="alphaBrowseForm_from"><?=$this->transEsc('starting from') ?></label>
          <input type="text" name="from" id="alphaBrowseForm_from" value="<?=$this->escapeHtmlAttr($this->from) ?>" class="form-control"/>
          <input class="btn btn-primary" type="submit" value="<?=$this->transEscAttr('Browse') ?>"/>
        </form>
      </div>
    </div>
    <div class="home-facet home-reserves">
      <h2>Course Reserves</h2>
      <div class="home-facet-container">
          <form class="form-inline" method="get" name="reservesSearchForm" action="Search/Reserves">
            <label class="mb-2" for="reservesSearchForm_lookfor">Search by <strong>Instructor</strong> or by <strong>Course</strong></label>
            <input id="reservesSearchForm_lookfor" placeholder="Search terms" type="text" name="lookfor" size="40" value="" <?=$this->searchOptions('SolrReserves')->autocompleteEnabled() ? ' class="form-control autocomplete searcher:SolrReserves type:Reserves"' : ''?> >
            <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr("Find")?>">
            <p><small>Course codes must be entered with a space between the course and code (e.g.&nbsp;acc&nbsp;341)</small></p>
          </form>
      </div>
    </div>
        <div class="home-facet home-askalib">
      <div class="home-facet-container text-center">
<a href="https://lib.msu.edu/contact/askalib">
            <p class="need-help">Need help getting started?</p>
            
            <img class="ask-icon d-none d-lg-block" alt="" role="presentation" aria-hidden="true" src="/themes/msul/images/Icons_AskALib_Default.svg">
            <br>
            <p class="askalibrarian">Ask a Librarian</p>
      </a>
      </div>
    </div>
</div>
