#!/bin/sh

runhelp() {
    echo ""
    echo "Purpose: Setup SSH access to all the deploy servers"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_A: The first host in the cluster"
    echo "  - DEPLOY_HOST_B: The second host in the cluster"
    echo "  - DEPLOY_HOST_C: The third host in the cluster"
    echo "  - ENCODED_PRIVATE_KEY: Private SSH key that has been base64 encoded"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If any required variables are not set"
    echo "  - The STACK_NAME job artifact was not properly passed to the job"
    echo ""
}

if [ -n "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
    runhelp
    exit 0
fi

beforescript() {
    # Check for STACK_NAME
    test -n "${STACK_NAME}"

    # Before script before SSH template
    if [ -z "$SERVER" ] || [ -z "$ENCODED_PRIVATE_KEY" ] ; then
       echo "Missing one or more of the required variables: SERVER, ENCODED_PRIVATE_KEY";
       echo "SERVER: ${SERVER}";
       echo "ENCODED_PRIVATE_KEY:  $(printf '%s' "${ENCODED_PRIVATE_KEY}" | cut -c 3)...";
       exit 1;
    fi

    # Setup SSH access to a server using $ENCODED_PRIVATE_KEY and $SERVER
    apk add openssh-client bash || apt install openssh-client;
    eval "$( ssh-agent -s )";
    echo "$ENCODED_PRIVATE_KEY" | base64 -d | ssh-add -;
    install -d -m 700 ~/.ssh/;
    ( umask 022; touch ~/.ssh/known_hosts );
    {
        ssh-keyscan "$SERVER"
        ssh-keyscan "$DEPLOY_HOST_B"
        ssh-keyscan "$DEPLOY_HOST_C"
    } >> ~/.ssh/known_hosts;

    # Docker login to all servers
    ssh deploy@"$DEPLOY_HOST_A" "docker login -u cicd -p $REGISTRY_ACCESS_TOKEN $CI_REGISTRY";
    ssh deploy@"$DEPLOY_HOST_B" "docker login -u cicd -p $REGISTRY_ACCESS_TOKEN $CI_REGISTRY";
    ssh deploy@"$DEPLOY_HOST_C" "docker login -u cicd -p $REGISTRY_ACCESS_TOKEN $CI_REGISTRY";
}
