#!/bin/bash

VUFIND_CORE_INSTALLATION=1 # TODO

runhelp() {
    echo ""
    echo "Purpose: Build the Vufind image"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - LATEST: Image tag for the latest image to use as cache"
    echo "  - CURR: Image tag for current image"
    echo "  - COMPONENT: Component name (context for the build)"
    echo "  - VUFIND_VERSION: The current version of Vufind"
    echo "  - Many other build Args: Documented in technical documentation"
    echo "    https://msu-libraries.github.io/catalog/CICD/#variables"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If the build fails"
    echo "  - If the push fails"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

main() {
    # Get the number of attempts for this job
    apk add jq curl || apt install -y jq curl;
    ATTEMPTS=$(curl -s --header "PRIVATE-TOKEN: ${RO_CICD_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/jobs?include_retried=true" | jq "[.[] | select(.name == \"${CI_JOB_NAME}\")] | length")
    echo "${CI_JOB_NAME// /_}_JobAttempts" "${ATTEMPTS}" >> metrics.txt

    # Determine job start time; used to calculate runtime metrics
    START=$(date +%s)

    if [[ ${VUFIND_CORE_INSTALLATION} == 1 ]]; then
      sed -i 's/VUFIND_LOCAL_MODULES=Catalog/VUFIND_LOCAL_MODULES=/' vufind/Dockerfile
    fi

    echo "Building image"
    DOCKER_BUILDKIT=1 docker build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --build-arg VUFIND_VERSION="${VUFIND_VERSION}" \
        --build-arg SOLR_URL=http://solr:8983/solr \
        --build-arg SIMPLESAMLPHP_VERSION="${SIMPLESAMLPHP_VERSION}" \
        --tag "${CURR}" \
        --cache-from "${LATEST}" \
        vufind/;

    EC=$?;
    if [[ ${EC} -ne 0 ]]; then
        echo "Failed to build. Sleeping to add delay before potential retry.";
        sleep 3;
        exit ${EC};
    fi;

    echo "Pushing image"
    docker push "${CURR}";

    EC=$?;
    if [[ ${EC} -ne 0 ]]; then
        echo "Failed to push. Sleeping to add delay before potential retry.";
        sleep 3;
        exit ${EC};
    fi;

    if [[ ${CI_DEFAULT_BRANCH} == "${CI_COMMIT_BRANCH}" || ${CI_COMMIT_BRANCH} == "catalog-preview" ]]; then
        echo "Pushing new unique main image tag"
        docker tag "${CURR}" "${CURR}-main";
        docker push "${CURR}-main";
        echo "Pushing new image with :latest tag"
        docker tag "${CURR}" "${LATEST}";
        docker push "${LATEST}";
    fi

    EC=$?;
    if [[ ${EC} -ne 0 ]]; then
        echo "Failed to add latest tag. Sleeping to add delay before potential retry.";
        sleep 3;
        exit ${EC};
    fi;

    # Get runtime metrics
    END=$(date +%s); RUNTIME=$((END-START)); HOURS=$((RUNTIME / 3600)); MINUTES=$(( (RUNTIME % 3600) / 60 )); SECONDS=$(( (RUNTIME % 3600) % 60 ));
    echo "${CI_JOB_NAME// /_}_Runtime" $HOURS:$MINUTES:$SECONDS >> metrics.txt
}

# exit script if any command fails
set -e;
# set xtrace to show commands being run in the CI job logs
set -o xtrace
main;
