#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

run_help() {
    echo ""
    echo "Purpose: Clear the VuFind cache volume"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo "  - DEPLOY_HOST_2: The second host in the cluster"
    echo "  - DEPLOY_HOST_3: The third host in the cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If cache clear script fails"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    run_help
    exit 0
fi

main() {
    # Clear cache on all catalog nodes
    NODES=(1 2 3)
    for NODE in "${NODES[@]}"; do
        # Kick off cache clear in the background on each node
        run_in_node_service "$NODE" "$STACK_NAME" "catalog_catalog" "clear-vufind-cache" &
    done

    # Wait for all cache clears to complete
    wait
    echo "Cache cleared on all nodes."
}

before_script
main

