#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Performs updates to the docker-compose files and deploys them to the server"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - SITE_HOSTNAME: URL for the site"
    echo "  - BASICAUTH_FOR_RESOURCES: Authenication to use for developer resources (i.e. Traefik and Solr)"
    echo "  - GITHUB_USER_TOKEN: Used when downloading yq from Github"
    echo "  - DEPLOY_HOST_A: The first host in the cluster"
    echo "  - COMPOSE_PATH: Where to put the docker-compose files on the DEPLOY_HOST_A server"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If any of the yq commands fail"
    echo "  - If the compose files fail to copy to the server"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

declare -a -g HTTPS_MIDDLEWARES=(remove-prefix)

apply_devel_changes() {
    # Use dnschallenge cert resolver (instead of httpchallenge)
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.monitoring.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.monitoring.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.monitoring.yml;

    # Remove the cron service if this is a devel environment
    ./yq -i "del(.services.cron)" docker-compose.yml;

    # Unset parallelism limit for non-production to speed up redeployments on devel stacks
    ./yq -i "del(.services.catalog.deploy.update_config.parallelism)" docker-compose.yml;

    # Add host router rules
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-mail.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/mail\`)\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/mail\`)\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-links.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
    docker-compose.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels +=\"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
    docker-compose.monitoring.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels +=\"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
    docker-compose.monitoring.yml;

    # Disable container rollback
    ./yq -i "del(.services.monitoring.deploy.update_config.failure_action)" docker-compose.monitoring.yml;
    ./yq -i "del(.x-solrproxy-deploy.update_config.failure_action)" docker-compose.solr-cloud-bootstrap.yml;
    ./yq -i "del(.services.zk.deploy.update_config.failure_action)" docker-compose.zk.yml;
    ./yq -i "del(.x-solrproxy-deploy.update_config.failure_action)" docker-compose.solr-cloud.yml;
    ./yq -i "del(.services.galera.deploy.update_config.failure_action)" docker-compose.mariadb-cloud.yml;
    ./yq -i "del(.services.galera.deploy.update_config.failure_action)" docker-compose.mariadb-cloud-force.yml;
    ./yq -i "del(.services.galera.deploy.update_config.failure_action)" docker-compose.mariadb-cloud-bootstrap.yml;
    ./yq -i "del(.services.cron.deploy.update_config.failure_action)" docker-compose.solr-cloud.yml;
    ./yq -i "del(.services.catalog.deploy.update_config.failure_action)" docker-compose.yml;
    ./yq -i "del(.services.croncache.deploy.update_config.failure_action)" docker-compose.yml;
    ./yq -i "del(.services.cron.deploy.update_config.failure_action)" docker-compose.yml;

    # Disable healthchecks on catalog service
    ./yq -i ".services.catalog.healthcheck.disable=true" docker-compose.yml

    # Reduce the catalog service replicas to 1
    ./yq -i ".services.catalog.deploy.replicas = 1" docker-compose.yml

}

apply_prod_changes() {
    ## Apply to catalog-preview, catalog-beta, and catalog-prod ##

    # Build extra environment suffix for image tag
    export EXTRA_TAG_SUFFIX="-main";

    # Increase Solr RAM to 2 GB (note: prod is further increased below)
    ./yq -i \
    ".x-solr-envs.SOLR_JAVA_MEM = \"-Xms2048m -Xmx2048m\"" \
    docker-compose.solr-cloud.yml;

    # Use httpchallenge cert resolver (instead of dnschallenge)
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.monitoring.yml;

    # Remove the croncache service if the stack name is production
    ./yq -i "del(.services.croncache)" docker-compose.yml;

    # Remove mailcatcher service
    ./yq -i "del(.services.mail-*)" docker-compose.yml;

    ## Changes for catalog-beta and catalog-preview
    if [ "${STACK_NAME}" == "catalog-beta" ] || [ "${STACK_NAME}" == "catalog-preview" ]; then
        # Override default router rule
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-links.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
    fi

    ## Changes for catalog-prod
    if [ "${STACK_NAME}" == "catalog-prod" ]; then
        # Increase Solr RAM to 4 GB (prod is granted more than non-prod envs)
        ./yq -i \
        ".x-solr-envs.SOLR_JAVA_MEM = \"-Xms4096m -Xmx4096m\"" \
        docker-compose.solr-cloud.yml;
        # Override default router rule
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-links.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.middlewares.${STACK_NAME}-redirect.redirectregex.regex=^https://catalog-prod.lib.msu.edu/(.*)\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.middlewares.${STACK_NAME}-redirect.redirectregex.replacement=https://catalog.lib.msu.edu/\$\${1}\"" \
        docker-compose.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.middlewares.${STACK_NAME}-redirect.redirectregex.permanent=true\"" \
        docker-compose.yml;
        HTTPS_MIDDLEWARES+=("${STACK_NAME}-redirect")
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`,\`catalog.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
    fi
}

main() {
    # Install yq, enbsubst, and sponge
    apk add wget gettext moreutils;
    wget --header="Authorization: token ${GITHUB_USER_TOKEN}" \
    "https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64" -O ./yq;
    chmod +x ./yq;

    # Replace custom includes with related files
    for f in *.yml; do
        sed -i -e "/#include vufind-envs/r vufind-envs" -e "/#include vufind-envs/d" "$f"
    done

    # Development environment changes
    if [[ "${STACK_NAME}" != catalog-* ]]; then
        apply_devel_changes;
    fi
    # Production environment changes
    if [[ "${STACK_NAME}" == catalog-* ]]; then
        apply_prod_changes;
    fi

    # Add in middlewares
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.middlewares=$(IFS=, ; echo "${HTTPS_MIDDLEWARES[*]}")\"" \
    docker-compose.yml;

    # Authentication environment changes
    if [[ "${STACK_NAME}" == catalog-* ]] || [ "${STACK_NAME}" == "devel-authentication" ]; then
      ./yq -i ".services.catalog.volumes += \"/home/deploy/samlcerts/${STACK_NAME}:/mnt/samlcerts:ro\"" docker-compose.yml;
    fi

    # Save CI variables
    env | grep -f <(grep -ohE '\$[A-Z_]+|\$\{[A-Z_]+\}' ./*.yml | tr -d '{}$' | sort -u) | sed -E -e 's/([A-Z_]+=)(.*)/export \1"\2"/' >.env
    chmod o-r .env

    # Remove blank lines as a workaround for issue caused by: https://github.com/mikefarah/yq/issues/1191
    sed -i "/^$/d" docker-compose.internal.yml;
    sed -i "/^$/d" docker-compose.yml;

    # Copy the updated compose files to the server
    ssh deploy@"${DEPLOY_HOST_A}" mkdir -p "${COMPOSE_PATH}";
    scp docker-compose* .env deploy@"${DEPLOY_HOST_A}":"${COMPOSE_PATH}"/;
    rm .env
    echo "Copying files to ${COMPOSE_PATH}"
}

beforescript
main
