#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Performs updates to the docker-compose files and deploys them to the server"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - SITE_HOSTNAME: URL for the site"
    echo "  - BASICAUTH_FOR_RESOURCES: Authentication to use for developer resources (i.e. Traefik and Solr)"
    echo "  - GITHUB_USER_TOKEN: Used when downloading yq from Github"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo "  - COMPOSE_PATH: Where to put the docker-compose files on the DEPLOY_HOST_1 server"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If any of the yq commands fail"
    echo "  - If the compose files fail to copy to the server"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

declare -a -g HTTPS_MIDDLEWARES=(remove-prefix)

apply_devel_changes() {
    # Restrict devel/review to campus IPs only
    HTTPS_MIDDLEWARES+=("ip-campus")
    # Use dnschallenge cert resolver (instead of httpchallenge)
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.certresolver=msul-letsencrypt-dns\"" \
    docker-compose.monitoring.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.domains[0].main=aws.lib.msu.edu\"" \
    docker-compose.monitoring.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.domains[0].sans=*.aws.lib.msu.edu\"" \
    docker-compose.monitoring.yml;

    # Remove the cron service if this is a devel environment
    ./yq -i "del(.services.cron)" docker-compose.catalog.yml;

    # Unset parallelism limit for non-production to speed up redeployments on devel stacks
    ./yq -i "del(.services.catalog.deploy.update_config.parallelism)" docker-compose.catalog.yml;

    # Add host router rules
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-mail.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/mail\`)\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.mail-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-mail.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/mail\`)\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-links.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels +=\"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
    docker-compose.monitoring.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels +=\"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.aws.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
    docker-compose.monitoring.yml;

    # Disable container rollback
    ./yq -i "del(.services.monitoring.deploy.update_config.failure_action)" docker-compose.monitoring.yml;
    ./yq -i "del(.x-solrproxy-deploy.update_config.failure_action)" docker-compose.solr-cloud-bootstrap.yml;
    ./yq -i "del(.services.zk.deploy.update_config.failure_action)" docker-compose.zk.yml;
    ./yq -i "del(.x-solrproxy-deploy.update_config.failure_action)" docker-compose.solr-cloud.yml;
    ./yq -i "del(.services.galera.deploy.update_config.failure_action)" docker-compose.mariadb-cloud.yml;
    ./yq -i "del(.services.galera.deploy.update_config.failure_action)" docker-compose.mariadb-cloud-force.yml;
    ./yq -i "del(.services.galera.deploy.update_config.failure_action)" docker-compose.mariadb-cloud-bootstrap.yml;
    ./yq -i "del(.services.cron.deploy.update_config.failure_action)" docker-compose.solr-cloud.yml;
    ./yq -i "del(.services.catalog.deploy.update_config.failure_action)" docker-compose.catalog.yml;
    ./yq -i "del(.services.croncache.deploy.update_config.failure_action)" docker-compose.catalog.yml;
    ./yq -i "del(.services.cron.deploy.update_config.failure_action)" docker-compose.catalog.yml;

    # Disable healthchecks on catalog service
    ./yq -i ".services.catalog.healthcheck.disable=true" docker-compose.catalog.yml

    # Reduce the catalog service replicas to 1
    ./yq -i ".services.catalog.deploy.replicas = 1" docker-compose.catalog.yml

}

apply_prod_changes() {
    ## Apply to catalog-preview, catalog-beta, and catalog-prod ##

    # Build extra environment suffix for image tag
    export EXTRA_TAG_SUFFIX="-main";

    # Increase Solr RAM to 4+1.5GB (note: prod is further increased below)
    ./yq -i \
    ".x-solr-envs.SOLR_JAVA_MEM = \"-Xms4096m -Xmx4096m -XX:MaxDirectMemorySize=1536m\"" \
    docker-compose.solr-cloud.yml;
    # Increase Docker limit (note: prod is further increased below)
    ./yq -i \
    ".services.solr.deploy.resources.limits.memory = \"8192M\"" \
    docker-compose.solr-cloud.yml;

    # Use httpchallenge cert resolver (instead of dnschallenge)
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.catalog.yml;
    ./yq -i \
    ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.solr-cloud.yml;
    ./yq -i \
    ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.tls.certresolver=msul-letsencrypt\"" \
    docker-compose.monitoring.yml;

    # Remove the croncache service if the stack name is production
    ./yq -i "del(.services.croncache)" docker-compose.catalog.yml;

    # Remove mailcatcher service
    ./yq -i "del(.services.mail-*)" docker-compose.catalog.yml;

    ## Changes for catalog-beta and catalog-preview
    if [ "${STACK_NAME}" == "catalog-beta" ] || [ "${STACK_NAME}" == "catalog-preview" ]; then
        # Restrict both beta/preview to campus IPs only
        HTTPS_MIDDLEWARES+=("ip-campus")
        ## Only catalog-beta
        if [ "${STACK_NAME}" == "catalog-beta" ]; then
            # Set cron/build placement contraint
            ./yq -i ".services.cron.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_2}\"]" docker-compose.catalog.yml;
            ./yq -i ".services.build.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_2}\"]" docker-compose.build.yml;
        fi;
        ## Only catalog-preview
        if [ "${STACK_NAME}" == "catalog-preview" ]; then
            # Set cron/build placement contraint
            ./yq -i ".services.cron.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_3}\"]" docker-compose.catalog.yml;
            ./yq -i ".services.build.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_3}\"]" docker-compose.build.yml;
        fi;
        ## both catalog-beta and catalog-preview
        # Override default router rule
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-links.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.rule=Host(\`${STACK_NAME}.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
    fi

    ## Changes for catalog-prod
    if [ "${STACK_NAME}" == "catalog-prod" ]; then
        # Set cron/build placement constraint
        ./yq -i ".services.cron.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_1}\"]" docker-compose.catalog.yml;
        ./yq -i ".services.build.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_1}\"]" docker-compose.build.yml;
        # Increase Solr RAM to 8+2.5GB (prod is granted more than non-prod envs)
        ./yq -i \
        ".x-solr-envs.SOLR_JAVA_MEM = \"-Xms8192m -Xmx8192m -XX:MaxDirectMemorySize=2560m\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".services.solr.deploy.resources.limits.memory = \"16384M\"" \
        docker-compose.solr-cloud.yml;

        # Override default router rule
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-router.rule=Host(\`catalog.lib.msu.edu\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.rule=Host(\`catalog.lib.msu.edu\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-http-links.rule=Host(\`catalog.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".services.legacylinks.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-links.rule=Host(\`catalog.lib.msu.edu\`) && PathPrefix(\`/record=\`)\"" \
        docker-compose.catalog.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxysolr-router.rule=Host(\`catalog.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".x-solrproxy-deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxysolr-router.rule=Host(\`catalog.lib.msu.edu\`) && PathPrefix(\`/solr\`)\"" \
        docker-compose.solr-cloud.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-msul-proxymonitoring-router.rule=Host(\`catalog.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
        ./yq -i \
        ".services.proxymon-\$STACK_NAME.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-msul-proxymonitoring-router.rule=Host(\`catalog.lib.msu.edu\`) && PathPrefix(\`/monitoring\`)\"" \
        docker-compose.monitoring.yml;
    fi
}

# set_or_update_docker_secret $SECRET_NAME $SECRET_VALUE
set_or_update_docker_secret() {
    SECRET_NAME="${STACK_NAME}-$1"
    SECRET_VALUE="$2"
    # Check if the secret exists and creating it
    if ! ssh deploy@"${DEPLOY_HOST_1}" docker secret inspect "${SECRET_NAME}" > /dev/null 2>&1; then
        echo "Creating secret ${SECRET_NAME}"
        printf "%s" "${SECRET_VALUE}" | ssh deploy@"${DEPLOY_HOST_1}" docker secret create "${SECRET_NAME}" -
    fi
}

main() {
    # Log the start of the pipeline stage
    date +%s >> "${CI_JOB_STAGE}"_start.txt

    set_or_update_docker_secret "MARIADB_MONITORING_PASSWORD" "${MARIADB_MONITORING_PASSWORD}"
    set_or_update_docker_secret "MARIADB_ROOT_PASSWORD" "${MARIADB_ROOT_PASSWORD}"
    set_or_update_docker_secret "MARIADB_GALERA_MARIABACKUP_PASSWORD" "${MARIADB_GALERA_MARIABACKUP_PASSWORD}"
    set_or_update_docker_secret "MARIADB_PASSWORD" "${MARIADB_VUFIND_PASSWORD}"
    set_or_update_docker_secret "MARIADB_VUFIND_PASSWORD" "${MARIADB_VUFIND_PASSWORD}"
    set_or_update_docker_secret "HLM_FTP_PASSWORD" "${HLM_FTP_PASSWORD}"
    set_or_update_docker_secret "SIMPLESAMLPHP_ADMIN_PW" "${SIMPLESAMLPHP_ADMIN_PW}"
    set_or_update_docker_secret "DEPLOY_KEY" "${DEPLOY_KEY}"

    # Install yq, envsubst, and sponge
    apk add wget gettext moreutils;
    wget --header="Authorization: token ${GITHUB_USER_TOKEN}" \
    "https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64" -O ./yq;
    chmod +x ./yq;

    for f in *.yml; do
        # Replace custom includes with related files
        sed -i -e "/#include vufind-envs/r vufind-envs" -e "/#include vufind-envs/d" "$f"

        # Secrets prefixing with ${STACK_NAME}-
        if [[ $(./yq '.secrets' "$f") != null ]]; then
            # Replace secret pattern to specify their stack :
            # /run/secrets/MARIADB_ROOT_PASSWORD => /run/secrets/${STACK_NAME}-MARIADB_ROOT_PASSWORD
            sed -i "s|/run/secrets/|/run/secrets/${STACK_NAME}-|g" "$f"
            ./yq -i ".services |= with_entries(select(.value.secrets |= map(\"${STACK_NAME}-\" + .)))" "$f"
            ./yq -i ".secrets |= with_entries(select(.value.external == true) .key |= \"${STACK_NAME}-\" + .)" "$f"
        fi
    done

    # Development environment changes
    if [[ "${STACK_NAME}" != catalog-* ]]; then
        apply_devel_changes;
    fi
    # Production environment changes
    if [[ "${STACK_NAME}" == catalog-* ]]; then
        apply_prod_changes;
    fi

    # Add in middlewares
    ./yq -i \
    ".services.catalog.deploy.labels += \"traefik.http.routers.${STACK_NAME}-https-router.middlewares=$(IFS=, ; echo "${HTTPS_MIDDLEWARES[*]}")\"" \
    docker-compose.catalog.yml;

    # Authentication environment changes
    if [[ "${STACK_NAME}" == catalog-* ]] || [ "${STACK_NAME}" == "devel-authentication" ]; then
      ./yq -i ".services.catalog.volumes += \"/home/deploy/samlcerts/${STACK_NAME}:/mnt/samlcerts:ro\"" docker-compose.catalog.yml;
    fi

    # Save CI variables
    env | grep -f <(grep -ohE '\$[A-Z_]+|\$\{[A-Z_]+\}' ./*.yml | tr -d '{}$' | sort -u) | sed -E -e 's/([A-Z_]+=)(.*)/export \1"\2"/' >.env
    chmod o-r .env

    # Remove blank lines as a workaround for issue caused by: https://github.com/mikefarah/yq/issues/1191
    sed -i "/^$/d" docker-compose.internal.yml;
    sed -i "/^$/d" docker-compose.catalog.yml;

    # Copy the updated compose files to the server
    ssh deploy@"${DEPLOY_HOST_1}" mkdir -p "${COMPOSE_PATH}";
    scp docker-compose* .env deploy@"${DEPLOY_HOST_1}":"${COMPOSE_PATH}"/;
    rm .env
    echo "Copying files to ${COMPOSE_PATH}"

    # Get runtime metrics
    END=$(date +%s); RUNTIME=$((END-START)); HOURS=$((RUNTIME / 3600)); MINUTES=$(( (RUNTIME % 3600) / 60 )); SECONDS=$(( (RUNTIME % 3600) % 60 ));
    echo "${CI_JOB_NAME// /_}_Runtime" $HOURS:$MINUTES:$SECONDS >> metrics.txt
}

beforescript
main
