#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

run_help() {
    echo ""
    echo "Purpose: Deploy the Vufind build service in the catalog application stack"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Stack name"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo "  - DEPLOY_HOST_2: The second host in the cluster"
    echo "  - DEPLOY_HOST_3: The third host in the cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - Deploying the stack fails"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    run_help
    exit 0
fi

main() {
    # Pull images now to save time with stack deploy
    run_on_all_nodes "docker pull $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA"

    run_on_node 1 "docker stack deploy --with-registry-auth -c <(source ${COMPOSE_PATH}/.env; envsubst <${COMPOSE_PATH}/docker-compose.build.yml) ${STACK_NAME}-catalog";
    
    # Set URL
    URL="${SITE_HOSTNAME}";
    
    # Report the environemnt URL to GitLab
    echo "URL=${URL}" >> deploy.env;
}

before_script
main
