#!/bin/bash

echo "Sourcing before_script"
source "${CI_PROJECT_DIR}"/cicd/before-script

run_help() {
    echo ""
    echo "Purpose: Deploy the internal network for the stack"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo "  - COMPOSE_PATH: Where the docker-compose files are located on the DEPLOY_HOST_1"
    echo ""
    echo "Failure Scenarios:"
    echo "  - The stack deploy command fails"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    run_help
    exit 0
fi

main() {
    run_on_node 1 "docker stack deploy --prune -c <(source ${COMPOSE_PATH}/.env; envsubst <${COMPOSE_PATH}/docker-compose.internal.yml) ${STACK_NAME}-internal"

    sleep 15

    # Get runtime metrics
    END=$(date +%s); RUNTIME=$((END-START)); HOURS=$((RUNTIME / 3600)); MINUTES=$(( (RUNTIME % 3600) / 60 )); SECONDS=$(( (RUNTIME % 3600) % 60 ));
    echo "${CI_JOB_NAME// /_}_Runtime" $HOURS:$MINUTES:$SECONDS >> metrics.txt
}

echo "Running before_script"
before_script
echo "Running main"
main
