#!/bin/bash

echo "Sourcing beforescript"
source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Deploy the internal network for the stack"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo "  - COMPOSE_PATH: Where the docker-compose files are located on the DEPLOY_HOST_1"
    echo ""
    echo "Failure Scenarios:"
    echo "  - The stack deploy command fails"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

main() {
    ssh deploy@"${DEPLOY_HOST_1}" "docker stack deploy --prune -c <(source ${COMPOSE_PATH}/.env; envsubst <${COMPOSE_PATH}/docker-compose.internal.yml) ${STACK_NAME}-internal"

    sleep 15
}

echo "Running beforescript"
beforescript
echo "Running main"
main
