#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

run_help() {
    echo ""
    echo "Purpose: Create the volume for the logs and initialize the directory with"
    echo "         proper permissions for MariaDB and Solr"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo "  - DEPLOY_HOST_2: The second host in the cluster"
    echo "  - DEPLOY_HOST_3: The third host in the cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If creation of the volumes failed"
    echo "  - If creating the database log directory or setting the permissions failed"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    run_help
    exit 0
fi

main() {
    # Create logs volume and set permissions for /mnt/logs/mariadb so that mariadb can write the log there (same for solr)
    run_on_all_nodes "docker volume create ${STACK_NAME}_logs &&
                docker run --rm -v ${STACK_NAME}_logs:/mnt/logs \
                    alpine sh -c 'mkdir -p /mnt/logs/mariadb /mnt/logs/solr && chown 1001 /mnt/logs/mariadb /mnt/logs/solr'"

    # Create a bind mount for the nagios user
    run_on_all_nodes "sudo /usr/local/bin/pc-mount-logs ${STACK_NAME} /home/nagios/ -v --create-service";
}

before_script
main
