#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Take a backup of all database nodes on the production environment"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Stack name, used to check if catalog-prod"
    echo "  - DEPLOY_HOST_A: First node in the deploy cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If the backup script returns a non-zero exit code"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

main() {
    if [[ "${STACK_NAME}" != catalog-prod ]]; then
        echo "Not backing up non production environment.";
        exit 0;
    fi

    CONTAINER="$(ssh deploy@"${DEPLOY_HOST_A}" "docker ps -q -f name=${STACK_NAME}-catalog_catalog")";

    if [[ -n "${CONTAINER}" ]]; then
        echo "Performing a database backup";
        ssh deploy@"${DEPLOY_HOST_A}" "docker exec ${CONTAINER} /backup.sh --db --rotations 5 -v";
    fi
}

beforescript
main
