#!/bin/bash

runhelp() {
    echo ""
    echo "Purpose: Prepopulate development and review environments with data"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_A: The first host in the cluster"
    echo "  - DEPLOY_HOST_B: The second host in the cluster"
    echo "  - DEPLOY_HOST_C: The third host in the cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - The catalog container is not online on the node"
    echo "  - The Solr container is not online on the node"
    echo "  - The import scripts fail for any reason"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

main() {
    # Determine if records are already loaded
    CONTAINER_A=$(ssh deploy@"${DEPLOY_HOST_A}" "docker ps -q -f name=${STACK_NAME}-catalog_catalog") || echo "";
    CONTAINER_B=$(ssh deploy@"${DEPLOY_HOST_B}" "docker ps -q -f name=${STACK_NAME}-catalog_catalog") || echo "";
    CONTAINER_C=$(ssh deploy@"${DEPLOY_HOST_C}" "docker ps -q -f name=${STACK_NAME}-catalog_catalog") || echo "";
    S_CONTAINER_A=$(ssh deploy@"${DEPLOY_HOST_A}" "docker ps -q -f name=${STACK_NAME}-solr_cron") || echo "";
    S_CONTAINER_B=$(ssh deploy@"${DEPLOY_HOST_B}" "docker ps -q -f name=${STACK_NAME}-solr_cron") || echo "";
    S_CONTAINER_C=$(ssh deploy@"${DEPLOY_HOST_C}" "docker ps -q -f name=${STACK_NAME}-solr_cron") || echo "";

    if [ -z "${CONTAINER_A}" ] || [ -z "${CONTAINER_B}" ] || [ -z "${CONTAINER_C}" ] ; then
        echo "Could not find container for ${STACK_NAME}-catalog_catalog on all 3 nodes";
        exit 1;
    fi;

    if [ -z "${S_CONTAINER_A}" ] || [ -z "${S_CONTAINER_B}" ] || [ -z "${S_CONTAINER_C}" ] ; then
        echo "Could not find container for ${STACK_NAME}-solr_cron on all 3 nodes";
        exit 1;
    fi;

    STAT_CD=$(ssh deploy@"${DEPLOY_HOST_A}" "docker exec ${CONTAINER_A} curl 'http://solr:8983/solr/biblio/select?indent=true&q.op=OR&q=*%3A*&rows=0' --write-out %{http_code} --silent --output /dev/null") || echo "-1";

    if [[ "${STAT_CD}" -ne 200 ]]; then
        echo "Failed to get number of records from Solr. Curl returned ${STAT_CD}.";
        exit 1;
    fi;

    NUM_RECS=$(ssh deploy@"${DEPLOY_HOST_A}" "docker exec ${CONTAINER_A} curl -s 'http://solr:8983/solr/biblio/select?indent=true&q.op=OR&q=*%3A*&rows=0' | jq '.response.numFound'") ||  echo "-1";

    if [[ "${NUM_RECS}" -eq "0" ]]; then
        # Load some records
        echo "Running harvest-and-import.sh now";
        ssh deploy@"${DEPLOY_HOST_A}" "docker exec ${CONTAINER_A} /harvest-and-import.sh -c -l 1 -b -r -s /mnt/shared/oai/devel-batch >/dev/null 2>&1";
        echo "Import completed with exit code $?";
        echo "Running HLM harvest-and-import.sh now";
        ssh deploy@"${DEPLOY_HOST_A}" "docker exec ${CONTAINER_A} /hlm-harvest-and-import.sh -l 1 -c -i -s /mnt/shared/hlm/devel-batch >/dev/null 2>&1";
        echo "Import completed with exit code $?";
        # Rebuild alphabetic browse databases
        echo "Running Alphabetic browse database build";
        ssh deploy@"${DEPLOY_HOST_A}" "docker exec ${S_CONTAINER_A} /alpha-browse.sh -v -p /mnt/shared/alpha-browse/${STACK_NAME}";
        ssh deploy@"${DEPLOY_HOST_B}" "docker exec ${S_CONTAINER_B} /alpha-browse.sh -v -p /mnt/shared/alpha-browse/${STACK_NAME}";
        ssh deploy@"${DEPLOY_HOST_C}" "docker exec ${S_CONTAINER_C} /alpha-browse.sh -v -p /mnt/shared/alpha-browse/${STACK_NAME}";
        echo "Completed alphabetic browse database build";
    else
        echo "${NUM_RECS} loaded records already exist. Doing nothing.";
    fi;
}

main
