#!/bin/bash

# shellcheck disable=SC1091
source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Upgrade database tables after a new DB version is deployed"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_1: The first host in the cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - The upgrade fails"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

main() {
    for NODE in {1..3}; do
        echo "Running db-upgrade for ${STACK_NAME}-mariadb_galera node ${NODE}."
        run_in_node_service "${NODE}" "${STACK_NAME}" "mariadb_galera" "db-upgrade"
        sleep 5
    done

    # Get runtime metrics
    END=$(date +%s); RUNTIME=$((END-START)); HOURS=$((RUNTIME / 3600)); MINUTES=$(( (RUNTIME % 3600) / 60 )); SECONDS=$(( (RUNTIME % 3600) % 60 ));
    echo "${CI_JOB_NAME// /_}_Runtime" $HOURS:$MINUTES:$SECONDS >> metrics.txt
}

before_script
main
