#!/bin/bash

runhelp() {
    echo ""
    echo "Purpose: Run validation on the VuFind image"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - CURR: Image tag for the VuFind image to test"
    echo ""
    echo "Failure Scenarios:"
    echo "  - When the unit tests return a non-zero exit code"
    echo "  - When the code quality scans return a non-zero exit code"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp;
    exit 0;
fi

main() {
    echo "Pulling image ${CURR} for validation...";
    docker pull "${CURR}";

    echo "Running PHP unit tests";
    echo "vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
    docker run --rm "${CURR}" vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/;
    EC=$?;

    if [[ ${EC} -ne 0 ]]; then
        echo "One or more unit tests failed. Run the following command to debug";
        echo "docker run --rm \"${CURR}\" vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
        exit ${EC};
    fi;
    
    echo "Running code style checks";
    echo "vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console";
    docker run --rm "${CURR}" vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console;
    EC=$?;
    if [[ ${EC} -ne 0 ]]; then
        echo "One or more of the style checks failed. Run the following command to debug";
        echo "docker run --rm \"${CURR}\" vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console"
        exit ${EC};
    fi;

    echo "All validations have passed";
}

# exit script if any command fails
set -e;
# set xtrace to show commands being run in the CI job logs
set -o xtrace
main;
