#!/bin/bash

runhelp() {
    echo ""
    echo "Purpose: Run validation on the VuFind image"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - CURR: Image tag for the VuFind image to test"
    echo ""
    echo "Failure Scenarios:"
    echo "  - When the unit tests return a non-zero exit code"
    echo "  - When the code quality scans return a non-zero exit code"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp;
    exit 0;
fi

main() {
    echo "Building image"
    DOCKER_BUILDKIT=1 docker build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --build-arg GITHUB_USER_TOKEN="${GITHUB_USER_TOKEN}" \
        --build-arg VUFIND_VERSION="${VUFIND_VERSION}" \
        --build-arg SOLR_URL=http://solr:8983/solr \
        --build-arg SIMPLESAMLPHP_VERSION="${SIMPLESAMLPHP_VERSION}" \
        --tag validate \
        --cache-from "${LATEST}" \
        vufind/;

    EC=$?;
    if [[ ${EC} -ne 0 ]]; then
        echo "Failed to build. Sleeping to add delay before potential retry.";
        sleep 3;
        exit ${EC};
    fi;

    echo "Running PHP unit tests";
    echo "vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
    docker run --rm validate vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/;
    EC=$?;

    if [[ ${EC} -ne 0 ]]; then
        echo "One or more unit tests failed. Run the following command in a VuFind container to debug";
        echo "vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
        exit ${EC};
    fi;
    
    echo "Running code style checks";
    echo "vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console";
    docker run --rm msul-validate vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console;
    EC=$?;
    if [[ ${EC} -ne 0 ]]; then
        echo "One or more of the style checks failed. Run the following command in a VuFind container to debug";
        echo "vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console"
        exit ${EC};
    fi;

    docker image rm msul-validate;
    echo "All validations have passed";
}

# exit script if any command fails
set -e;
# set xtrace to show commands being run in the CI job logs
set -o xtrace
main;
