#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Verify the health of the stack by calling the check"
    echo "         scripts used by the NCPA plugin"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_A: The first host in the cluster"
    echo "  - DEPLOY_HOST_B: The second host in the cluster"
    echo "  - DEPLOY_HOST_C: The third host in the cluster"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If the NCPA plugin returns a non-zero exit code"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

check() {
    SERVICE=$1;
    HEALTHY=0;
    for HOST in ${HOSTS}; do
        ATTEMPTS=0;
        while [[ "${ATTEMPTS}" -le 60 ]]; do
            echo "$(date +'%m-%d-%Y %T %z') -- (${HOST}): Checking ${SERVICE} health...";
            if ssh deploy@"${HOST}" "/usr/local/ncpa/plugins/check_${SERVICE}.sh ${STACK_NAME}"; then
                echo "$(date +'%m-%d-%Y %T %z') -- (${HOST}): ${SERVICE} is healthy!";
                HEALTHY=1;
                break;
            fi
            echo "$(date +'%m-%d-%Y %T %z') -- (${HOST}): ${SERVICE} not healthy yet. Waiting...";
            sleep 15;
            ATTEMPTS=$((ATTEMPTS+1));
        done
        if [[ "${HEALTHY}" -ne 1 ]]; then
            echo "$(date +'%m-%d-%Y %T %z') -- (${HOST}): ${SERVICE} not healthy after max attempts. Failing job!";
            exit 1;
        fi;
    done
}

main() {
    HOSTS="$DEPLOY_HOST_A $DEPLOY_HOST_B $DEPLOY_HOST_C";

    echo "Update the services before running checks"
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-catalog_legacylinks" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-monitoring_monitoring" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-solr_cron" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-solr_proxysolr" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-solr_zk" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-catalog_catalog" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-solr_solr" &
    ssh deploy@"${DEPLOY_HOST_A}" "docker service update ${STACK_NAME}-mariadb_galera";
    wait

    echo "Run checks using the NCPA scripts"
    check solr
    check zk
    check galera
    check docker
}

beforescript
main
