#!/bin/bash

source "${CI_PROJECT_DIR}"/cicd/before-script

runhelp() {
    echo ""
    echo "Purpose: Run the vufind upgrade command through cURL"
    echo ""
    echo "Expected User-defined Variables:"
    echo "  - STACK_NAME: Name of the stack"
    echo "  - DEPLOY_HOST_A: The first host in the cluster"
    echo "  - DEPLOY_HOST_B: The second host in the cluster"
    echo "  - DEPLOY_HOST_C: The third host in the cluster"
    echo "  - URL: URL for the instance"
    echo "  - PREV_VUFIND_VERSION: The previous version of Vufind"
    echo ""
    echo "Failure Scenarios:"
    echo "  - If the cURL calls fail"
    echo "  - If unable to set/unset the auto-configure setting"
    echo "  - The catalog container is not online on the node"
    echo ""
}

if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
    runhelp
    exit 0
fi

setconfig() {
    # shellcheck disable=SC2034
    OLDVAL=$1;
    # shellcheck disable=SC2034
    NEWVAL=$2;
    for HOST in ${HOSTS}; do
        CONTAINER=$(ssh deploy@"${HOST}" "docker ps -q -f name=${STACK_NAME}-catalog_catalog") || echo "";
        if [ -z "${CONTAINER}" ]; then
          echo "Could not find container for ${STACK_NAME}-catalog_catalog!";
          exit 1;
        fi;
        ssh deploy@"${HOST}" "docker exec ${CONTAINER} sed -i 's/autoConfigure = ${OLDVAL}/autoConfigure = ${NEWVAL}/g' local/config/vufind/config.ini";
    done
}

main() {
    HOSTS="$DEPLOY_HOST_A $DEPLOY_HOST_B $DEPLOY_HOST_C";

    apk add curl || apt install curl -y;

    echo "Enabling auto configure temporarily";
    setconfig "false" "true";

    echo "Running Vufind upgrade now against ${URL}";
    curl "${URL}/Upgrade/GetSourceVersion" -k --data-raw "sourceversion=${PREV_VUFIND_VERSION}&skip%5B%5D=config" -L -O;
    echo "Upgrade complete with exit code $?";

    echo "Disabling auto configure";
    setconfig "true" "false";
}

beforescript
main
