<h1>Different search types information</h1>
<p>The catalog site has two main search options: <i>Catalog</i> and <i>Articles & More</i></p>
<dl class="Content">
  <dt class="h2">Catalog</dt>
  <dd>
    <p>The <i>Catalog</i> search covers all physical materials, eBooks, and journal <i>titles</i> held by the MSU Libraries.</p>
  </dd>

  <dt class="h2">Articles & More</dt>
  <dd>
    <p>The <i>Articles & More</i> search includes all journal <i>articles</i> along with a wide variety of online content licensed by the MSU Libraries.</p>
  </dd>
</dl>
