<h1>Different search types information</h1>

<ul class="HelpMenu">
  <li><a href="#catalog">Catalog Searches</a></li>
  <li><a href="#articles_and_more">Articles & More Searches</a></li>
</ul>

<dl class="Content">
  <dt class="h2"><a id="catalog"></a>Catalog Searches</dt>
  <dd>
    <p>In this tab, you can search the library catalog.</p>
  </dd>

  <dt class="h2"><a id="articles_and_more"></a>Articles & More Searches</dt>
  <dd>
    <p>In this tab, you can search through available digital content owned by the library and accessible through EBSCO.</p>
  </dd>
</dl>
