<?php /** MSU Start - Icons for JS actions (hierarchical checkboxes) */ ?>
<div style="display: none" id="jsContent">
  <div class="expander">
    <span class="chevronRight"><?= $this->icon('chevron-right') ?></span>
    <span class="chevronDown"><?= $this->icon('chevron-down') ?></span>
  </div>
</div>
<?php /** MSU END */ ?>
<?=$this->render('search/advanced/solr-facets.phtml')?>
<?php if (isset($this->illustratedLimit)): ?>
  <fieldset class="solr">
    <legend><?=$this->transEsc('Illustrated')?>:</legend>
    <?php foreach ($this->illustratedLimit as $current): ?>
      <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected'] ? ' checked="checked" data-checked-by-default="true"' : ''?>>
      <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br>
    <?php endforeach; ?>
  </fieldset>
<?php endif; ?>
<?=$this->render('search/advanced/limit.phtml')?>
<?=$this->render('search/advanced/ranges.phtml')?>
