<footer class="hidden-print">
  <div class="footer-container vf-footer">
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('footer_header_search_options')?></h2>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-center')->start(); ?>
        <h2><?=$this->transEsc('footer_header_find_more')?></h2>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Explore Catalog by Filters')?></a></li>
 <!--         <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li> -->
 <!--         <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li> -->
  <!--        <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li> -->
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
        </ul>
      <?=$this->slot('footer-center')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('footer_header_need_help')?></h2>
        <ul>
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <li><a href="https://lib.msu.edu/contact/askalib/">Ask a Librarian</a></li>
<!--         <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li> -->
          <?php if ($this->cookieConsent()->isEnabled()): ?>
            <li><a href="#" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a></li>
          <?php endif; ?>
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>



<div class="msul-prefooter">
<div class="footer-container">

<div class="footer-column">
    <a href="https://lib.msu.edu/" aria-label="Michigan State University Libraries">
      <img class="img-responsive" alt="Michigan State University Libraries" src="/themes/msul/images/MSUL_Helmet-Signature_reverse.png">
    </a>
    <div>
      <div class="msul-address-icon" aria-hidden="true">
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><title>Michigan State University Libraries address</title><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
      </div>
      <div class="msul-address">
        <address>
          <a href="https://goo.gl/maps/PsFndYZqwFXD5vPH9">
            MSU Libraries<br aria-hidden="true">
            366 W. Circle Drive<br aria-hidden="true">
            East Lansing, MI 48824 USA
          </a>
        </address>
      </div>
    </div>
      <div class="msul-phone-icon" aria-hidden="true">
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone"><title>Michigan State University Libraries phone number</title><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
      </div>
      <div class="msul-phone">
        <a href="tel:15173538700" aria-label="Phone Number 5 1 7. 3 5 3. 8 7 0 0">
          (517) 353-8700<br>
        </a>
      </div>
  </div>

  <div class="footer-column">
    <ul>
   <!--  <li><a id="preFooterfaq" href="/">Frequently asked questions</a></li> -->

      <li><a id="preFooterA11yStatement" href="https://lib.msu.edu/general/accessibility/">Accessibility statement</a></li>

   <!--  <li><a id="preFooterReportA11y" href="/">Report an accessibility issue</a></li> -->
      <li><a id="preFooterPrivacy" href="https://lib.msu.edu/about/privacystmt/">Privacy statement</a></li>
   <!--  <li><a id="preFooterLibraryUnits" href="/">Library units</a></li> -->
      <li><a id="preFooterStaffDirectory" href="https://lib.msu.edu/staffdir/">Staff directory</a></li>
    </ul>
  </div>

  <div class="footer-column">
    <ul>
      <li><a id="preFooterSpaces" href="https://lib.msu.edu/library-spaces/">Discover Library spaces</a></li>
      <li><a id="preFooterEmployment" href="https://lib.msu.edu/human-resources/employment/">Employment</a></li>
      <li><a id="preFooterSupport" href="https://lib.msu.edu/support/">Support the Libraries</a></li>
      <li><a id="preFooterSitemap" href="https://lib.msu.edu/atoz/">Site map</a></li>
      <li id="preFooterSocial">
        <a href="https://www.facebook.com/msu.libraries" class="pe-2" aria-label="Michigan State University Libraries Facebook account">
          <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook"><title>Michigan State University Libraries Facebook account</title><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>
        </a>
        <a href="https://www.instagram.com/msulibraries/" class="pe-2" aria-label="Michigan State University Libraries Instagram account">
          <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram"><title>Michigan State University Libraries Instagram account</title><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>
        </a>
        <a href="https://twitter.com/msulibraries" class="pe-2" aria-label="Michigan State University Libraries Twitter account">
          <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><title>Michigan State University Libraries Twitter account</title><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>
        </a>
        <a href="https://www.youtube.com/channel/UCcyAXBxyxPA13Ko-o3yiRYQ" class="pe-2" aria-label="Michigan State University Libraries Youtube account">
          <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-youtube"><title>Michigan State University Libraries Youtube account</title><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg>
        </a>
      </li>
    </ul>
  </div>
</div>
</div>


  <div class="msu-footer">
    <div class="container">
      <div class="row">
        


  <div class="col-lg-9 col-lg-push-3">
        
        <ul>
            <li class="small-text">
Call MSU:     <a href="tel:5173551855" target="">(517) 355-1855</a>

                <span>|</span>
            </li>
            <li class="small-text">
Visit:    <a href="https://msu.edu/visit/" target="_blank">msu.edu</a>

                <span>|</span>
            </li>
            <li class="small-text">
MSU is an affirmative-action, equal-opportunity employer.
                <span>|</span>
            </li>
            <li class="bold-text small-text">
    <a href="https://civilrights.msu.edu/policies/" target="">Notice of Nondiscrimination</a>

            </li>
        </ul>
        <ul>
            <li class="small-text">
SPARTANS WILL.
                <span>|</span>
            </li>
            <li class="small-text">
© Michigan State University
            </li>
        </ul>
  </div>


  <div class="col-lg-3 col-lg-pull-9">
    <a href="https://msu.edu/"><img src="/themes/msul/images/msu-wordmark-green.svg?la=en&amp;hash=8E089B07620E2E1A11309309C66BC6F3" alt="Michigan State University Home" /></a>
  </div>


      </div>
    </div>
  </div>


</footer>




