<footer class="hidden-print">
  <div class="footer-container vf-footer">
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('Search Options')?></h2>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-center')->start(); ?>
        <h2><?=$this->transEsc('Find More')?></h2>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
          <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
          <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
        </ul>
      <?=$this->slot('footer-center')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('Need Help?')?></h2>
        <ul>
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>



  <div class="msu-footer">
    <div class="container">
      <div class="row">
        


  <div class="col-lg-9 col-lg-push-3">
        
        <ul>
            <li class="small-text">
Call MSU:     <a href="tel:5173551855" target="">(517) 355-1855</a>

                <span>|</span>
            </li>
            <li class="small-text">
Visit:    <a href="https://msu.edu/visit/" target="_blank">msu.edu</a>

                <span>|</span>
            </li>
            <li class="small-text">
MSU is an affirmative-action, equal-opportunity employer.
                <span>|</span>
            </li>
            <li class="bold-text small-text">
    <a href="https://civilrights.msu.edu/policies/" target="">Notice of Nondiscrimination</a>

            </li>
        </ul>
        <ul>
            <li class="small-text">
SPARTANS WILL.
                <span>|</span>
            </li>
            <li class="small-text">
© Michigan State University
            </li>
        </ul>
  </div>


  <div class="col-lg-3 col-lg-pull-9">
    <a href="https://msu.edu/"><img src="/themes/msul/images/msu-wordmark-green.svg?la=en&amp;hash=8E089B07620E2E1A11309309C66BC6F3" alt="Michigan State University Home" /></a>
  </div>


      </div>
    </div>
  </div>
</footer>




