<footer class="hidden-print">
  <div class="footer-container vf-footer">
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('footer_header_search_options')?></h2>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
          <li><a href="https://eds.lib.msu.edu" target="_blank"><?=$this->transEsc('EDS catalog interface')?><?= $this->icon('fa-external-link', 'fa-external-link') ?></a></li>
        </ul>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-center')->start(); ?>
        <h2><?=$this->transEsc('footer_header_find_more')?></h2>
        <ul>
 <!--         <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li> -->
          <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Explore Catalog by Filters')?></a></li>
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
          <li><a href="https://lib.msu.edu/ils" target="_blank"><?=$this->transEsc('Search Other Libraries')?><?= $this->icon('fa-external-link', 'fa-external-link') ?></a></li>
        </ul>
      <?=$this->slot('footer-center')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('footer_header_need_help')?></h2>
        <ul>
          <li><a href="https://lib.msu.edu/callnumbers" target="_blank">Call Number Locations<?= $this->icon('fa-external-link', 'fa-external-link') ?></a></li>
          <li><a href="https://lib.msu.edu/contact/askalib/" target="_blank">Ask a Librarian<?= $this->icon('fa-external-link', 'fa-external-link') ?></a></li>
          <li><a href="<?=$this->url('help', ['topic' => 'z3950'])?>" data-lightbox><?=$this->transEsc('Z39.50 Access')?></a></li>
          <li><a href="<?=$this->url('help', ['topic' => 'oaipmh'])?>" data-lightbox><?=$this->transEsc('OAI-PMH Access')?></a></li>
<!--         <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li> -->
          <?php if ($this->cookieConsent()->isEnabled()): ?>
            <li><a href="#" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a></li>
          <?php endif; ?>
          <li><a href="<?=$this->url('feedback-home') ?>" data-lightbox><?=$this->transEsc('Feedback')?></a></li>
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>



<div class="msul-prefooter">
<div class="footer-container">

<div class="footer-column">
    <a href="https://lib.msu.edu/" aria-label="Michigan State University Libraries">
      <img class="img-responsive msul_logo" alt="Michigan State University Libraries" src="/themes/msul/images/MSUL_Helmet-Signature_reverse.png">
    </a>
    <div>
      <div class="msul-address-icon" aria-hidden="true">
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><title>Michigan State University Libraries address</title><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
      </div>
      <div class="msul-address">
        <address>
          <a href="https://goo.gl/maps/PsFndYZqwFXD5vPH9">
            MSU Libraries<br aria-hidden="true">
            366 W. Circle Drive<br aria-hidden="true">
            East Lansing, MI 48824 USA
          </a>
        </address>
      </div>
    </div>
      <div class="msul-phone-icon" aria-hidden="true">
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone"><title>Michigan State University Libraries phone number</title><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
      </div>
      <div class="msul-phone">
        <a href="tel:15173538700" aria-label="Phone Number 5 1 7. 3 5 3. 8 7 0 0">
          (517) 353-8700<br>
        </a>
      </div>
  </div>

  <div class="footer-column">
    <ul>
   <!--  <li><a id="preFooterfaq" href="/">Frequently asked questions</a></li> -->

      <li><a id="preFooterA11yStatement" href="https://lib.msu.edu/accessibility/">Accessibility</a></li>

   <!--  <li><a id="preFooterReportA11y" href="/">Report an accessibility issue</a></li> -->
      <li><a id="preFooterPrivacy" href="https://lib.msu.edu/policies/privacy-statement">Privacy Statement</a></li>
      <li><a id="preFooterLibraryUnits" href="https://lib.msu.edu/orgchart">Library Units</a></li>
      <li><a id="preFooterStaffDirectory" href="https://lib.msu.edu/staff">Staff Directory</a></li>
    </ul>
  </div>

  <div class="footer-column">
    <ul>
      <li><a id="preFooterSpaces" href="https://lib.msu.edu/spaces">Discover Library Spaces</a></li>
      <li><a id="preFooterEmployment" href="https://lib.msu.edu/human-resources/employment">Employment</a></li>
      <li><a id="preFooterSupport" href="https://lib.msu.edu/support">Support the Libraries</a></li>
      <li class="mb-4"><a id="preFooterSitemap" href="https://lib.msu.edu/sitemap">Site Map</a></li>      
      <li id="preFooterSocial" class="text-center">
        <a href="https://www.facebook.com/msu.libraries" aria-label="Michigan State University Libraries Facebook account"><img class="text-center" alt="" role="presentation" aria-hidden="true" src="/themes/msul/images/Icons_Facebook.svg"></a>
        <a href="https://www.instagram.com/msulibraries/" aria-label="Michigan State University Libraries Instagram account"><img class="text-center" alt="" role="presentation" aria-hidden="true" src="/themes/msul/images/Icons_Instagram.svg"></a>
        <a href="https://twitter.com/msulibraries" aria-label="Michigan State University Libraries Twitter account"><img class="text-center" alt="" role="presentation" aria-hidden="true" src="/themes/msul/images/Icons_Twitter.svg"></a>
        <a href="https://www.youtube.com/channel/UCcyAXBxyxPA13Ko-o3yiRYQ" aria-label="Michigan State University Libraries Youtube account"><img class="text-center" alt="" role="presentation" aria-hidden="true" src="/themes/msul/images/Icons_YouTube.svg"></a>
      </li>
    </ul>
  </div>
</div>
</div>


  <div class="msu-footer">
    <div class="container">
      <div class="row">
        


  <div class="col-lg-9 order-2">
        
        <ul>
            <li class="small-text">
Call MSU:     <a href="tel:5173551855" target="">(517) 355-1855</a>

                <span>|</span>
            </li>
            <li class="small-text">
Visit:    <a href="https://msu.edu/visit/" target="_blank">msu.edu</a>

                <span>|</span>
            </li>
            <li class="bold-text small-text">
    <a href="https://civilrights.msu.edu/policies/" target="">Notice of Nondiscrimination</a>

            </li>
        </ul>
        <ul>
            <li class="small-text">
SPARTANS WILL.
                <span>|</span>
            </li>
            <li class="small-text">
© Michigan State University
            </li>
        </ul>
  </div>


  <div class="col-lg-3 order-1">
    <a href="https://msu.edu/"><img src="/themes/msul/images/msu-wordmark-green.svg?la=en&amp;hash=8E089B07620E2E1A11309309C66BC6F3" alt="Michigan State University Home"></a>
  </div>


      </div>
    </div>
  </div>


</footer>




