<?php $account = $this->auth()->getManager(); $isTestTenant = str_contains(getenv("FOLIO_URL"), 'test'); ?>
<div class="banner container navbar">
  <div class="navbar-header">
    <div class="navbar-msubrand"><a href="https://msu.edu/" rel="nofollow"><img alt="Michigan State University" src="/themes/msul/images/masthead-helmet-white.png"></a></div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-hidden="true">
      <i class="fa fa-bars"><span class="sr-only">Top Menu</span></i>
    </button>

    <h2 class="navbar-msul"><a href="https://lib.msu.edu/">MSU Libraries</a></h2>
    <h1 class="navbar-catalog"><a href="<?=$this->url('home') ?>">Public Catalog</a></h1>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right flip">
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon" class="fa fa-user-circle" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <?php if($account->dropdownEnabled()): ?>
              <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
                <div class="dropdown-menu">
                  <?=$this->render('myresearch/menu'); ?>
                </div>
              </li>
            <?php endif; ?>
            <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <?php else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                      <?=$this->transEsc($current['desc']) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>
  <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['lng' => $langCode])) ?>" rel="nofollow">
                      <?=$this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

        </ul>
      </nav>
    </div>
  <?php endif; ?>
</div>
<?php if ($isTestTenant): ?>
  <div class="collapse navbar-collapse" id="navbar-warning">
    <p>
      <b>Notice:</b> This catalog is connected to the FOLIO test tenant, and should be used for testing purposes only.
      The information here is not up-to-date, and item availability will not be accurate.
      <a href="https://catalog-prod.lib.msu.edu" target="_blank">
        <i class="fa fa-sign-in" aria-hidden="true"></i>
        Go to the production catalog
      </a>
    </p>
  </div>
<?php else: ?>
  <div class="collapse navbar-collapse" id="navbar-warning">
    <p>
      Welcome to the new interface to the MSU Libraries catalog,
      expected to launch in May 2023. While
      <a href="https://catalog.lib.msu.edu/" target="_blank">
        <i class="fa fa-sign-in" aria-hidden="true"></i> EDS
      </a>
      remains the official catalog, you can use this site as an alternative, and
      <em>
        help us improve it by providing
        <a data-lightbox href="<?=$this->url('feedback-home') ?>">feedback and suggestions</a>!
      </em>
    </p>
  </div>
<?php endif; ?>
<?php if ($this->layout()->searchbox !== false): ?>
  <div class="search container navbar">
    <div class="nav searchbox hidden-print" role="search">
      <?=$this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>
