<?php
  include $this->parentTemplate('myresearch/menu.phtml');
  $isCommunityBorrower = $user != null ? $this->auth()->isCommunityBorrower() : false;
  $this->layout()->searchbox = false;
?>

<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <?php if (!$isCommunityBorrower): ?>
    <hr>
      &nbsp&nbsp<a target="_blank" href="https://interlib.lib.msu.edu/">
        <i class="fa fa-fw fa-external-link" aria-hidden="true"></i> Illiad Account
      </a><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>(MSU Students, Staff, and Faculty)</small>
  <?php endif; ?>
<?php endif; ?>
