<?=$this->component('hide-offcanvas-button')?>
<?php foreach ($this->menu as $menuGroup): ?>
  <h2 id="<?=$this->idPrefix ?? ''?><?=$menuGroup['id']?>"><?=$this->transEsc($menuGroup['label'])?></h3> <?php // MSU h3 to h2 ?>
  <nav class="myresearch-menu" aria-labelledby="<?=$this->idPrefix ?? ''?><?=$menuGroup['id']?>">
    <ul<?=!empty($menuGroup['class']) ? ' class="' . $menuGroup['class'] . '"' : ''?>>
      <?php foreach ($menuGroup['MenuItems'] as $item): ?>
        <?=$this->render($item['template'] ?? 'myresearch/menu-item.phtml', ['active' => $this->active, ...$item])?>
      <?php endforeach; ?>
    </ul>
  </nav>
<?php endforeach ?>
<?php
  // MSU Start
  $isCommunityBorrower = $user != null ? $this->auth()->isCommunityBorrower() : false;
  $this->layout()->searchbox = false;
?>

<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <?php if (!$isCommunityBorrower): ?>
    <hr>
        <div class="myresearch-menu">
            <a href="https://interlib.lib.msu.edu/" class="icon-link">
                <?= $this->icon('fa-external-link', 'fa-external-link icon-link__icon') ?>
                <span class="icon-link__label">Illiad Account <small>(MSU Students, Staff, and Faculty)</small></span>
            </a>
        </div>
  <?php endif; ?>
<?php endif; ?>
<?php // MSU end ?>
