---
- name: Create AWS config directory
  file:
    path: "~/.aws"
    state: directory

- name: Create AWS credential file
  copy:
    dest: "~/.aws/credentials"
    content: "{{ aws_credential_template }}"

- name: Provision DNS CNAME
  community.general.terraform:
    project_path: "../dns-terraform/env/prod/"
    state: present
    provider_upgrade: yes
    # focing init because state file exists in s3 and need provider
    # installed locally before we can detect it
    force_init: yes 
