<h3><a class="btn" data-bs-toggle="collapse" href="#collapseCommunity" role="button" aria-expanded="false" aria-controls="collapseCommunity">Community Borrowers</a></h3>
<div class="collapse" id="collapseCommunity">
  <div class="card card-body">
    <p>You may <a href="https://oaconnector.ebsco-gss.net/pinreset.php?organization=s8364774a" target="_blank">create or reset your PIN<span class="ps-1"></span><?= $this->icon('fa-external-link', 'fa-external-link') ?></a>, using your library card barcode as the username. If you need further assistance, see the <a href="https://lib.msu.edu/circ/borrowing-faq#heading--faqfield_field_faq_accordion_paragraph_374--8" target="_blank">FAQ</a>.</p>
