<h3><a data-toggle="collapse" href="#collapseCommunity" role="button" aria-expanded="false" aria-controls="collapseCommunity">Community Borrowers & Faculty Authorizations</a></h3>
<div class="collapse" id="collapseCommunity">
  <div class="card card-body">
  	<p>You may <a href="https://oaconnector.ebsco-gss.net/passwordreset.php?organization=s8364774">create or reset your password</a>, using your library card barcode as the username. If you need further assistance, see the <a href="https://lib.msu.edu/circ/borrowing-faq#heading--faqfield_field_faq_accordion_paragraph_374--8">FAQ</a>.</p>
