############# Build ###############
Build DB Image:
  variables:
     COMPONENT: db
  extends: .build_template

Build Solr Image:
  variables:
     COMPONENT: solr
  extends: .build_template

Build ZK Image:
  variables:
     COMPONENT: zk
  extends: .build_template

Build Ansible Image:
  variables:
     COMPONENT: ansible
  extends: .build_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

Build Monitoring Image:
  variables:
     COMPONENT: monitoring
  extends: .build_template

Build LegacyLinks Image:
  variables:
     COMPONENT: legacylinks
  extends: .build_template

Build Vufind Image:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  environment:
    name: $CI_COMMIT_BRANCH
    action: prepare
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_DEPLOY_FREEZE == null && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/vufind:latest
    CURR: $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Stack Name
      artifacts: true
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache bash
  script:
    - bash ./cicd/build-vufind

Validate Vufind Build:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_DEPLOY_FREEZE == null && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    CURR: $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA
  needs:
    - Build Vufind Image
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache bash
  script:
    - bash ./cicd/validate-vufind-build

############# Templates ###############

.build_template:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_DEPLOY_FREEZE == null && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/$COMPONENT:latest
    CURR: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache bash
  needs:
    - job: Set Stack Name
      artifacts: true
  script:
    - bash ./cicd/build-general
