############# Build ###############
Build DB Image:
  variables:
     COMPONENT: db
  extends: .build_template

Build Solr Image:
  variables:
     COMPONENT: solr
  extends: .build_template

Build ZK Image:
  variables:
     COMPONENT: zk
  extends: .build_template

Build Ansible Image:
  variables:
     COMPONENT: ansible
  extends: .build_template

Build Monitoring Image:
  variables:
     COMPONENT: monitoring
  extends: .build_template

Build Vufind Image:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  environment:
    name: $CI_COMMIT_BRANCH
    action: prepare
  interruptible: true
  rules:
    - if: '($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule") && $CI_DEPLOY_FREEZE == null'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/vufind:latest
    CURR: $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Stack Name
      artifacts: true
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cicd/build-vufind

############# Templates ###############

.build_template:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  interruptible: true
  rules:
    - if: '($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule") && $CI_DEPLOY_FREEZE == null'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/$COMPONENT:latest
    CURR: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  needs:
    - job: Set Stack Name
      artifacts: true
  script:
    - cicd/build-general
