############# Build ###############
Build DB Image:
  variables:
     COMPONENT: db
  extends: .build_template

Build Solr Image:
  variables:
     COMPONENT: solr
  extends: .build_template

Build ZK Image:
  variables:
     COMPONENT: zk
  extends: .build_template

Build Ansible Image:
  variables:
     COMPONENT: ansible
  extends: .build_template

Build Vufind Image:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  environment:
    name: $CI_COMMIT_BRANCH
    action: prepare
  interruptible: true
  rules:
    - if: '($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule") && $CI_DEPLOY_FREEZE == null'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/vufind:latest
    CURR: $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Stack Name
      artifacts: true
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $LATEST || true
    - > 
        docker build 
        --build-arg GITHUB_USER_TOKEN=$GITHUB_USER_TOKEN
        --build-arg VUFIND_VERSION=$VUFIND_VERSION
        --build-arg SITE_HOSTNAME=$SITE_HOSTNAME
        --build-arg FOLIO_URL=$FOLIO_URL 
        --build-arg FOLIO_USER=$FOLIO_USER 
        --build-arg FOLIO_PASS=$FOLIO_PASS 
        --build-arg FOLIO_TENANT=$FOLIO_TENANT 
        --build-arg FOLIO_REC_ID=$FOLIO_REC_ID 
        --build-arg FOLIO_CANCEL_ID=$FOLIO_CANCEL_ID 
        --build-arg OAI_URL=$OAI_URL 
        --build-arg EMAIL=$EMAIL 
        --build-arg MAIL_HOST=host.docker.internal
        --build-arg MAIL_PORT=25 
        --build-arg MAIL_USERNAME= 
        --build-arg MAIL_PASSWORD= 
        --build-arg FEEDBACK_EMAIL=$FEEDBACK_EMAIL 
        --build-arg SOLR_URL=http://solr:8983/solr 
        --build-arg EDS_USER=$EDS_USER
        --build-arg EDS_PASS=$EDS_PASS
        --build-arg EDS_PROFILE=$EDS_PROFILE
        --build-arg EDS_ORG=$EDS_ORG
        --build-arg RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY
        --build-arg RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
        --build-arg SIMPLESAMLPHP_VERSION=$SIMPLESAMLPHP_VERSION
        --build-arg SIMPLESAMLPHP_SALT=$SIMPLESAMLPHP_SALT
        --build-arg SIMPLESAMLPHP_ADMIN_PW=$SIMPLESAMLPHP_ADMIN_PW
        --build-arg FTP_USER=$FTP_USER
        --build-arg FTP_PASSWORD=$FTP_PASSWORD
        --build-arg AUTH_FTP_USER=$AUTH_FTP_USER
        --build-arg AUTH_FTP_PASSWORD=$AUTH_FTP_PASSWORD
        --build-arg DEPLOY_KEY=$DEPLOY_KEY
        --tag $CURR 
        --cache-from $LATEST 
        vufind/
    - docker push $CURR
    - |
      if [[ $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH ]]; then
        docker tag $CURR $LATEST
        docker push $LATEST
      fi

Build Monitoring Image:
  variables:
     COMPONENT: monitoring
  extends: .build_template

############# Templates ###############

.build_template:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  interruptible: true
  rules:
    - if: '($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule") && $CI_DEPLOY_FREEZE == null'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/$COMPONENT:latest
    CURR: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  needs:
    - job: Set Stack Name
      artifacts: true
  script:
    - docker pull $LATEST || true
    - > 
        docker build 
        --tag $CURR
        --build-arg VUFIND_VERSION=$VUFIND_VERSION
        --cache-from $LATEST 
        $COMPONENT/
    - docker push $CURR
    - |
      if [[ $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH ]]; then
        docker tag $CURR $LATEST
        docker push $LATEST
      fi
