############# Build ###############

Build DB Image:
  variables:
     COMPONENT: db
  extends: .build_template

Build Solr Image:
  variables:
     COMPONENT: solr
  extends: .build_template

Build ZK Image:
  variables:
     COMPONENT: zk
  extends: .build_template

Build Ansible Image:
  variables:
     COMPONENT: ansible
  extends: .build_template

Build Internal Traefik Image:
  variables:
     COMPONENT: traefik-internal
  extends: .build_template
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Replace Name in providers file
    - sed -i "s/msul-galera/${STACK_NAME}-msul-galera/g" $COMPONENT/providers/internal.yml

Build Vufind Image:
  stage: Build
  tags:
    - msul-docker
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/ || $CI_PIPELINE_SOURCE == "schedule'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/vufind:latest
    CURR: $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Stack Name
      artifacts: true
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $LATEST || true
    - > 
        docker build 
        --build-arg DEBUG=false 
        --build-arg FOLIO_URL=$FOLIO_URL 
        --build-arg FOLIO_USER=$FOLIO_USER 
        --build-arg FOLIO_PASS=$FOLIO_PASS 
        --build-arg FOLIO_TENANT=$FOLIO_TENANT 
        --build-arg FOLIO_REC_ID=$FOLIO_REC_ID 
        --build-arg FOLIO_CANCEL_ID=$FOLIO_CANCEL_ID 
        --build-arg OAI_URL=$OAI_URL 
        --build-arg EMAIL=$EMAIL 
        --build-arg MAIL_HOST=localhost 
        --build-arg MAIL_PORT=25 
        --build-arg MAIL_USERNAME= 
        --build-arg MAIL_PASSWORD= 
        --build-arg SOLR_URL=http://solr:8983/solr 
        --tag $CURR 
        --cache-from $LATEST 
        vufind/
    - docker push $CURR
    - |
      if [[ $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH ]]; then
        docker tag $CURR $LATEST
        docker push $LATEST
      fi

############# Templates ###############

.build_template:
  stage: Build
  tags:
    - msul-shared
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/ || $CI_PIPELINE_SOURCE == "schedule'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/$COMPONENT:latest
    CURR: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  needs:
    - job: Set Stack Name
      artifacts: true
  script:
    - docker pull $LATEST || true
    - > 
        docker build 
        --tag $CURR 
        --cache-from $LATEST 
        $COMPONENT/
    - docker push $CURR
    - |
      if [[ $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH ]]; then
        docker tag $CURR $LATEST
        docker push $LATEST
      fi
