Build Prod DB Image:
  extends: .build_prod_template
  variables:
    COMPONENT: db

Build Prod Solr Image:
  extends: .build_prod_template
  variables:
    COMPONENT: solr

Build Prod ZK Image:
  extends: .build_prod_template
  variables:
    COMPONENT: zk

Build Prod Vufind Image:
  stage: Build Prod
  extends: Build Vufind Image
  rules:
    - if: '($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule") && $CI_DEPLOY_FREEZE == null'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/vufind-prod:latest
    CURR: $CI_REGISTRY_IMAGE/vufind-prod:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Prod Stack Name
      artifacts: true

.build_prod_template:
  stage: Build Prod
  extends: .build_template
  variables:
    LATEST: $CI_REGISTRY_IMAGE/$COMPONENT-prod:latest
    CURR: $CI_REGISTRY_IMAGE/$COMPONENT-prod:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Prod Stack Name
      artifacts: true
  rules:
    - if: '($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "schedule") && $CI_DEPLOY_FREEZE == null'
