############# Build ###############
Build DB Image:
  variables:
     COMPONENT: db
  extends: .build_template
  environment:
    name: $CI_COMMIT_BRANCH/build-db
    auto_stop_in: 2 weeks

Build Solr Image:
  variables:
     COMPONENT: solr
  extends: .build_template
  environment:
    name: $CI_COMMIT_BRANCH/build-solr
    auto_stop_in: 2 weeks

Build ZK Image:
  variables:
     COMPONENT: zk
  extends: .build_template
  environment:
    name: $CI_COMMIT_BRANCH/build-zk
    auto_stop_in: 2 weeks

Build Ansible Image:
  variables:
     COMPONENT: ansible
  extends: .build_template
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  environment:
    name: $CI_COMMIT_BRANCH/build-ansible
    auto_stop_in: 2 weeks

Build Monitoring Image:
  variables:
     COMPONENT: monitoring
  extends: .build_template
  environment:
    name: $CI_COMMIT_BRANCH/build-monitoring
    auto_stop_in: 2 weeks

Build LegacyLinks Image:
  variables:
     COMPONENT: legacylinks
  extends: .build_template
  environment:
    name: $CI_COMMIT_BRANCH/build-legacylinks
    auto_stop_in: 2 weeks

Build Vufind Image:
  stage: Build
  environment:
    name: $CI_COMMIT_BRANCH/build-vufind
    auto_stop_in: 2 weeks
  tags:
    - msul-shared
  retry: 2
  timeout: 10m
  environment:
    name: $CI_COMMIT_BRANCH
    action: prepare
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_DEPLOY_FREEZE == null && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/ || $CI_COMMIT_BRANCH == "catalog-preview"'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/vufind:latest
    CURR: $CI_REGISTRY_IMAGE/vufind:$CI_COMMIT_SHORT_SHA
  needs:
    - job: Set Stack Name
      artifacts: true
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache bash
  script:
    - bash ./cicd/build-vufind

############# Templates ###############

.build_template:
  stage: Build
  tags:
    - msul-shared
  retry: 2
  timeout: 10m
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_DEPLOY_FREEZE == null && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_COMMIT_BRANCH =~ /^devel-/ || $CI_COMMIT_BRANCH =~ /^review-/ || $CI_COMMIT_BRANCH == "catalog-preview"'
  variables:
    LATEST: $CI_REGISTRY_IMAGE/$COMPONENT:latest
    CURR: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --no-cache bash
  needs:
    - job: Set Stack Name
      artifacts: true
  script:
    - bash ./cicd/build-general
