<div>
    <p>
        <b>Request this Item:</b>
        Microform materials can be accessed and viewed on 2 West of the Main Library
        during open hours. Please note remotely held materials will have to be requested
        in advance using the Remote Storage Request. 
        <ul>
            <li>For more details, visit the 
                <a href='https://lib.msu.edu/general/collections/microforms/' target='_blank'>
                    Microforms Library homepage
                </a>
            </li>
        </ul>
    </p>
</div>

