<div>
    <p>
        <b>Request this Item:</b>
        Microform materials can be accessed and viewed on 2 West of the Main Library
        during <a href="https://lib.msu.edu/hours">open hours</a>. Please note remotely
        held materials will have to be requested in advance of in-person viewing to
        allow time for retrieval.
        <ul>
            <li>For more details on requesting microforms for viewing, visit the
                <a href='https://lib.msu.edu/general/collections/microforms/' target='_blank'>
                    Microforms Library homepage
                </a>
            </li>
        </ul>
    </p>
</div>

