<!-- Getthis: Otherlib -->
<?php
use Catalog\GetThis\RegexLookup as Regex;

$item = $this->getthis->getItem();
$loc = $this->getthis->getLocation();
$status = $this->getthis->getStatus();
$title = $this->driver->getTitle();
$title_full = $this->driver->getRawData()['title_full'];
$pubname = $this->driver->getPublisher();
$author = $this->driver->getPrimaryAuthor();
$isbn = $this->driver->getCleanISBN();
$callnum = $this->getthis->getCallNumber();
if (is_array($pubname)): $pubname = implode(", ", $pubname); endif;
?>
<div>
    <p><b><a href='https://ub.relaisd2d.com/?LS=MICHIGANSTATE&PI=MICHIGANSTATE' target="_blank">UBorrow</a>:</b> Borrow from the Big 10 libraries, typically available for pickup in 3-5 business days
       (MSU Students, Staff and Faculty only)</p>
    <ul>
        <?php
        $search = $isbn;
        if (empty($search)) $search = $title_full;
        ?>
            <li><a href="https://ub.relaisd2d.com/?LS=MICHIGANSTATE&PI=MICHIGANSTATE&query=<?= $search ?>" target="_blank">
            Search UBorrow</a></li>
    </ul>
    <?php
      # If law library use only material, display law patron form first
      if (Regex::SCHAEFER($loc) && $this->getthis->isOut()) { ?>
          <p><b>Law Library Inter-library Loan:</b> Law Library patrons can request this material through
              <a href="http://www.law.msu.edu/library/ill.php" target="_blank">the Inter-library Loan Request Form</a>
          </p>
     <?php
      } ?>
    <p><b><a href='https://lib.msu.edu/ils/' target="_blank">Inter-library Loan</a>:</b> Request materials through the Inter-library Loan Request Form.
        Typically available for pickup in 3-14 business days (MSU Students, Staff and Facaulty only)</p>
    <ul>
        <?php
        echo "<li><a href='https://interlib.lib.msu.edu/remoteauth/illiad.dll/OpenURL?rfr_id=info:sid/Catalog:" .
            $this->escapeHtml($status) . ":" . $this->escapeHtml($item == null ? '' : $item['barcode']) .
            "&rft.genre=book&LO=EYM%2CGZM%2CMUN&rft.title=" .
            $this->escapeHtml($title) . "&rft.au=" . $this->escapeHtml($author) . "&rft.pub=" . $this->escapeHtml($pubname) .
            "&rft.isbn=" . $this->escapeHtml($isbn) . "&loc=" .
            $this->escapeHtml($loc) . "&callno=" . $this->escapeHtml($callnum) .
            "&CAT=1' target='_blank'>Request Copy via ILLiad</a></li>";
        ?>
    </ul>
    <?php
    if (Regex::ROVI($loc) && $this->getthis->isMedia()) { ?>
    <p><b>Scans:</b> If you only need an article/chapter from this title, it can be typically delivered electronically in
        2-3 business days (MSU Students, Staff and Faculty only)</p>
    <ul>
        <?php
        echo "<li><a href='https://interlib.lib.msu.edu/remoteauth/illiad.dll/OpenURL?rfr_id=info:sid/Catalog:" .
            $this->escapeHtml($status) . ":" . $this->escapeHtml($item['barcode']) .
            "&rft.genre=article&LO=EYM%2CGZM%2CMUN&rft.title=" .
            $this->escapeHtml($title) . "&rft.au=" . $this->escapeHtml($author) . "&rft.pub=" . $this->escapeHtml($pubname) .
            "&rft.isbn=" . $this->escapeHtml($isbn) . "&loc=" . $this->escapeHtml($loc) . "&callno=" .
            $this->escapeHtml($callnum) .
            "&CAT=1' target='_blank'>Request a SCAN of Copy</a></li>";
    } ?>
    </ul>
</div>
