<!-- Getthis: remotepat -->
<div>
    <p>
        <b><a href="https://lib.msu.edu/ils/distance" target="_blank">Distance Delivery Services</a>:</b>
        For qualifying users, we deliver MSU materials directly to your home, free of charge, via UPS.
        Shipping is limited to MSU Students, Faculty and Staff residing more than 50 miles from campus.
        <ul>
            <li>
                <a href="https://lib.msu.edu/ils/distance" target="_blank">
                    Apply for Distance Delivery Service
                </a>
            </li>
        </ul>
    </p>
</div>
