<!-- Getthis: remotepat -->
<?php
$item = $this->getthis->getItem();
$loc = $this->getthis->getLocation();
$title = $this->driver->getTitle();
$author = $this->driver->getPrimaryAuthor();
$status = $this->getthis->getStatus();
$isbn = $this->driver->getCleanISBN();
$callnum = $this->getthis->getCallNumber();
$pubname = $this->driver->getPublisher();
if (is_array($pubname)): $pubname = implode(', ', $pubname); endif;
?>
<div>
    <p>
        <b><a href="https://lib.msu.edu/ils/distance" target="_blank">Distance Delivery Services</a>:</b>
        We deliver MSU materials directly to your home, free of charge,
        via UPS. Shipping is limited to anywhere in the US or Canada. (MSU Students, Faculty and Staff only)
        <ul>
            <li>
                <a href="https://interlib.lib.msu.edu/remoteauth/illiad.dll/OpenURL?rfr_id=info:sid/Catalog:distance&rft.genre=Book3&LO=EYM%2CGZM%2CMUN&rft.title=<?= $this->escapeHtml($title) ?>&rft.au=<?= $this->escapeHtml($author) ?>&rft.pub=<?= $this->escapeHtml($pubname) ?>&rft.isbn=<?= $this->escapeHtml($isbn) ?>&loc=<?= $this->escapeHtml($loc) ?>&callno=<?= $this->escapeHtml($callnum) ?>&CAT=1" target="_blank">
                    Request Item as Distance User
                </a>
            </li>
        </ul>
    </p>
</div>
