<?php include 'reqscan.phtml'; ?>
<div>
    <p>
        <b>
            <a href="https://lib.msu.edu/ils/articledelivery" target="_blank">
            Article Scan &amp; Electronic Delivery</a>:
        </b>
        We will pursue obtaining a scan of an article, chapter, or other limited textual
        material from another library, free of charge. (MSU Students, Staff and Faculty only)
    </p>
    <ul>
        <li><a href="https://interlib.lib.msu.edu/remoteauth/illiad.dll?Action=10&amp;Form=22<?= $param_str ?>"
        target="_blank">Request Article Scan</a></li>
    </ul>
</div>
