<?php
$item = $this->getthis->getItem();
$authors = $this->driver->getDeduplicatedAuthors();
$authors = array_keys(array_merge(
    $authors['primary'],
    $authors['secondary'],
    $authors['corporate'],
));
$isxns = array_merge($this->driver->getISSNs(), $this->driver->getISBNs());
$pass_params = [];
$pass_params['PhotoJournalTitle'] = $this->driver->getTitle();
$pass_params['PhotoArticleAuthor'] = count($authors) == 1 ? $authors[0] : '';
$pass_params['ISSN'] = count($isxns) == 1 ? $isxns[0] : '';
# Clean the ISxN
if ($pos = strpos($pass_params['ISSN'], ' ')) {
    $pass_params['ISSN'] = substr($pass_params['ISSN'], 0, $pos);
}
$pass_params['CallNumber'] = $this->getthis->getCallNumber();
$pass_params['PhotoJournalVolume'] = $item['enumchron'] ?? '';
$param_str = '';
foreach ($pass_params as $pkey => $pval) {
    if (!empty($pval)) {
        $param_str .= "&amp;{$pkey}=" . $this->escapeUrl($pval);
    }
}
?>
<div>
    <p>
        <b>
            <a href="https://lib.msu.edu/ils/articledelivery" target="_blank">
            Article Scan &amp; Electronic Delivery</a>:
        </b>
        We will scan and electronically deliver an article or chapter from
        MSU's print collection, free of charge, typically completed in 1-3
        business days. (MSU Staff, Faculty, and Students only)
    </p>
    <ul>
        <li><a href="https://interlib.lib.msu.edu/remoteauth/illiad.dll?Action=10&amp;Form=22<?= $param_str ?>"
        target="_blank">Request Article Scan</a></li>
    </ul>
</div>
