<!-- Getthis: scancopy -->
<?php
$item = $this->getthis->getItem();
$title = $this->driver->getTitle();
$callnum = $this->driver->getCallNumber();
$author = $this->driver->getPrimaryAuthor();
$loc = $this->getthis->getLocation();
$bibnum = $this->driver->getSierraBN();
$isbn = $this->driver->getCleanISBN();
$pubname = $this->driver->getPublisher();
if (is_array($pubname)): $pubname = implode(", ", $pubname); endif;

if ($this->getthis->isSerial()) {
    $scan = "Journal Article";
    $mattype= "ARTICLE2";
} else {
    $scan = "Book Chapter";
    $mattype="bookitem";
}
# Only show this template for non-media items
if (!$this->getthis->isMedia()) {
?>
<div>
    <p>
        <b><a href="https://www.lib.msu.edu/mars/" target="_blank">Request <?= $this->escapeHtml($scan) ?></a></b>
        We scan and electronically deliver an article or chapter
        from MSU's print collection, free of charge within 2-3 business days.
        (MSU Students, Staff and Faculty only)
        <ul>
            <li>
                <a href="https://interlib.lib.msu.edu/remoteauth/illiad.dll/OpenURL?rfr_id=info:sid/Catalog:<?= $this->escapeHtml($bibnum) ?>&rft.genre=<?= $this->escapeHtml($mattype) ?>&LO=EYM%2CGZM%2CMUN&rft.title=<?= $this->escapeHtml($title) ?>&rft.au=<?= $this->escapeHtml($author) ?>&rft.pub=<?= $this->escapeHtml($pubname) ?>&rft.isbn=<?= $this->escapeHtml($isbn) ?>&loc=<?= $this->escapeHtml($loc) ?>&callno=<?= $this->escapeHtml($callnum) ?>&CAT=1" target="_blank">
                    Request a Scan
                </a>
            </li>
        </ul>
    </p>
</div>
<?php
} ?>

