<?php
$item = $this->getthis->getItem();
$loc = $this->getthis->getLocation();
$title_full = $this->driver->getRawData()['title_full'];
$callnum = $this->driver->getCallNumber();
?>
<div>
    <b>Confirm Retrieval Request</b>
    <form data-lightbox="" method="POST" action="<?= $this->url(
        'record-getthissendrequest',
        [
            'id'     => $this->driver->getUniqueId(),
            'action' => 'GetThisSendRequest',
        ],
        [
            'query' => [
                "target" => "remotestorage",
            ],
        ]) ?>">
        <p><i>Title:</i> <?= $this->escapeHtml($title_full) ?><br /></p>
        <p><i>Call Number:</i> <?= $this->escapeHtml($callnum) ?><br /></p>
        <p><i>Retrieval From:</i> <?= $this->escapeHtml($loc) ?><br /></p>
        <br />
        <p>
            Please confirm your request to retrieve the above material
            and enter an email address to receive
            the confirmation of the request.
            Once the material is ready, you will be contacted with
            further instructions.
        </p>
        <p>
            <label for="requestemail">Email Address:</label>
            <input id="requestemail" type='email' name="email" required="required"
                value="<?= $this->escapeHtmlAttr($user_email) ?>"/><br />
        </p>
        <div class="text-center" style="font-size: 120%; font-weight: bold; margin-top: 1rem; margin-bottom: 0.5rem;">
            <input type='submit' value="Send Request" />
        </div>
    </form>
</div>
