<?php
$item = $this->getthis->getItem();
$pubname = $this->driver->getPublisher();
if (is_array($pubname)): $pubname = implode(', ', $pubname); endif;
$aeon_args = [
    'Action' => '10',
    'Form' => '21',
    'value' => 'VufindGenericRequest',
    'CallNumber' => $this->getthis->getCallNumber(),
    'ItemTitle' => substr($this->driver->getTitle(), 0, 255),
    'ItemEdition' => $this->driver->getEdition(),
    'ItemAuthor' => $this->driver->getPrimaryAuthor(),
    'ItemPublisher' => substr($pubname, 0, 255),
    'Location' => $this->getthis->getLocation(),
    'ItemNumber' => $this->driver->getSierraBN(),
    'ItemVolume' => ($item['barcode'] ?? ''),
];
?>
<div>
    <p>
        <b>
            <a href='https://lib.msu.edu/ua' target='_blank'>
            University Archives Collections Access</a>:
        </b>
        Material will be retrieved for viewing in the <a
        href='https://lib.msu.edu/hours/calendar/reading-room'
        target='_blank'>Special Collections and University Archives Reading
        Room</a> in the Main Library. Please allow up to 3 business days for
        delivery, or you may schedule a later date and time for viewing.
        <ul>
            <li>
                <a href='https://spcrequest.lib.msu.edu/Logon/?<?= http_build_query($aeon_args)?>' target='_blank'>Request Item</a>
            </li>
        </ul>
    </p>
</div>
