<?php
$callnum = $this->driver->getCallNumber();
?>
<div>
    <p>
        <b>
            <a href='https://lib.msu.edu/branches/ua/' target='_blank'>
            University Archives Collections Access</a>:
        </b>
        You may review the material at the University Archives &amp; Historical Collections in
        <a href='https://goo.gl/maps/cJzgFWghhRRAcFU5A' target='_blank'>Conrad Hall</a> using call number
        <?= $this->escapeHtml($callnum) ?> during the
        <a href='https://lib.msu.edu/branches/ua/Research/ReadingRoom/' target='_blank'>Reading Room</a>&#39;s open hours.
        <ul>
            <li>
                Please contact the University Archives &amp; Historical Collections at
                <a href='mailto:archives@msu.edu' target='_blank'>archives@msu.edu</a> or visit
                <a href='https://lib.msu.edu/branches/ua/' target='_blank'>University Archives</a> for information on how
                to access these materials.
            </li>
        </ul>
    </p>
</div>
