<?php if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
  <fieldset class="solr-facets">
    <legend><?=$this->transEsc('Limit To')?></legend>
    <?php if (!empty($this->checkboxFacets)): ?>
      <?=$this->render('search/advanced/checkbox-filters.phtml')?>
    <?php endif; ?>
    <div class="solr-facet-container">
      <?php foreach ($this->facetList as $field => $list): ?>
        <div class="solr-adv-facet">
          <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
          <?php /** MSU Code removed */ ?>
            <?php if (is_array($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
              <?php /** MSU START */ ?>
              <div class="form-control leveledCheckboxes" id="limit_<?= $this->escapeHtmlAttr(str_replace(' ', '', $field)) ?>">
                <?php foreach ($list['list'] as $value): ?>
                  <?php
                  $padding = str_pad('', 4 * $value['level'] * 6, '&nbsp;', STR_PAD_LEFT);
                  $display = $this->escapeHtml($value['displayText']);
                  ?>
                  <div
                      class="leveledCheckbox"
                      data-level="<?= $value['level'] ?>">
                    <?= $padding ?>
                    <label
                        for="<?= $this->escapeHtmlAttr($this->operatorToFieldPrefix($value['operator']) . $field . ':"' .
                          $value['value'] . '"') ?>">
                      <input
                          type="checkbox"
                          name="filter[]"
                          id="<?= $this->escapeHtmlAttr($this->operatorToFieldPrefix($value['operator']) . $field . ':"' .
                            $value['value'] . '"') ?>"
                          value="<?= $this->escapeHtmlAttr($this->operatorToFieldPrefix($value['operator']) . $field . ':"' .
                            $value['value'] . '"') ?>"
                        <?= (isset($value['selected']) && $value['selected']) ? ' checked="checked"' : '' ?>/>
                      <?= $display ?>
                    </label>
                  </div>
                <?php endforeach; ?>
              </div>
              <?php /** MSU END */ ?>
            <?php else: ?>
              <?php /** MSU START */ ?>
              <select class="form-control"
                      id="limit_<?= $this->escapeHtmlAttr(str_replace(' ', '', $field)) ?>" name="filter[]"
                      multiple="multiple" size="10">
              <?php /** MSU END */ ?>
              <?php
              // Sort the current facet list alphabetically and filter items to
              // the top if they appear in the config; we'll use this data
              // along with the foreach below to display facet options in the
              // correct order.
              $conf = $this->options->limitOrderOverride($field);
              $conf = array_flip($conf);
              $sorted = [];
              $filtered = [];
              $filterKeys = [];
              foreach ($list['list'] as $i => $value) {
                if (!empty($value['value'] && !empty($value['displayText']))) {
                  if (isset($conf[$value['value']])) {
                    $filtered[$i] = $value['displayText'];
                    $filterKeys[$value['displayText']] = $conf[$value['value']];
                  } else {
                    $sorted[$i] = $value['displayText'];
                  }
                }
              }
              $this->sorter()->natsort($sorted);

              // Order filtered items according to how they appear in the config.
              uasort($filtered, function ($a, $b) use ($filterKeys) {
                return $filterKeys[$a] <=> $filterKeys[$b];
              });

              // Combine filtered and sorted arrays so that the items in the config
              // appear in order at the top and all other items appear afterwards
              // sorted by natcasesort.
              $sorted = $filtered + $sorted;
              ?>
              <?php foreach ($sorted as $i => $display): ?>
                <?php $value = $list['list'][$i]; ?>
                <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected']) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($display)?></option>
              <?php endforeach; ?>
              </select><?php /** MSU */ ?>
            <?php endif; ?>
          <?php /** MSU Code removed */ ?>
        </div>
      <?php endforeach; ?>
    </div>
  </fieldset>
<?php endif; ?>
