<?php
  $this->assetManager()->appendStyleLink('EDS.css');
?>
<div class="media"<?=$this->schemaOrg()->getAttributes(['vocab' => 'http://schema.org/', 'resource' => '#record', 'typeof' => $this->schemaOrg()->getRecordTypes($this->driver)])?>>
  <?php
    $this->layout()->showSearchBacklink = true; // MSU
    $user = $this->auth()->isLoggedIn(); // MSU
    $isCommunityBorrower = $user != null ? $this->auth()->isCommunityBorrower() : false; // MSU
    $isOnCampus = $this->auth()->isOnCampus(); // MSU
    $libkeyData = $this->record($this->driver)->getLibKeyData($this->driver->getCleanDOI()); // MSU
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium');
    $cover = $coverDetails['html'];
  ?>
  <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
    <?php if ($cover): ?>
      <?=$cover?>
    <?php endif; ?>

    <?php if (($isCommunityBorrower && $isOnCampus) || ($user && !$isCommunityBorrower)): // MSU ?>
    <div class="external-links">
      <?php $pLink = $this->driver->getPLink();
          if ($pLink): ?>
        <span>
          <?=$this->icon('external-link', 'icon-link__icon') /** MSU */ ?>
          <a href="<?=$this->escapeHtmlAttr($pLink)?>">
            <?=$this->transEsc('View in EDS')?>
          </a>
        </span>
      <?php endif; ?>
      <?php if ($this->permission()->isAuthorized('access.EDSExtendedResults')): ?>
        <?php if ($this->driver->hasHTMLFullTextAvailable()): ?>
          <span>
            <?=$this->icon('external-link', 'icon-link__icon') /** MSU */ ?>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>#html" class="icon--eds html fulltext">
              <?=$this->transEsc('HTML Full Text')?>
            </a>
          </span>
        <?php endif; ?>
        <?php if ($ftLink = $this->driver->getLinkedFullTextLink()): ?>
          <span>
            <?=$this->icon('external-link', 'icon-link__icon') /** MSU */ ?>
            <a href="<?=$ftLink?>" class="fulltext">
              <?=$this->transEsc('Linked Full Text')?>
            </a>
          </span>
        <?php endif; ?>
        <?php if ($pdfLink = $this->driver->getPdfLink()): ?>
          <span>
            <?=$this->icon('external-link', 'icon-link__icon') /** MSU */ ?>
            <a href="<?=$pdfLink?>" class="icon--eds pdf fulltext">
              <?=$this->transEsc('PDF Full Text')?>
            </a>
          </span>
        <?php endif; ?>
        <?php if ($epubLink = $this->driver->getEpubLink()): ?>
          <span>
            <?=$this->icon('external-link', 'icon-link__icon') /** MSU */ ?>
            <a href="<?=$epubLink?>" class="icon--eds epub fulltext">
              <?=$this->transEsc('ePub Full Text')?>
            </a>
          </span>
        <?php endif; ?>
      <?php else: ?>
        <?=$this->render('RecordDriver/EDS/result-list/full-text-links.phtml', ['driver' => $this->driver, 'recordLinker' => $this->recordLinker()])?>
      <?php endif; ?>
    </div>
    <?php elseif ($pLink || $this->permission()->isAuthorized('access.EDSExtendedResults')): /** MSU START */ ?>
       <span>
        <a class="login" href="<?=$this->url('myresearch-userlogin')?>" data-lightbox rel="nofollow">
          <span class="icon icon--font fa fa-sign-in icon-link__icon" role="img" aria-hidden="true"></span>
          <strong><?=$this->transEsc('Login for full access')?></strong>
        </a>
       </span><br>
  <?php endif; ?>
    <?=$this->render('RecordDriver/EDS/libkey-link.phtml', ['link' => $libkeyData['pdf'],
                                           'label' => 'Download PDF',
                                           'openAccess' => $libkeyData['openAccess']]); ?>
    <?=$this->render('RecordDriver/EDS/libkey-link.phtml', ['link' => $libkeyData['article'],
                                           'label' => 'View Article',
                                           'openAccess' => $libkeyData['openAccess']]); ?>
    <?=$this->render('RecordDriver/EDS/libkey-link.phtml', ['link' => $libkeyData['issue'],
                                           'label' => 'View Full Issue',
                                           'openAccess' => $libkeyData['openAccess']]); ?>
    <?php /** MSU END */ ?>
  </div>
  <div class="media-body">

    <h1<?=$this->schemaOrg()->getAttributes(['property' => 'name'])?>><?=$this->driver->getTitle()?></h1>

    <?php if ($this->driver->getExtraDetail('cached_record') && !$this->translationEmpty('cached_record_warning')): ?>
      <div class="alert alert-warning">
        <?=$this->transEsc('cached_record_warning')?>
      </div>
    <?php endif; ?>
    <?=$this->record($this->driver)->getLabelList() ?>

    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php if (!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary(); ?>
    <?php if ($summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if (strlen($summary) > 300): ?>
        <p><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'Description'))?>#tabnav"><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?=
      $this->record($this->driver)->renderTemplate(
          'core-fields.phtml',
          [
            'driver' => $this->driver,
            'defaults' => 'core',
          ]
      );
    ?>
    <?php /* End Main Details */ ?>
    <div class="resultItemLine4 custom-links">

    <?php $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
    if (!empty($customLinks)): ?>
      <?php foreach ($customLinks as $customLink): ?>
        <?php
          $url = $customLink['Url'] ?? '';
          $mot = $customLink['MouseOverText'] ?? '';
          $icon = $customLink['Icon'] ?? '';
          $name = $customLink['Text'] ?? '';
        ?>
        <div>
          <!-- MSU add external link icon -->
          <?php if ($icon): ?><img alt="" src="<?=$this->escapeHtmlAttr($icon)?>" />
          <?php else: ?><?=$this->icon('external-link', 'icon-link__icon') ?><?php endif; ?>
          <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
            <?=$this->escapeHtml($name)?>
          </a>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php $identifierLinksHtml = $this->identifierLinker($this->driver, 'record'); ?>
    <?php if ($identifierLinksHtml): ?>
      <div><?=$identifierLinksHtml?></div>
    <?php endif; ?>
    </div>
  </div>
</div>
