<?php if (!empty($this->link)): ?>
    <div class="libkey-link">
      <?=$this->icon('external-link', 'icon-link__icon') ?>
      <a class="icon-link" target="new" href="<?= $this->link ?>">
        <span class="icon-link__label">
            <?= $this->label ?><?= !$this->openAccess ? " <span class='icon fa fa-lock' role='img' aria-hidden='true' data-bs-toggle='tooltip' title='Login required'></span>" : '';?>
        </span>
      </a><br>
    </div>
<?php endif; ?>

