<?php
  // Set page title.
  $this->headTitle($this->translate('System Unavailable'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  $this->layout()->breadcrumbs = '<li class="active">Error</li>';
?>
<div class="alert alert-warning">
  <h2><?=$this->transEsc('System Unavailable')?></h2>
  <p>
    <?=$this->transEsc('The system is currently unavailable due to system maintenance')?>.
    <?=$this->transEsc('Please check back soon')?>.
  </p>
  <p>
    Pleast contact Reference and Discovery Services via their
    <a href="https://lib.msu.edu/rds/askus?ref=catalog">Contact Form</a> or call them
    directly at: 517-353-8700 for assistance.
  </p>
</div>
