<?php
    // TODO PC-895 To remove after PR
    /** @var \Laminas\View\Renderer\PhpRenderer $this */
    /** @var \Catalog\Search\SearchOrigin\AbstractSearchOrigin|null $searchOrigin */
    if (isset($searchOrigin)) {
        $link = $this->url($searchOrigin->getRouteName()) . '?' . http_build_query($searchOrigin->getOriginUrlParamsArray());
        $fieldValue = $this->translate($searchOrigin->getDisplayName());
        ?>
        <nav class="backtoorigin container">
            <p><a href="<?= $link ?>">
                    <?= $this->icon('fa-long-arrow-left', 'fa-long-arrow-left') ?>
                    <?= $this->transEsc($searchOrigin->getLinkTranslationKey(), ['%%field%%' => $fieldValue]) ?>
                </a></p>
        </nav>
        <?php
    }
