<?php
$checkboxFilters = $this->checkboxFilters;
$filterList = $this->filterList;
$filterCount = $this->searchbox()->getFilterCount($this->checkboxFilters, $this->filterList);
$skip = false;
if ($filterCount == 1) {
    if (count($filterList) != 1) {
        foreach ($checkboxFilters as $filter) {
            if ($filter['selected'] && $filter['desc'] == 'eds_expander_fulltext') {
                $skip = true;
            }
        }
    }
}

if (!$skip) {
    include $this->parentTemplate('search/filters.phtml');
}
