<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->breadcrumbs()->disable();

  /** MSU Start */
  $homePaths = [
      '/',
      '/search',
      '/search/home',
      '/eds',
      '/eds/home',
      '/combined',
      '/combined/home',
      '/browse/home',
      '/alphabrowse/home',
  ];
  $currentPath = rtrim($this->currentPath(), '/') ?: '/';
  $this->layout()->isHome = in_array(strtolower($currentPath), $homePaths);
  /** MSU End */
?>

<?php // this div might be updated dynamically to contain the ILS offline message ?>
<div class="searchHomeContent"></div>

<main>
  <?= $this->context($this)->renderInContext('search/searchbox.phtml', []) ?>
  <?= implode('', array_map([$this, 'contentBlock'], $blocks ?? [])) ?>
</main>
