<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  // MSU - Setting this to false removes header search from EDS,combined
  //$this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->layout()->breadcrumbs = false;
  // MSU -- render searchbox right away, otherwise tab underlining will fail
  $this->layout()->searchbox = $this->context($this)->renderInContext('search/searchbox.phtml', []);
?>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
