<?php
    // Set up page title:
    $this->headTitle($this->translate('New Item Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('New Items') . '</li>';
    //Load the javascript
    $this->assetManager()->appendScriptLink(
        $this->advancedSearchJsOverride ?? 'advanced_search.js'
    );
    //Add expanders
    $this->extraAdvancedControls = $this->render('search/advanced/solr.phtml');

    // Convenience variable:
    $offlineMode = $this->ils()->getOfflineMode();
    $this->layout()->searchbox = false; /** MSU */
    $this->defaultSort = 'first_indexed'; /** MSU */
?>
<div style="display: none" id="jsContent">
  <div class="expander">
    <span class="chevronRight"><?= $this->icon('chevron-right') ?></span>
    <span class="chevronDown"><?= $this->icon('chevron-down') ?></span>
  </div>
</div>
<h1><?=$this->transEsc('Find New Items')?></h1><?php /** MSU */ ?>
<?php if ($offlineMode == 'ils-offline'): ?>
  <?=$this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message'])?>
<?php endif; ?>
<form method="get" class="form-search-newitem">
  <?php if (!empty($this->defaultSort)): ?>
    <input type="hidden" name="sort" value="<?=$this->escapeHtmlAttr($this->defaultSort)?>">
  <?php endif; ?>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('Range')?>:</label>
    <div class="btn-group" data-bs-toggle="buttons">
      <?php foreach ($this->ranges as $key => $range): ?>
        <label class="btn btn-primary<?php if ($key == 0): ?> active<?php endif ?>">
          <input type="radio" name="range" id="newitem_range_<?=$this->escapeHtmlAttr($key)?>" value="<?=$this->escapeHtmlAttr($range)?>"<?=($key == 0) ? ' checked="checked"' : ''?>>
          <!-- MSUL -- Add span element for styling -->
          <span class="msul-btn-group-span"><?=$this->transEsc('past_days', ['range' => $this->escapeHtml($range)], null, true)?></span>
        </label>
      <?php endforeach; ?>
    </div>
  </div>
  <?=$this->render('search/advanced/solr-facets.phtml')?>
  <?php if (is_array($this->fundList) && !empty($this->fundList)): ?>
    <div class="form-group">
      <label class="control-label" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
      <select id="newitem_department" name="department" size="10" class="form-control">
      <?php foreach ($this->fundList as $fundId => $fund): ?>
        <option value="<?=$this->escapeHtmlAttr($fundId)?>"><?=$this->transEsc($fund)?></option>
      <?php endforeach; ?>
      </select>
    </div>
  <?php endif; ?>
  <input class="btn btn-primary" type="submit" name="submitButton" value="<?=$this->transEscAttr('Find')?>">
</form>
