<?php
    // Set up page title:
    $this->headTitle($this->translate('Reserves Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Reserves') . '</li>';

    // Convenience variables:
    $reservesLookfor = $this->params->getDisplayQuery();

    $this->searchClassId = 'SolrReserves';
    $this->layout()->searchbox = false; // MSU
?>
<!-- BEGIN MSU -->
<div class="<?=$this->layoutClass('mainbody')?> mb-5">
  <h1 class="mb-5"><?=$this->transEsc('Search For Items on Reserve')?></h1>
  <form class="form-inline mb-4" method="get" name="reservesSearchForm">
    <label class="mb-2 fw-normal" for="reservesSearchForm_lookfor">Search by <strong>Instructor</strong> or by <strong>Course</strong></label><br>
<!-- END MSU -->
    <?php
      $searchboxAttributes = [
        'id' => 'reservesSearchForm_lookfor',
        'type' => 'search',
        'name' => 'lookfor',
        'size' => '38', // MSU
        'value' => $reservesLookfor,
        'aria-label' => $this->translate('search_terms'),
      ];
      if ($placeholder = $this->searchbox()->getPlaceholderText($tabConfig['selected']['id'] ?? $this->searchClassId)) {
        $searchboxAttributes['placeholder'] = $this->translate($placeholder);
      }
      if ($this->searchbox()->autocompleteEnabled('SolrReserves')) {
        $searchboxAttributes['class'] = ' autocomplete form-control searcher:SolrReserves type:Reserves mb-3' // MSU
          . ($this->searchbox()->autocompleteAutoSubmit('SolrReserves') ? ' ac-auto-submit' : '');
        $searchboxAttributes['data-autocomplete-formatting-rules'] = $this->searchbox()->autocompleteFormattingRulesJson('SolrReserves');
      }
    ?>
    <input<?=$this->htmlAttributes($searchboxAttributes)?>>
    <input class="btn btn-primary" type="submit" value="<?=$this->transEscAttr('Find')?>">
  </form>
  <?=
    $this->context($this)->renderInContext(
        'search/filters.phtml',
        [
          'params' => $this->params ?? null,
          'urlQuery' => $this->results?->getUrlQuery(),
          'filterList' => $this->params->getFilterList(true),
          'searchClassId' => $this->searchClassId,
          'checkboxFilters' => [],
        ]
    );
  ?>
  <?=$this->assetManager()->outputInlineScriptString("$('#reservesSearchForm_lookfor').focus()")?>

  <div class="resulthead search-header mb-3"> <!-- MSU -->
    <div class="flip search-stats"> <!-- MSU -->
      <span>
      <?php $qtime = $this->results->getQuerySpeed(); ?>
      <?php if (($recordTotal = $this->results->getResultTotal()) > 0): ?>
        <?php
          $transParams = [
            '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
            '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
            '%%total%%' => $this->localizedNumber($recordTotal),
            '%%lookfor%%' => $this->escapeHtml($reservesLookfor),
          ];
        ?>
        <?=$this->translate('showing_results_of_for_html', $transParams); ?><?php if (false && $qtime): ?>,<?php endif; ?> <!-- MSU -->
      <?php endif; ?>
      <?php if (false && $qtime): ?> <!-- MSU -->
        <?=$this->transEsc('query time')?>: <?=$this->localizedNumber($qtime, 2) . $this->transEsc('seconds_abbrev')?>
      <?php endif; ?>
      </span>
    </div>

    <?php if ($recordTotal > 0): ?>
      <div class="flip search-sort"> <!-- MSU -->
        <?=$this->render('search/controls/sort.phtml')?>
      </div>
    <?php endif; ?>
  </div>
  <?php if ($recordTotal < 1): ?>
    <p class="error"><?=$this->translate('nohit_lookfor_html', ['%%lookfor%%' => $this->escapeHtml($reservesLookfor)]) ?></p>
    <?php if (isset($this->parseError)): ?>
      <p class="error"><?=$this->transEsc('nohit_parse_error')?></p>
    <?php endif; ?>
  <?php else: ?>
    <table class="table table-striped">
    <tr>
      <!-- MSU REMOVE -->
      <th class="course"><?=$this->transEsc('Course')?></th>
      <th class="instructor"><?=$this->transEsc('Instructor')?></th>
      <th class="items"><?=$this->transEsc('Items')?></th>
    </tr>
    <?php foreach ($this->results->getResults() as $record): ?>
      <?php
        $url = $this->currentPath() . $this->escapeHtmlAttr(
            '?inst=' . urlencode($record->getInstructorId())
            . '&course=' . urlencode($record->getCourseId())
            . '&dept=' . urlencode($record->getDepartmentId())
        );
      ?>
      <tr>
        <!-- MSU REMOVE -->
        <td class="course"><a href="<?=$url?>"><?=$this->escapeHtml($record->getCourse())?></a></td>
        <td class="instructor"><a href="<?=$url?>"><?=$this->escapeHtml($record->getInstructor())?></a></td>
        <td class="items"><?=$this->escapeHtml($record->getItemCount())?></td>
      </tr>
    <?php endforeach; ?>
    </table>
    <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results])?>
  <?php endif; ?>
</div>

<?php /* Refine Search Options */ ?>
<div class="<?=$this->layoutClass('sidebar')?>">
  <?php foreach ($this->results->getRecommendations('side') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>
</div>
<?php /* End Refine Search Options */ ?>
