<?php if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <?php foreach ($searchTabs as $tab): ?>
        <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
          <li<?=$tab['selected'] ? ' class="active"' : ''?><?=$this->showCounts ? ' data-show-counts' : ''?>>
            <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?> data-source="<?=$this->escapeHtmlAttr($tab['class'])?>"><?=$this->transEsc($tab['label']); ?></a>
          </li>
        <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
            <?=$block?>
        <?php endif; ?>
    <?php endforeach; ?>
<li class="navtab-digrepo">
      <a target="_blank" href="https://d.lib.msu.edu/"><i class="fa fa-sign-in" aria-hidden="true"></i> Digital Respository</a>
    </li>  </ul>
  <?php if ($this->showCounts): ?>
    <?php $this->headScript()->appendFile('resultcount.js'); ?>
  <?php endif; ?>
<?php endif; ?>
