<?php if (count($searchTabs) > 0): ?>
  <?php
    $hasSelectedTab = false;
    $resultTotal = $this->results?->getResultTotal() ?? -1;
  ?>
  <ul class="nav nav-tabs">
    <?php foreach ($searchTabs as $tab): ?>
      <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
        <?php
          $linkAttributes = [
            'data-source' => $tab['class'],
            'class' => 'nav-link',
          ];
          if ($tab['selected']) {
            $hasSelectedTab = true;
            $linkAttributes['class'] .= ' active';
            $linkAttributes['aria-current'] = 'page';
            if ($this->showCounts && $resultTotal >= 0) {
              $linkAttributes['data-result-total'] = $resultTotal;
            } elseif ($this->showCounts) {
              $linkAttributes['data-search-url'] = $tab['url'];
            }
          } else {
            $linkAttributes['href'] = $tab['url'];
          }
        ?>
        <li class="nav-item<?=$tab['selected'] ? ' active' : ''?>"<?=$this->showCounts ? ' data-show-counts' : ''?>>
          <a<?=$this->htmlAttributes($linkAttributes)?>><?=$this->transEsc($tab['label']); ?></a>
        </li>
      <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
        <?=$block?>
      <?php endif; ?>
    <?php endforeach; ?>
    <?php /** MSU START */ ?>
    <li class="nav-item">
      <a
        href="<?=$this->url('help', ['topic' => 'searchTabInformation'])?>"
        data-lightbox
        class="nav-link search-tips-icon"
        title="Different search types information"
        aria-label="Different search types information"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
          stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
          class="feather feather-info"
        >
          <circle cx="12" cy="12" r="10"></circle>
          <line x1="12" y1="16" x2="12" y2="12"></line>
          <line x1="12" y1="8" x2="12.01" y2="8"></line>
        </svg>
      </a>
    </li>
    <?php /** MSU END */ ?>
    <?php if (!$hasSelectedTab && !$this->translationEmpty('temporary_search_tab_title')): ?>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page"><?=$this->transEsc('temporary_search_tab_title')?></a>
      </li>
    <?php endif; ?>
  </ul>
  <?php if ($this->showCounts): ?>
    <?php $this->assetManager()->appendScriptLink('resultcount.js'); ?>
  <?php endif; ?>
<?php endif; ?>
