<?php
  # TODO is $holding actually an item record? possibly!
  $id=$holding['id'];
  $item_id=$holding['item_id'];
  $check = $holding['check'] ?? false;
  $checkStorageRetrievalRequest = $holding['checkStorageRetrievalRequest'] ?? false;
  $checkILLRequest = $holding['checkILLRequest'] ?? false;
  $getthis = new \Catalog\GetThis\GetThisLoader($record, [$holding]);
?>
<tr vocab="http://schema.org/" typeof="Offer">
  <th class="copy-number">
    <?php if ($holding['callnumber'] ?? false): ?>
      <span><?=$holding['callnumber_prefix'] ? $this->escapeHtml($holding['callnumber_prefix']) . ' ' : '' ?><?=$this->escapeHtml($holding['callnumber'])?></span>
    <?php endif; ?>
    <?php if ($holding['enumchron'] ?? false): ?>
      <span class="enumchron"><?=$this->escapeHtml($holding['enumchron'])?></span>
    <?php endif; ?>
    <?php if ($holding['number'] ?? false): ?>
      &nbsp;(Copy <?=$this->escapeHtml(($holding['number']))?>)
    <?php endif; ?>
  </th>
  <td>
    <?php if ($holding['reserve'] == "Y"): ?>
      <link property="availability" href="http://schema.org/InStoreOnly" />
      <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
    <?php endif; ?>
    <?php if ($holding['use_unknown_message'] ?? false): ?>
      <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
    <?php else: ?>
      <?php if ($holding['availability'] ?? false): ?>
        <?php /* Begin Available Items (Holds) */ ?>
          <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
        <?php if (! $this->driver instanceof VuFind\RecordDriver\EDS && ! $getthis->isOnlineResource($item_id)): ?>
            <a class="<?=$check ? 'checkRequest' : ''?> placehold" data-lightbox href="<?= $this->escapeHtmlAttr("/Record/$id/GetThis?item_id=$item_id") ?>" rel="nofollow"><?=$this->transEsc('Get this')?></a>
        <?php endif; ?>
        <?php if ($holding['storageRetrievalRequestLink'] ?? false): ?>
          <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holding['storageRetrievalRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
        <?php endif; ?>
        <?php if ($holding['ILLRequestLink'] ?? false): ?>
          <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holding['ILLRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
        <?php endif; ?>
      <?php else: ?>
        <?php /* Begin Unavailable Items (Requests) */
            $status=$holding['status'];
            if (in_array($status, array('Aged to lost', 'Claimed returned', 'Declared lost', 'In process',
                'In process (non-requestable)', 'Long missing', 'Lost and paid', 'Missing', 'On order', 'Order closed',
                'Unknown', 'Withdrawn')))
              $status = 'Unavailable ('.$status.')';
            else if (in_array($status, array('Awaiting pickup', 'Awaiting delivery', 'In transit', 'Paged')))
              $status = 'Checked Out ('.$status.')';
            else if ($status == 'Restricted')
              $status = 'Library Use Only';
            else if (!in_array($status, array('Available', 'Unavailable', 'Checked out')))
              $status = 'Unknown status ('.$status.')';
        ?>
        <span class="text-danger"><?=$this->transEsc($status)?><link property="availability" href="http://schema.org/OutOfStock" /></span>
        <?php if ($holding['returnDate'] ?? false): ?>&ndash; <span class="small"><?=$this->escapeHtml($holding['returnDate'])?></span><?php endif; ?>
        <?php if ($holding['duedate'] ?? false): ?>
          &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($holding['duedate'])?></span>
        <?php endif; ?>
        <?php if (($holding['requests_placed'] ?? 0) > 0): ?>
          <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($holding['requests_placed'])?></span>
        <?php endif; ?>
        <?php if (! $this->driver instanceof VuFind\RecordDriver\EDS && ! $getthis->isOnlineResource($item_id)): ?>
            <a class="<?=$check ? 'checkRequest' : ''?> placehold" data-lightbox href="<?= $this->escapeHtmlAttr("/Record/$id/GetThis?item_id=$item_id") ?>" rel="nofollow"><?=$this->transEsc('Get this')?></a>
        <?php endif; ?>
        <?=$this->relais()->renderButtonIfActive($this->driver ?? null)?>
      <?php endif; ?>
      <?php if (isset($holding['item_notes'])): ?>
        <div class="item-notes">
          <b><?=$this->transEsc("Item Notes")?>:</b>
          <ul>
            <?php foreach ($holding['item_notes'] as $item_note): ?>
              <li><?=$this->escapeHtml($item_note) ?></li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <?php /* Embed item structured data: library, barcode, call number */ ?>
    <?php if ($holding['location'] ?? false): ?>
      <meta property="seller" content="<?=$this->escapeHtmlAttr($holding['location'])?>" />
    <?php endif; ?>
    <?php if ($holding['barcode'] ?? false): ?>
      <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($holding['barcode'])?>" />
    <?php endif; ?>
    <?php if ($holding['callnumber'] ?? false): ?>
      <meta property="sku" content="<?=$this->escapeHtmlAttr($holding['callnumber'])?>" />
    <?php endif; ?>
    <?php /* Declare that the item is to be borrowed, not for sale */ ?>
    <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
    <link property="itemOffered" href="#record" />
  </td>
</tr>
