<?php
  $this->layout()->showSearchBacklink = true; // MSU
  $this->metadata()->generateMetatags($this->driver);
  $this->assetManager()->appendScriptLink('get_license_agreement.js'); // MSU
?>
<div class="media"<?=$this->schemaOrg()->getAttributes(['vocab' => 'http://schema.org/', 'resource' => '#record', 'typeof' => $this->schemaOrg()->getRecordTypes($this->driver)])?>>
  <?php
    $QRCode = $this->record($this->driver)->getQRCode('core');
    $largeImage = $this->record($this->driver)->getThumbnail('large');
    $linkAttributes = $largeImage ? ['href' => $largeImage, 'data-lightbox-image' => 'true'] : [];
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $linkAttributes);
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
    $rating = $this->driver->isRatingAllowed();
  ?>
  <?php if ($QRCode || $cover || $preview || $rating): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if ($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if ($QRCode): ?>
        <span class="hidden-xs">
          <br><img alt="<?=$this->transEscAttr('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>">
        </span>
      <?php endif; ?>

      <?php /* Display rating if enabled: */ ?>
      <?php if ($rating): ?>
        <?=$this->record($this->driver)->renderTemplate('rating.phtml')?>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">
    <!-- MSU PC-1354 Use solr field for title to match search results page -->
    <h1<?=$this->schemaOrg()->getAttributes(['property' => 'name'])?>><?=$this->escapeHtml($this->driver->getTitle()) ?></h1>
    <?php //MSUL customization to add hidden fields used in support of PC-606 ?>
    <input type='hidden' id='title_short' value='<?= $this->escapeHtml($this->driver->getRawData()['title_short'] ?? '')?>'/>
    <input type='hidden' id='id' value='<?= $this->escapeHtml($this->driver->getRawData()['id'] ?? '')?>'/>
    <?php if ($this->driver->getExtraDetail('cached_record') && !$this->translationEmpty('cached_record_warning')): ?>
      <div class="alert alert-warning">
        <?=$this->transEsc('cached_record_warning')?>
      </div>
    <?php endif; ?>

    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt mb-3"><?php /** MSU */ ?>
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php if (!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?php /** MSU START */ ?>
    <?php
      $summaries = $this->driver->getSummary();
      $summary = [];
      if (isset($summaries)) {
        for ($i = 0; $i < count($summaries); $i++) {
          if (is_array($summaries[$i])) {
            $link = trim($summaries[$i]['link'] ?? '');
            $curSummary = trim($summaries[$i]['note']) . (empty($link) ? '' : ' = ' . $link);
            $this->escapeHtml($curSummary);
            $summary[] = $curSummary;
          } else {
            $this->escapeHtml($summaries[$i]);
            $summary[] = $summaries[$i];
          }
        }
        $summary = implode(' ', $summary);
      } else {
        $summary = false;
      }
    ?>
    <?php if ($summary): ?>
    <?php /** MSU END */ ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if (strlen($summary) > 300): ?>
        <p><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'TOC'))?>#tabnav"><?=$this->transEsc('Full description')?></a></p><?php /** MSU */ ?>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?=
      $this->record($this->driver)->renderTemplate(
          'core-fields.phtml',
          [
            'driver' => $this->driver,
            'defaults' => 'core',
          ]
      );
    ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
