<?php $alt = $this->link ? trim($this->driver->tryMethod('getTitle') ?? '') : ''; ?>
<?php if ($this->link && !empty($alt)): ?><a tabindex="-1" href="<?=$this->escapeHtmlAttr($this->link)?>" class="record-cover-link"><?php endif; ?> <!--PC-504: added tabindex -->
<?php /* Display thumbnail if appropriate: */ ?>
<?php if ($cover): ?>
  <img src="<?=$this->escapeHtmlAttr($cover); ?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" role="presentation" alt=""> <!--PC-504: made empty alt tag, add role="presentation"-->
<?php elseif ($cover === false): ?>
  <img src="<?=$this->url('cover-unavailable')?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" role="presentation" alt=""> <!--PC-504: added role="presentation"-->
<?php else: ?>
  <div class="ajaxcover">
    <div class="spinner"><?=$this->icon('spinner') ?> <?=$this->translate('loading_ellipsis')?></div>
    <div class="cover-container">
      <img <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>data-context="<?=$this->escapeHtmlAttr($this->context)?>" data-recordsource="<?=$this->escapeHtmlAttr($driver->getSourceIdentifier())?>" data-recordid="<?=$this->escapeHtmlAttr($driver->getUniqueID())?>" data-coversize="<?=$this->escapeHtmlAttr($size)?>" class="recordcover ajax" role="presentation" alt=""> <!--PC-504: made empty alt tag, add role="presentation"-->
    </div>
  </div>
<?php endif; ?>
<?php if ($this->link && !empty($alt)): ?></a><?php endif; ?>
