<?php
 // $data will be an array, containing either strings or arrays. If the element
 // is an array, it will contain keys of 'note' and 'link'
?>
<?php foreach ($data as $title): ?>
  <?php $titleVal = is_array($title) ? $title['note'] ?? '' : $title; ?>
  <?php $linkVal = is_array($title) ? $title['link'] ?? '' : ''; ?>
  <?php if (!empty($titleVal)): ?>
    <a href="<?=$this->record($this->driver)->getLink('title', $titleVal)?>"><?=$this->escapeHtml($titleVal)?></a>
    <?php if (!empty($linkVal)): ?>
      = <?=$this->escapeHtml($linkVal)?>
    <?php endif; ?>
    <br/>
  <?php endif; ?>
<?php endforeach; ?>
