<?php foreach ($this->driver->getSummary() as $summary): ?>
  <?=$this->escapeOrCleanHtml($summary, 'summary', true) ?><br>
<?php endforeach; ?>
<?php $isbn = $this->driver->getCleanISBN(); ?>
<?php foreach ($this->summaries($isbn) as $provider => $content): ?>
  <?php // MSUL customization ?>
  <?php foreach ($content as $summary): ?>
    <?php $htmlContent = str_starts_with($summary, '<') && str_ends_with($summary, '>'); ?>
    <?=$htmlContent ? $summary : ($this->escapeOrCleanHtml($summary, 'summary') . '<br>')?>
  <?php endforeach; ?>
<?php endforeach; ?>
