<?php if (is_array($data)): ?>
  <?php foreach ($data as $field): ?>
      <div class="variant-line" property="keywords">
          <?php $title = trim($field['title'] ?? ''); ?>
          <?php $type = trim($field['type'] ?? ''); ?>
          <?=trim($this->escapeHtml($title))?><?= empty($this->escapeHtml($type)) ? '' : ' [' . $this->escapeHtml($type) . ']'?>
      </div>
  <?php endforeach; ?>
<?php endif; ?>
