<?php
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $id); // MSUL added to use for li id attribute
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->getId();
    $user_id = $this->list->getUser()->getId();
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->getId() : null;
  }
  // Thumbnail
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $this->recordLinker()->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
?>
<li id="record-<?=$safeId?>" class="result<?php if ($this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?> d-flex"><?php // MSUL add 'd-flex' class for a11y reordering checkbox and add a unique id for lightbox rendering ?>
  <?php if ($cover):
    ob_start(); ?>
    <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?> order-2 ms-3"><?php // MSUL added classes 'order-2 ms-3' ?>
      <?=$cover ?>
    </div>
    <?php $thumbnail = ob_get_contents(); ?>
    <?php ob_end_clean(); ?>
  <?php endif; ?>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource">
  <?php if (isset($this->overrideId)): // hiddenOverrideId is used for availability checking for non SOLR records?>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->overrideId) ?>" class="hiddenOverrideId">
  <?php endif; ?>
  <?php if ($recordNumber): ?>
    <?php // MSUL Moved getCheckbox call below ?>
  <?php endif; ?>
  <div class="media">
    <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
    <div class="media-body order-3"><?php /** MSU added 'order-3' */ ?>
      <div class="result-body">
        <div class="resultItemLine1">
          <h2>
            <?php $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
            <?php if (!$missing): ?><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>" class="getFull" data-view="<?=$this->params->getOptions()->getListViewOption() ?>"><?php endif; ?>
              <span class="title"><?=$this->record($this->driver)->getTitleHtml()?></span>
            <?php if (!$missing): ?></a><?php endif; ?>
            <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?><?php /** MSU */ ?>
              <div class="title-alt">
                <?=$this->escapeOrCleanHtml($altTitle, 'title')?>
              </div>
            <?php endforeach; ?>
        <?php /** Many MSU changes below */ ?>
          </h2>
        </div>
        <table><tbody>
          <?php if (!$this->driver->isCollection()): ?>
            <?php $summAuthors = $this->driver->getPrimaryAuthors(); ?>
            <?php if (!empty($summAuthors)): ?>
              <tr class="authors">
                <th><?=$this->transEsc('Authors')?></th>
                <td>
                  <?php $authorCount = count($summAuthors); ?>
                  <?php foreach ($summAuthors as $i => $summAuthor): ?>
                    <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?=$this->escapeHtml($summAuthor)?></a><?=($i + 1 < $authorCount ? ';' : '') ?>
                  <?php endforeach; ?>
                </td>
              </tr>
            <?php endif; ?>
          <?php endif; ?>
          <?php if ($this->driver->isCollection()): ?>
            <?=implode(' ', array_map([$this, 'escapeHtml'], $this->driver->getSummary())); /** MSU */ ?><
          <?php else: ?>
            <?php
              $journalTitle = $this->driver->getContainerTitle();
              $summDate = $this->driver->getPublicationDates();
            ?>
            <tr>
              <?php if (!empty($journalTitle)): ?>
                <th><?=$this->transEsc('Published in')?></th>
                <td>
                  <?=/* TODO: handle highlighting more elegantly here */' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
                  <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
                </td>
              <?php elseif (!empty($summDate)): ?>
                <th><?=$this->transEsc('Published')?></th>
                <td><?=$this->escapeHtml($summDate[0])?></td>
              <?php endif; ?>
            </tr>
            <?php $summInCollection = $this->driver->getContainingCollections(); ?>
            <?php /** MSU: removed code */ ?>
          <?php endif; ?>

          <?php if (!$this->driver->isCollection()) {
            if ($snippet = $this->driver->getHighlightedSnippet()) {
              echo '<tr>';
              if (!empty($snippet['caption'])) {
                echo '<th>' . $this->transEsc($snippet['caption']) . '</th> ';
              }
              if (!empty($snippet['snippet'])) {
                echo '<td>' . $this->translate(
                    'highlight_snippet_html',
                    ['%%snippet%%' => $this->highlight($snippet['snippet'])]
                ) . '</td>';
              }
              echo '</tr>';
            }
          } ?>

          <?php
            $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->record($this->driver)->getTagsFromFavorites(
                $list_id,
                $user_id,
                'tag'
            ) : [];
          ?>
          <?php if (count($listTags) > 0): ?>
            <tr>
              <th><?=$this->transEsc('Your Tags')?></th>
              <td>
                <?php foreach ($listTags as $tag): ?>
                  <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag['tag'])?>"><?=$this->escapeHtml($tag['tag'])?></a>
                <?php endforeach; ?>
              </td>
            </tr>
          <?php endif; ?>
          <?php $listNotes = $this->record($this->driver)->getListNotes($list_id, $user_id); ?>
          <?php if (count($listNotes) > 0): ?>
            <tr>
              <th><?=$this->transEsc('Notes')?></th>
              <td>
                <?php foreach ($listNotes as $note): ?>
                  <?=$this->escapeHtml($note)?><br>
                <?php endforeach; ?>
              </td>
            </tr>
          <?php endif; ?>

          <?php if (count($this->lists ?? []) > 0): ?>
            <tr>
              <th><?=$this->transEsc('Saved in')?></th>
              <?php $i = 0; ?>
              <td>
                <?php foreach ($this->lists as $current): ?>
                  <a href="<?=$this->url('userList', ['id' => $current->getId()])?>"><?=$this->escapeHtml($current->getTitle())?></a><?php if ($i++ < count($this->lists) - 1): ?>,<?php endif; ?>
                <?php endforeach; ?>
              </td>
            </tr>
          <?php endif; ?>
        </tbody><tbody class="callnumAndLocation ajax-availability hidden">
          <?php if ($this->driver->supportsAjaxStatus()): ?>
            <tr>
              <th class="hideIfDetailed"><?=$this->transEsc('Call Number')?></th>
              <td class="callnumber ajax-availability hidden">
                <?=$this->transEsc('loading_ellipsis')?>
            </td>
            </tr><tr>
              <th><?=$this->transEsc('Located')?>:</th>
              <td class="location ajax-availability hidden">
                <?=$this->transEsc('loading_ellipsis')?>
              </td>
              <tr>
                <td class="locationDetails" colspan="2"></td>
              </tr>
            </tr>
          <?php else: ?>
            <?php $summCallNo = $this->driver->getCallNumber(); ?>
            <?php if (!empty($summCallNo)): ?>
              <tr>
                <th><?=$this->transEsc('Call Number')?></th>
                <td><?=$this->escapeHtml($summCallNo)?></td>
              </tr>
            <?php endif; ?>
          <?php endif; ?>
        </tbody><tbody>

          <?php
            /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
               but even if we don't plan to display the link, we still want to get the $openUrl
               value for use in generating a COinS (Z3988) tag -- see bottom of file.
             */
            $openUrl = $this->openUrl($this->driver, 'results');
            $openUrlActive = $openUrl->isActive();
            $identifierLinksHtml = $this->identifierLinker($this->driver, 'results');
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
          ?>
          <?php if ($openUrlActive || $identifierLinksHtml || !empty($urls)): ?>
            <?php if ($openUrlActive): ?>
              <tr><td colspan="2"><?=$openUrl->renderTemplate()?></td></tr>
            <?php endif;?>

            <?php if ($identifierLinksHtml): ?>
              <tr><td colspan="2"><?=$identifierLinksHtml?></td></tr>
            <?php endif; ?>

            <?php $urls = is_array($urls) ? $urls : []; ?>
            <?php if (!$this->driver->isCollection()): ?>
              <?php foreach ($urls as $current): ?>
                <tr><td colspan="2">
                  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext icon-link" target="new">
                    <?=$this->icon('external-link', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></span>
                  </a>
                </td></tr>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>

          <?php if (
            $this->searchOptions($this->driver->getSourceIdentifier())->displayCitationLinksInResults()
            && $links = $driver->tryMethod('getCitations')
          ): ?>
            <tr><td class="result-citation-links" colspan="2">
              <?=$this->record($this->driver)->renderTemplate('data-citations.phtml', ['data' => $links])?>
            </td></tr>
          <?php endif; ?>
        </tbody></table>

        <?=$this->record($this->driver)->getFormatList() ?>

        <?php if (!$openUrlActive && empty($urls) && $this->driver->supportsAjaxStatus()): ?>
          <span class="status ajax-availability hidden"><?=$this->transEsc('loading_ellipsis')?></span>
          <br><br>
        <?php endif; ?>
        <?=$this->record($this->driver)->getPreviews()?>
      </div>

      <div class="result-links hidden-print">
        <?php if ($this->list === null || $this->userlist()->userCanEditList($this->auth()->getManager()->getUserObject(), $this->list)): ?>
          <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><?php if (null !== $list_id):?>&amp;list_id=<?=urlencode($list_id)?><?php endif; ?>" class="edit tool icon-link">
            <?=$this->icon('user-list-entry-edit', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('Edit')?></span>
          </a>
          <?php /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
            $deleteUrl = null === $list_id
                ? $this->url('myresearch-favorites')
                : $this->url('userList', ['id' => $list_id]);
            $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
            $md5Id = md5($id);
          ?>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonClass' => 'btn-link',
                    'buttonLink' => $deleteUrlGet,
                    'buttonIcon' => 'user-list-remove',
                    'buttonLabel' => 'Delete',
                    'confirmId' => 'confirm_delete_item_' . $md5Id,
                ]
            )
          ?>
          <?php
            $escId = $this->escapeJs($id);
            $escSource = $this->escapeJs($source);
            $script = <<<JS
                $('#confirm_delete_item_{$md5Id}').click(function(e) {
                    e.preventDefault();
                    $.post('{$deleteUrl}', {
                                'delete':'{$escId}',
                                'source':'{$escSource}',
                                'confirm':true
                            },
                            function() {
                                location.reload()
                            }
                        );
                });
                JS;
          ?>
          <?=$this->assetManager()->outputInlineScriptString($script);?>
        <?php endif; ?>
        <?=$this->driver->supportsCoinsOpenUrl() ? '<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()) . '"></span>' : ''?>
      </div>
    </div>
    <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <?php endif; ?>
    <?=$this->record($this->driver)->getCheckbox()?><?php /** MSUL moved from line 29 to recorder checkboxes a11y */ ?>
  </div>
</li>
