<?php
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->assetManager()->appendScriptLink('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }
?>
<nav class="record-nav" aria-label="<?=$this->transEscAttr('ajaxview_label_tools'); ?>">
  <ul class="action-toolbar">
    <?php /** MSU START */
      if (method_exists($this->driver, 'getLocation') && !empty($this->driver->getLocation()) && !str_contains(strtolower($this->driver->getLocation()), 'remote storage')): ?>
      <li>
        <a class="map-record toolbar-btn" data-lightbox href="<?= $this->record($this->driver)->getLink('mapit', null) ?>" rel="nofollow" target="_blank" aria-hidden="true"> <!--msul added aria-hidden="true"-->
          <?=$this->icon('format-map') ?>
          <?=$this->transEsc('Map this')?>
        </a>
      </li>

    <?php endif; /** MSU END */ ?>

    <?php if (count($this->driver->getCitationFormats()) > 0): ?>
      <li><?php /** MSU */ ?>
        <a class="cite-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Cite'))?>" rel="nofollow">
          <?=$this->icon('cite') ?>
          <?=$this->transEsc('Cite this')?>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
      <li><?php /** MSU */ ?>
        <a class="sms-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'SMS'))?>" rel="nofollow">
          <?=$this->icon('send-sms') ?>
          <?=$this->transEsc('Text this')?>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->isEmailActionAvailable()): ?>
      <li><?php /** MSU */ ?>
        <a class="mail-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email'))?>" rel="nofollow">
          <?=$this->icon('send-email') ?>
          <?=$this->transEsc('Email this')?>
        </a>
      </li>
    <?php endif; ?>

    <li>
      <a class="print-record toolbar-btn" href="<?=$this->url()->addQueryParameters(['print' => true])?>" rel="nofollow">
        <?=$this->icon('print') ?>
        <?=$this->transEsc('Print')?>
      </a>
    </li>

    <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <?php if (count($exportFormats) > 0): ?>
      <li class="dropdown"><?php /** MSU */ ?>
        <a class="export-toggle toolbar-btn dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>" rel="nofollow" aria-expanded="false" aria-controls="export-options">
          <?=$this->icon('fa-arrow-right', 'fa-arrow-right') /** MSU */ ?>
          <?=$this->transEsc('Export record') /** MSU */ ?>
        </a>
        <ul class="dropdown-menu" id="export-options" role="menu">
          <?php foreach ($exportFormats as $exportFormat): ?>
            <li><?php /** MSU */ ?>
              <a class="dropdown-item" <?php if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow" role="menuitem">
                <?=$this->transEsc('export_to', ['%%target%%' => $this->translate($this->export()->getLabelForFormat($exportFormat))])?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li><?php /** MSU */ ?>
        <?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
          <a class="save-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" rel="nofollow">
            <?=$this->icon('user-favorites') ?>
            <?=$this->transEsc('Add to favorites')?>
          </a>
        <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
          <?=$block ?>
        <?php endif; ?>
      </li>
    <?php endif; ?>
    <?php if (!empty($addThis)): ?>
      <li><?php /** MSU */ ?>
        <a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>">
          <?=$this->icon('addthis-bookmark') ?>
          <?=$this->transEsc('Bookmark')?>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->cart()->isActive()): ?>
      <li>
        <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?>
      </li>
    <?php endif; ?>

    <?php if ($this->config()->get('config')->Record->permanent_link ?? true): ?>
      <li><?php /** MSU */ ?>
        <a class="permalink-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Permalink'))?>" rel="nofollow">
          <?=$this->icon('external-link') ?>
          <?=$this->transEsc('permanent_link')?>
        </a>
      </li>
    <?php endif ?>
  </ul>
</nav>
