<?=$this->doctype()?>
<html lang="<?=$this->layout()->userLang?>"<?php if ($this->layout()->rtl): ?> dir="rtl"<?php endif; ?>>
  <head>
    <?php
      $this->setupThemeResources();
      $this->assetManager()->clearScriptList()->appendStyleLink('help.css');
    ?>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?=$this->assetManager()->outputHeaderAssets()?>
  </head>
  <body>
    <?=$this->layout()->content?>
  </body>
</html>
